### ISSUE TITLE
Add information on packaging API Java facades

### ISSUE THREAD

**Issue by shturec** [eclipse/dirigible#100]
In [api-v3-guidelines](https://github.com/eclipse/dirigible/wiki/api-v3-guidelines) it is not clear where should we place facade Java classes for an API module.
This: "A separate module in the main Eclipse Dirigible repository have to be created under the "content" subfolder containing all the "webjars" modules." doesn't look right and is not sufficient.
After some searching I found out that the Java counterpart of a JS API need to go under the "[api/api-facades](https://github.com/eclipse/dirigible/tree/master/api/api-facades)" folder and a corresponding  maven project in [api-javascript](https://github.com/eclipse/dirigible/tree/master/api/api-javascript) needs  to be prepared to fetch remote git resources from the Git repo where they are actually hosted.

**Comment by delchev** [comment]
Fixed in [api-v4-guidelines](https://github.com/eclipse/dirigible/wiki/api-v4-guidelines)
