### ISSUE TITLE
[OData] Issue to Retrieval OData using API

### ISSUE THREAD

**Issue by ujval-kalal** [eclipse/dirigible#1035]
Issue w.r.t the OData retrieval. unable to retrieve the data using API's.

1. Recently I have updated all the tables with the few columns and then I generated the model.odata. 
2. I unpublished the whole project and ran below sql query in database perspective.
delete from DIRIGIBLE_ODATA;
delete from DIRIGIBLE_ODATA_MAPPING;
delete from DIRIGIBLE_ODATA_SCHEMA;
Results: 0 0 0
3. then I published all the projects freshly and tried to run the application again it didn't work.
4. when trying to fetch meta data using below link it is returning empty no results (https://dirigiblewebide-symetric.cfapps.eu11.hana.ondemand.com/odata/v2/$metadata)
**Output:**
All the API calls are responding with 404 not found status.

**Expected behavior**
All API call should be served successfully 

**Screenshots**

![newly_Added_columns](https://user-images.githubusercontent.com/72190161/129023719-b7e3ba8a-1300-4761-98f1-851b9d73a5a3.png)
![Network_log](https://user-images.githubusercontent.com/72190161/129023722-ef623373-7fed-4018-8695-fbadb1a6e342.png)
[DirigibleWebIDE-2021-08-11 10_02_35.895+0000.txt]
[model.odata.txt](https://github.com/eclipse/dirigible/files/6968106/model.odata.txt)
(https://github.com/eclipse/dirigible/files/6968099/DirigibleWebIDE-2021-08-11.10_02_35.895%2B0000.txt)

**Desktop (please complete the following information):**
 - OS:  windows 10 pro
 - Browser : Google chrome
 - Version 92.0.4515.131 (Official Build) (64-bit)

**Additional context**

**Comment by ujval-kalal** [comment]
[DirigibleWebIDE-2021-08-11 10_02_35.895+0000.txt](https://github.com/eclipse/dirigible/files/6968110/DirigibleWebIDE-2021-08-11.10_02_35.895%2B0000.txt)
[model.odata.txt](https://github.com/eclipse/dirigible/files/6968111/model.odata.txt)

**Comment by ujval-kalal** [comment]
inadvertently Closed the issue so reopened it.

**Comment by delchev** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/114e56745dac72c20ac8b7d2c642d2af22ca9ed6
