### ISSUE TITLE
[Samples] Maintain Samples Repository

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#1059]
Maintain Samples Repository

- Cleanup the current content: https://github.com/eclipse/dirigible-samples
- Create project (subfolder) per each sample from: https://www.dirigible.io/samples/

**Comment by ThuF** [comment]
Fixed with:
- https://github.com/eclipse/dirigible-samples/pull/1
- https://github.com/dirigible-io/dirigible-io.github.io/pull/53
