### ISSUE TITLE
[Synchronizers] Global enable/disable synchronizers service

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#1063]
Provide a REST service which can enable or disable the synchronization process of all the synchronizers globally.
In addition a clear states functionality to be implemented, so that the dependency between synchronizers if any, to take place after enabling again.

**Comment by ThuF** [comment]
Suggestion: instead of enabling/disabling the synchronizers, the intended outcome could be achieved by resetting the synchronization status, as part of the **Publish** action.
