### ISSUE TITLE
Add "Contact Us" information to the dirigible.io website

### ISSUE THREAD

**Issue by danachkov** [eclipse/dirigible#1119]
We should add "Contact Us" details to the dirigible.io website so that we can tell people to contact us if they want to request to join the Slack channel, for example. 

This is not a bad spot for these contact details:

![image](https://user-images.githubusercontent.com/20664881/133098752-9fb66934-9f18-4708-b2bf-93f086c491a7.png)

**Comment by ThuF** [comment]
Progress tracked here: https://github.com/eclipse/dirigible/issues/1120
