### ISSUE TITLE
[Site] Join Slack Workspace

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#1120]
Research how to enable self/public join to our Slack Workspace. As of now, invite only is enabled.

**Comment by krasimirdermendzhiev** [comment]
1.	Choose Allow invitations, and approve invitations for any email address from specific domains.
 https://slack.com/intl/en-bg/help/articles/115004856503-Manage-how-people-join-your-workspace
 
2.	Manage SSO 
 https://slack.com/intl/en-bg/help/articles/220403548-Manage-single-sign-on-settings
 
3.	Share your workspace’s invite link
     https://eclipse-dirigible.slack.com/?redir=%2Fadmin%2Fshared_invites
    -	For security, invite links will expire and can be used by up to 2000 people. If you need to, you can get a new link.
    -	30 days expiration
    -    Set default channel - https://workspace.slack.com/?redir=%2Fadmin%2Fsettings#default_channels

4.	Community inviter
 https://communityinviter.com/
    -	This app hasn’t been reviewed or approved by Slack!!!
    -	It basically let you create a landing page to collect email addresses and send them automatic (or manual if you wish) invitations.
    -	It is completely free to use as it is. If you want to ask some questions, there is a form builder (similar to typeform), this one is for $5/month.
 
5.	Slackin
  https://github.com/rauchg/slackin
    -	A landing page you can point users to fill in their emails and receive an invite (https://slack.yourdomain.com)
    -	An <iframe> badge to embed on any website that shows connected users in realtime with socket.io.
    -	A SVG badge that works well from static mediums (like GitHub README pages)
    -	Abuse prevention via Google reCAPTCHA

6. StackStorm - auto invite users
 https://stackstorm.com/

7. Slack Invite Automation
 https://github.com/outsideris/slack-invite-automation
   -	A tiny web application to invite a user into your Slack team.

**Comment by ThuF** [comment]
The **third** (manual) option, to generate an invite link and update the site, will be selected as go forward option:

Update Slack Join Link commit: https://github.com/dirigible-io/dirigible-io.github.io/commit/1680b769fefb66b52b439c0bc42fff0c01613161

**Comment by ThuF** [comment]
Web forwarding to be created for https://slack.dirigible.io

**Comment by ThuF** [comment]
Web forwarding created: https://github.com/dirigible-io/dirigible-io.github.io/commit/c2627f589a5335a508346f51272fc8437bd5616d
