### ISSUE TITLE
[Core] Add support for ES6 modules

### ISSUE THREAD

**Issue by vmutafov** [eclipse/dirigible#1147]
Currently, the Dirigible supports only [CommonJS modules](https://en.wikipedia.org/wiki/CommonJS). It would be great to support [ES6 modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) as well because it's the standardized and recommended way of modularizing JS code. 

Depends on:
- https://github.com/eclipse/dirigible/issues/1148
- https://github.com/eclipse/dirigible/issues/1149
- https://github.com/eclipse/dirigible/issues/1150
- https://github.com/eclipse/dirigible/issues/1153

**Comment by delchev** [comment]
already in place
