### ISSUE TITLE
[Core] Implement GraalVM file system for ES6 modules resolution

### ISSUE THREAD

**Issue by vmutafov** [eclipse/dirigible#1148]
In order to support ES6 modules in the GraalVM JS executor, several things should be changed in the way of executing JS code. Currently, the JS execution is happening [here](https://github.com/eclipse/dirigible/blob/master/modules/engines/engine-javascript-graalvm/src/main/java/org/eclipse/dirigible/engine/js/graalvm/processor/GraalVMJavascriptEngineExecutor.java#L184). The way we construct the JS context should be changed according to the [GraalVM docs](https://www.graalvm.org/reference-manual/js/Modules/#ecmascript-modules-esm). This means that we should implement a Truffle File System, probably proxying into the Dirigible Repository classes.

**Comment by iwolkov** [comment]
@ThuF Assign this to me.

**Comment by ivanvolkoff** [comment]
Solved by #1263
