### ISSUE TITLE
[IDE] Add Monaco editor support for ES6 modules

### ISSUE THREAD

**Issue by vmutafov** [eclipse/dirigible#1153]
Currently, the Monaco editor in the Dirigible "understands" only the CommonJS modules. We should extend it to work with ES6 modules. The implementation for this could be by providing [`.d.ts` files](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html) for each JS library the Dirigible exposes. 
Although this is probably the best approach so that we can in the future ship Dirigible libraries to be used in other IDE environments, it may be a bit complicated if no tools for generating the `.d.ts` files work for our case. Manual writing the `.d.ts` files would result in having to maintain them manually when anything in the JS libs is changed.

**Comment by ThuF** [comment]
@iwolkov to be assigned

**Comment by ivanvolkoff** [comment]
Solved by #1263
