### ISSUE TITLE
[Releng] Helm Chart Audit

### ISSUE THREAD

**Issue by krasimirdermendzhiev** [eclipse/dirigible#1204]
Audit helm charts and check best practises.

**Comment by krasimirdermendzhiev** [comment]
What can be add it.

1. Using requited function - can provide more detail for error
If we take the installation on Kyma and forget to add --set kyma.apirule.host=<kyma-host>:
```
helm install dirigible dirigible \
--set kyma.enabled=true \
```
We will receive messege something like this
```
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "APIRule" in version "gateway.kyma-project.io/v1alpha1", unable to recognize "": no matches for kind "ServiceBinding" in version "servicecatalog.k8s.io/v1beta1", unable to recognize "": no matches for kind "ServiceBindingUsage" in version "servicecatalog.kyma-project.io/v1alpha1", unable to recognize "": no matches for kind "ServiceInstance" in version "servicecatalog.k8s.io/v1beta1"]
```
But if we add
`value: {{ required "Missing apirule host!" .Values.kyma.apirule.host }}`
We will receive message
```
Error: execution error at (dirigible/templates/dirigible.yaml:70:22): Missing apirule host!
```
2. Chart version
We can validate the kubernetes version with kubeVersion field in chart.yaml

3. Deprecating charts - old version can be marked deprecated

4. License file - A LICENSE file can containing the license for the chart.

5. If you want to run the chart from cloned repository need to add
`--set dirigible.image=dirigiblelabs/dirigible-all`

6. Verify the integrity and origin of a package
[https://helm.sh/docs/topics/provenance/](url)

7. Add more notes
For testing - `helm test dirigible`
For status - `helm status {{ .Release.Name }}`
For get all - `helm get all {{ .Release.Name }}`

8. Naming conventions
`fullnameOverride` -> `fullNameOverride`

9. Every defined property in values.yaml should be documented.
[https://helm.sh/docs/chart_best_practices/values/#document-valuesyaml](url)

10. SecurityContext
allowPrivilegeEscalation: false

**Comment by ThuF** [comment]
@krasimirdermendzhiev thanks for the detailed audit!

Should we create separate issues to track the progress of each item, or they could be tracked here as different commits?

**Comment by krasimirdermendzhiev** [comment]
We can track here as different commits.

**Comment by krasimirdermendzhiev** [comment]
1. Using required function - https://github.com/eclipse/dirigible/pull/1334/commits/eede7f4f9a7b9a6970a1b9862e23447f38249d6c

**Comment by delchev** [comment]
obsolete
