### ISSUE TITLE
[Core] Refactoring of GraalVM Javascript engine

### ISSUE THREAD

**Issue by Fluctuationqt** [eclipse/dirigible#1212]
Create context builder.
Split implementation in separate classes for CommonJS and ES6 and use the context builder in them.
For Truffle File System move logic in path handles (dirigible scoped path handler, absolute/relative path handler, uri path handler)

**Comment by delchev** [comment]
This is the test which should get work again:
https://github.com/eclipse/dirigible/blob/e97c4e1c117e3820d84b4d2d429129bceecdb830/modules/engines/engine-graalium/execution-tests/src/test/java/org/eclipse/dirigible/tests/GraaliumCustomTest.java#L133

**Comment by delchev** [comment]
Fixed: https://github.com/eclipse/dirigible/blob/master/modules/engines/engine-graalium/execution-tests/src/test/java/org/eclipse/dirigible/tests/GraaliumCustomTest.java
