### ISSUE TITLE
[IDE] Database - Run button doesn't work

### ISSUE THREAD

**Issue by dpanayotov** [eclipse/dirigible#1215]
From xsk created by [dpanayotov](https://github.com/dpanayotov): SAP/xsk#645  

**Describe the bug**
Run button does not execute the statements 

**To Reproduce**
1. Open Database perspective
2. Write some SQL statement
3. Click the Run button
4. See that nothing happens

**Expected behavior**
Clicking the Run button executes the SQL statements (preferably the selected ones) and the result is displayed below.

**Comment by dimitarquanterall** [comment]
Please, assign to me
