### ISSUE TITLE
[IDE] Hide technical implementation details

### ISSUE THREAD

**Issue by dpanayotov** [eclipse/dirigible#1219]
From xsk created by [dpanayotov](https://github.com/dpanayotov): SAP/xsk#661  

**Describe the solution you'd like**
Identify and replace technical implementation details with user friendly text messages.
Example: `Right click > Open with > Monaco` to be `Code Editor` for example. Monaco as the underlying editor may not make sense to be presented to the user

**Comment by iwolkov** [comment]
assign this to me
