### ISSUE TITLE
[IDE] Loading indicator

### ISSUE THREAD

**Issue by dpanayotov** [eclipse/dirigible#1221]
From xsk created by [dpanayotov](https://github.com/dpanayotov): SAP/xsk#662  

**Is your feature request related to a problem? Please describe.**
There's no easy way to describe if something is loading or if it's loaded and no information is shown. 

**Describe the solution you'd like**
Whenever a view is loading content, there needs to be an indicator.

fundamentals-ngx defines budy indicator - https://sap.github.io/fundamental-ngx/#/core/busy-indicator

**Comment by vmutafov** [comment]
We could probably use the CSS only version of the busy indicator: https://sap.github.io/fundamental-styles/?path=/docs/components-busy-indicator--standard

We should add the CSS sheets as in here or by using some other CDN: https://www.npmjs.com/package/fundamental-styles/v/0.5.1-rc.0

**Comment by iwolkov** [comment]
assign this to me

**Comment by dimitarquanterall** [comment]
and co-assign to me

**Comment by ivanvolkoff** [comment]
- [ ] ide-git

**Comment by ivanvolkoff** [comment]
Solved by #1381
