### ISSUE TITLE
[IDE] Can't close welcome screen

### ISSUE THREAD

**Issue by dpanayotov** [eclipse/dirigible#1222]
From xsk created by [dpanayotov](https://github.com/dpanayotov): SAP/xsk#663  

**Describe the bug**
Welcome tab cannot be closed unlike any other tab

**Additional context**
![image](https://user-images.githubusercontent.com/4910295/137884244-b28d7264-0d61-4ec3-ad68-484516245cdf.png)

**Comment by StanZGenchev** [comment]
This is not a bug. We did decide that the welcome screen is a special case and should not be closable.
See issue #900
