### ISSUE TITLE
[IDE] Delete many to prompt only once

### ISSUE THREAD

**Issue by dpanayotov** [eclipse/dirigible#1223]
From xsk created by [dpanayotov](https://github.com/dpanayotov): SAP/xsk#664  

**Is your feature request related to a problem? Please describe.**
Marking multiple files/folders for deletion opens a confirmation prompt for each selected file.

**Describe the solution you'd like**
Only 1 confirmation pop-up is shown with a message similar to `Are you sure you want to delete the following N files?`

**Comment by dimitarquanterall** [comment]
https://github.com/dirigiblelabs/ide-workspace/pull/2 will fix this after being merged.

**Comment by dimitarquanterall** [comment]
Fixed in dirigible by https://github.com/dirigiblelabs/ide-workspace/pull/2
The issue may be closed
