### ISSUE TITLE
[CMS] CSVIM Synchronizer

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#1276]
Implement a Synchronizer for CSVIM files

**Comment by delchev** [comment]
This will be the way forward for DATA imports for the predefined ones such as nomenclatures or test data. The other formats *.append, *.replace, *.delete and *.update DSV files to be deprecated.

**Comment by ThuF** [comment]
Artefacts state to be tracked, as implemented in: https://github.com/eclipse/dirigible/commit/9177bdc2f505c38d506640549f9e94359be6a1bf
