### ISSUE TITLE
[Synchronizer] Introduce corresponding types for the supported artefacts

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#1277]
Add type support for the existing artefacts to be integrated with the State management during the synchronization:

- [x] BPMN - fixed with https://github.com/eclipse/dirigible/commit/8dcab48f6ac2a6ff8da5eab71e2018bfa4a720e7
- [x] ChangeLog - fixed with https://github.com/eclipse/dirigible/commit/339a8ed35c430831b8104bd1929b9eccca7b12c4
- [x] Table - fixed with https://github.com/eclipse/dirigible/commit/1ec038e6305983ec49d98eea54ac49caed4fa9d5
- [x] View - fixed with https://github.com/eclipse/dirigible/commit/1ec038e6305983ec49d98eea54ac49caed4fa9d5
- [x] Replace - fixed with https://github.com/eclipse/dirigible/commit/1ec038e6305983ec49d98eea54ac49caed4fa9d5
- [x] Append - fixed with https://github.com/eclipse/dirigible/commit/1ec038e6305983ec49d98eea54ac49caed4fa9d5
- [x] Update - fixed with https://github.com/eclipse/dirigible/commit/1ec038e6305983ec49d98eea54ac49caed4fa9d5
- [x] Delete - fixed with https://github.com/eclipse/dirigible/commit/1ec038e6305983ec49d98eea54ac49caed4fa9d5
- [x] Schema - fixed with https://github.com/eclipse/dirigible/commit/d763fc2d9b202c4d05d43f8c6f39ef3ef7ad4a03
- [x] CSVIM - to be fixed with https://github.com/eclipse/dirigible/issues/1276
- [x] CSV - to be fixed with https://github.com/eclipse/dirigible/issues/1276
- [x] ExtensionPoint - fixed with https://github.com/eclipse/dirigible/commit/3f0fd5244eb16a9a0a5a4596322b549c7a6c1b70
- [x] Extension - fixed with https://github.com/eclipse/dirigible/commit/3f0fd5244eb16a9a0a5a4596322b549c7a6c1b70
- [x] Job - fixed with https://github.com/eclipse/dirigible/commit/d6cb13de26c7344dc5fa6d18411d4e27efc1d46e
- [x] Listener - fixed with https://github.com/eclipse/dirigible/commit/f0ac770c9c898bf17a3ca47c0d47eda0b190c9d8
- [x] Migration - fixed with https://github.com/eclipse/dirigible/commit/dfdf1cf486e09f565a820bdf593198a7f8907583
- [x] OData - fixed with https://github.com/eclipse/dirigible/commit/57e7ec7107cd3315be8b391572c747ae9819dbae
- [x] Access - fixed with https://github.com/eclipse/dirigible/commit/cef382bab15f39ffcbd3fe06dcba7f8ed1f7a336
- [x] Role - fixed with https://github.com/eclipse/dirigible/commit/cef382bab15f39ffcbd3fe06dcba7f8ed1f7a336
- [x] Websocket - fixed with https://github.com/eclipse/dirigible/commit/9177bdc2f505c38d506640549f9e94359be6a1bf

The definition example:

https://github.com/eclipse/dirigible/blob/53aa38ae4acf1300e3d97b2087e1c82b7875343c/modules/database/database-data-structures/src/main/java/org/eclipse/dirigible/database/ds/artefacts/TableSynchronizationArtefactType.java

https://github.com/eclipse/dirigible/blob/53aa38ae4acf1300e3d97b2087e1c82b7875343c/modules/database/database-data-structures/src/main/resources/META-INF/services/org.eclipse.dirigible.core.scheduler.api.ISynchronizerArtefactType

The actual integration is specific to each artefact and its synchronizer

**Comment by ThuF** [comment]
Fixed, artefacts state tracked for all except `*.csv` and `*.csvim`. To be fixed with:
- https://github.com/eclipse/dirigible/issues/1276
