### ISSUE TITLE
Logs cleanup in Dirigible v3

### ISSUE THREAD

**Issue by shturec** [eclipse/dirigible#129]
The log streams need a thorough examination as we currently can observe a number of useless messages that diminish the value of logging and hinder tracing issues.
As a start, we will need criteria that puts usefulness as priority first and then execute based on that.
An important part of this plan would be to conveniently tune the streams severity thresholds without restarting the server. (we'll have a separate issue created for that)

1. Reconsider the setup the logging destinations the the type of logs they comprise:
- IDE Console Log appender destination will be destination for applications log appenders and mostly JS runtime. Dirigible code logs, unless directly influencing application code, are non of my concern as a consumer in the IDE.
- File appender should be spearated to application and 'sink all' files. The application file log is a (persistent) mirror of what we see in the IDE Console Log appender. It's important to have such backup copy as a more reliable mechanism for exploring and sharing issue traces. The 'sink all' file collects all logs for a holistic view on the system execution logs. Should be a rolling update file as it will tend to grow large.
- Console Log appender should be fairly muted and log only errors. 

2. Log Quality. 
- Tune the logging streams for usefulness on purpose and severity. Always log with purpose and check logs for usefulness against that purpose. Ask yourself "As a developer tracing X, does that help me?".
- Design messages to be brief, yet sufficient. Avoid redundancies. Make it traceable with context.
- Do log. Remember: if it wasn't logged. It didn't happen. However, consider the previous points, because if it's not traceable due to log quality, it equally didn't happen. Ask yourself the question: "Can I understand what happened in this situation only from the log, or I need to insert console message and recreate the situation?" Do not anticipate. Simulate and try to explore the log like another person would.

**Comment by delchev** [comment]
done
