### ISSUE TITLE
Resilient log files destinations

### ISSUE THREAD

**Issue by shturec** [eclipse/dirigible#131]
Logs are currently written to Dirigible's server local file system. In a dynamic IasS platform where failures must be anticipated as a norm, we need a proven resilient solution.

One simple solution would be to write logs to mounted volume provided by the IaaS that is physically detached from the Dirigible instance.

Another option is to use the [DB Appender](https://logback.qos.ch/manual/appenders.html#DBAppender) and the (managed) DB service provided in the IaaS and shared for the Dirigible instances.

Another one, is to use the distributed agent facility in logback, which essentially provides TCP networking for log events which are streamed to a (managed) destination service, provided that such networking would be allowed.

And yet another one would be similar to the second, but with a custom solution to stream the log files to a desired location/service endpoint.  

Another option would be to stream directly the log events. For example, **opentracing** (http://opentracing.io/) works similar to slf4j but for distributed tracing systems, and provides a common protocol and concrete language bindings (API) that work with concrete distributed tracing systems such as **zipkin** (https://github.com/openzipkin/zipkin). This would be a more comprehensive solution that considers the problem of tracing (in logs) and not simply logs replication. However it also comes at the cost of the complexity of a distributed system. 

This issue is to ensure that it is possible to configure Dirigible 's file log appenders produced logs to survive host environment crashes at least with the first option, and ideally for any.

**Comment by delchev** [comment]
won't fix as IaaS providers already have such features in place
