### ISSUE TITLE
[IDE] Track changed rows on the fly

### ISSUE THREAD

**Issue by dimitarquanterall** [eclipse/dirigible#1327]
**Is your feature request related to a problem? Please describe.**
There is no way to track rows differing the Git version of a file with the one displayed on screen without using the inconvenient DiffEdiror.

**Describe the solution you'd like**
Using JSDiff as a tool we can track which rows are altered and display a small mark  to the left of them.

**Describe alternatives you've considered**
Using DiffEditor by Monaco Editor itself in the background seems to be also a solution but wasted too many resources.

**Comment by delchev** [comment]
obsolete
