### ISSUE TITLE
[OData] Samples - Northwind

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#1333]
Add a sample project (Java) showcasing the OData capabilities of Eclipse Dirigible, through the popular OData Northwind sample model, that could be found here: https://services.odata.org/V2/Northwind/Northwind.svc/

## Required Entities
- [x] **Categories** - fixed with https://github.com/eclipse/dirigible/commit/7d80ab74494a359818f5949ca41a7650d4a57769
- [x] **CustomerDemographics** - fixed with https://github.com/eclipse/dirigible/commit/7d80ab74494a359818f5949ca41a7650d4a57769
- [x] **Customers** - fixed with https://github.com/eclipse/dirigible/commit/7d80ab74494a359818f5949ca41a7650d4a57769
- [x] **Employees** - fixed with https://github.com/eclipse/dirigible/commit/7d80ab74494a359818f5949ca41a7650d4a57769
- [x] **Order_Details** - fixed with https://github.com/eclipse/dirigible/commit/7d80ab74494a359818f5949ca41a7650d4a57769
- [x] **Orders** - fixed with https://github.com/eclipse/dirigible/commit/b2af07e97283b9949ce63fd95daf8752c8b2ed94
- [x] **Products** - fixed with https://github.com/eclipse/dirigible/commit/b2af07e97283b9949ce63fd95daf8752c8b2ed94
- [x] **Regions** - fixed with https://github.com/eclipse/dirigible/commit/b2af07e97283b9949ce63fd95daf8752c8b2ed94
- [x] **Shippers** - fixed with https://github.com/eclipse/dirigible/commit/b2af07e97283b9949ce63fd95daf8752c8b2ed94 
- [x] **Suppliers** - fixed with https://github.com/eclipse/dirigible/commit/ed15f0b24749b942dc55c2560dbaa09451303989
- [x] **Territories** - fixed with https://github.com/eclipse/dirigible/commit/ed15f0b24749b942dc55c2560dbaa09451303989
- [x] **Invoices** - fixed with https://github.com/eclipse/dirigible/commit/ed15f0b24749b942dc55c2560dbaa09451303989

## Optional Entities
- [x] **Alphabetical_list_of_products**
- [x] **Category_Sales_for_1997**
- [x] **Current_Product_Lists**
- [x] **Customer_and_Suppliers_by_Cities**
- [x] **Order_Details_Extendeds**
- [x] **Order_Subtotals**
- [x] **Orders_Qries**
- [x] **Product_Sales_for_1997**
- [x] **Products_Above_Average_Prices**
- [x] **Products_by_Categories**
- [x] **Sales_by_Categories**
- [x] **Sales_Totals_by_Amounts**
- [x] **Summary_of_Sales_by_Quarters**
- [x] **Summary_of_Sales_by_Years**

**Comment by ThuF** [comment]
@mit-ko Do you have a suggestion how we can handle the following difference in the scale of **DECIMAL** values?

HTTP GET: https://services.odata.org/V2/Northwind/Northwind.svc/Categories(1)/Products?$format=json

**Scale Diff**:
```diff
{
   "ProductID":1,
   "ProductName":"Chai",
   ...
-   "UnitPrice":"18.0000"
+   "UnitPrice":"18"
   ...
}
```

The **expected**  value should be: `"UnitPrice":"18.0000"`, while the actual value is: `"UnitPrice":"18"`

> **Note:** Product UnitPrice definition in our sample model could be found [here](https://github.com/eclipse/dirigible/blob/master/modules/odata/odata-samples-northwind/src/test/java/org/eclipse/dirigible/engine/odata2/sql/entities/northwind/Product.java#L45-L46).

**Comment by delchev** [comment]
done
