### ISSUE TITLE
[IDE] Copy existing to show prompt

### ISSUE THREAD

**Issue by dpanayotov** [eclipse/dirigible#1367]
Issue cloned from https://github.com/SAP/xsk/issues/919

### Background
If I copy a directory that already exists I don't get prompt what to do. The process just fails and I get no message what happened. 
If I copy `file.txt` in a directory which contains `file.txt` it'll actually create another file called `file (copy 1).txt`

#### File behavior
When a file is copied to a directory in which the same one exists, a prompt must be shown to the user.
Options should be `Replace`, `Replace all` (if more than 1 file is conflicting), `Skip`.
If you choose `Replace` it must overwrite only this file. Then, the dialog must be shown for the next file.
If you choose `Replace all` it must replace all the files that are duplicates.
If you choose `Skip` this file must be skipped and the operation must continue with the next file.

#### Directory behavior
When a directory is copied to a directory in which one with the same name exists, a prompt must be shown to the user only if there are conflicting files. Otherwise just merge the two directories.
The behavior should be that for each file the algorithm above must be followed. Essentially it translates to:
1. If file does not exist - copy it
2. If file exists - show dialog from above

**Comment by dimitarquanterall** [comment]
Fixed by https://github.com/eclipse/dirigible/pull/1657
The issue may be closed after the PR is merged.
