### ISSUE TITLE
[IDE Git] Attempt to clone a huge project leads to infinite error messaging

### ISSUE THREAD

**Issue by dimitarquanterall** [eclipse/dirigible#1378]
**Describe the bug**
Cloning a huge project fails. While this is probably expected, system behaviour after such a clone attempt is non-informative and loops in error state. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Git perspective.
2. Clone a huge project, for example Node.js (https://github.com/nodejs/node.git)
3. After a while you will see an error message just saying "Loading Git Repositories Error!" What kind of error occurred is not clear for the user. 
4. If Git perspective is refreshed / reloaded the message appears again and again on each refresh. "TypeError: data is undefined" is logged into console.
5. If trying to clone another repository "No space left on device" error is displayed. 

**Expected behaviour**
If a project is too big to be cloned it should be be expected to:
- display reasonable error message;
- delete all temporary data of the unsuccessfully cloned project in order to leave unusable space. 

**Desktop (please complete the following information):**
 - Linux Mint
 - Firefox
 - 84.0.2 (64-bit)

**Comment by delchev** [comment]
Non realistic use-case in general, but seems fixed meanwhile
