### ISSUE TITLE
[IDE] Moving Monaco tab loses unsaved changes

### ISSUE THREAD

**Issue by dimitarquanterall** [eclipse/dirigible#1379]
**Describe the bug**
Moving an the tab of a file being edited leads to losing unsaved changes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Workbench perspective.
2. Open several files.
3. Make some changes in any of the files. Do not save! 
4. Drag and drop file's tab to the right or to the left, or even move it to another section. 
5. The editor reloads on its new place and all unsaved changes are lost.

**Expected behaviour**
Not losing unsaved changes by just moving a tab. 

**Desktop (please complete the following information):**
 - Linux Mint
 - Firefox
 - 84.0.2 (64-bit)

**Comment by delchev** [comment]
obsolete
