### ISSUE TITLE
Dirigible Installation Issue: HTTP Status 404 – Not Found

### ISSUE THREAD

**Issue by jugluck** [eclipse/dirigible#1383]
Hello All:
I tried to set up locally Eclipse Dirigible using Tomcat. I followed the instructions given in the following link as shown
The installation details are
a) OS: Windows 10
b) Tomcat: 8.5.73
c) Eclipse Dirigible- 6.1.12
d) Java: jre1.8.0_311
When I try to open the localhost http://localhost:8080/ page, I get the following error as shown below. I have re-installed my tomcat and also followed different instructions on the web but I am unable to launch Dirigible. Can someone guide me as to what is amiss ?

HTTP Status 404 – Not Found

Type Status Report

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
Apache Tomcat/8.5.73

**Comment by ThuF** [comment]
Hi, could you please try with Java 11 or later, as it’s a prerequisite: https://www.dirigible.io/help/setup/

**Comment by jugluck** [comment]
Thuf:
Thanks for your response. This is what I have updated
Java: jdk 17.0.1
Tomcat: 10.0.14
Eclipse Dirigible- 6.1.12
I dont have issues while loading the tomcat server by itself after tomcat installation. But after deleting the original files under webapp folder, copying the root.war files  and running the catalina.bat file I open the browser to the following location http://localhost:8080/ .
I am still getting the following error as shown below.

![image](https://user-images.githubusercontent.com/52330831/147371580-c895b913-8bc2-4121-bda4-4b2e34a707f5.png)

**Comment by ThuF** [comment]
Hi @jugluck, it seems that there was some time ago reported an issue, related to build with Java 15 tracked [here](https://github.com/eclipse/dirigible/issues/1384) (origin can be found [here](https://github.com/SAP/xsk/issues/126)). So assuming that Java 15 isn’t quite there,  I’ll assume that currently it’s not working also with Java 17 or later. To add support for the latest Java versions, could you attach the log files from the `<Tomcat-Location>/logs` directory?

To run Dirigible locally either use one of the supported Java versions (as of now are Java 11 and Java 13), or go with the [Dockers setup](https://www.dirigible.io/help/setup/docker/).

**Comment by jugluck** [comment]
Hello Thuf:
I have tested this with dockers setup. I followed another youtube video from you as a guiding step.
https://www.youtube.com/watch?v=mQ7jIQ9naXU&t=979s.
When I copied and ran the following command as below

_**docker run --name dirigible \
--rm -p 8080:8080 -p 8081:8081 \
dirigiblelabs/dirigible-all:latest**_

I ended up getting the following errors as shown below.

C:\Users\jug>docker run --name dirigible \
docker: invalid reference format.
See 'docker run --help'.

C:\Users\jug>--rm -p 8080:8080 -p 8081:8081 \
'--rm' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\jug>dirigiblelabs/dirigible-all:latest
'dirigiblelabs' is not recognized as an internal or external command,
operable program or batch file.

I have been trying to figure out these messages from other forums but dont have any breakthrough yet. Any pointers ?

**Comment by ThuF** [comment]
Hi @jugluck, could you try to execute the docker command on a single line:

```
docker run --name dirigible 
--rm -p 8080:8080 -p 8081:8081 
dirigiblelabs/dirigible-all:latest
```

->

```
docker run --name dirigible --rm -p 8080:8080 -p 8081:8081 dirigiblelabs/dirigible-all:latest
```

It’s a common issue for Windows with multi-lines commands, as the break new line separator (`\`) is not supported on Windows. To execute such commands you should first delete the `\` separator and the new lines and then execute the command on a single line.

**Comment by jugluck** [comment]
Thanks a ton. That worked for me.
Wishing a Happy New Year !
