### ISSUE TITLE
[Core] XSK Web IDE and Runtime Hangs

### ISSUE THREAD

**Issue by dpanayotov** [eclipse/dirigible#1392]
Issue cloned from https://github.com/SAP/xsk/issues/623

Import the attached project: [workspace-20211014063625.zip](https://github.com/SAP/xsk/files/7343735/workspace-20211014063625.zip)

**Note** that it deliberately references a non-existing schema.

Steps to reproduce:
- Try to load the **xsjs/hello.xsjs** about 20-30 times.
- At some point of time the whole XSK hangs and restart of the pod is required.

**Comment by delchev** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/8e4fff900c809befd765168928dfd2af5c286bd4
