### ISSUE TITLE
Annoying session terminations

### ISSUE THREAD

**Issue by shturec** [eclipse/dirigible#142]
Non-disruptive working sessions are imperative in the UI, especially the IDE. 

However, when the session expires I'm getting an annoying form login that reloads my whole screen, which is unacceptable from Ux perspective. 

If there needs to be session management, it must be fairly transparent. If for some reason you do require user input to refresh the session, which I doubt concerning the IDE, this must be a login control that does not replace and then refresh the whole page, and thus ensures non-disruptive workflow.

Currently, we have some weird effects such as the IDE console view showing a login form with a huge stack trace in the server console informing us for something that coud be expressed significantly more brief, if someone cared at all about that:
2017-11-03 09:52:47.917 [INFO ] [http-nio-8080-exec-3] o.e.d.r.i.c.s.ConsoleWebsocketService - [ws:console] Session 1 closed because of CloseReason: code [1008], reason [This connection was established under an authenticated HTTP session that has ended.]
09:52:47,920 |-ERROR in org.eclipse.dirigible.runtime.ide.console.service.ConsoleLoggingAppender[ConsoleLoggingAppender] - Appender [ConsoleLoggingAppender] failed to append. java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed

**Comment by delchev** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/68448289f50dd336cf4f0b9a357b9d9402f7fef3
