### ISSUE TITLE
IDE client perspective layout is preserved across different IDE instances with same URL

### ISSUE THREAD

**Issue by shturec** [eclipse/dirigible#143]
If you open the IDE in a browser using the same URL, open up a few files form the corresponding workspace, and then start another dirigible instance, and try to open its IDE hosted under the same URL, the previously open files will still be preserved as open tabs despite that they may not even exist in the workspace of the second dirigible instance..

**Comment by delchev** [comment]
Not sure that this has to be fixed or it is a desired effect to preserve the open files in the working perspective. The observed issue above should happen only during development of the Dirigible's core and not during its usage in production, right?

**Comment by shturec** [comment]
It is a desired effect to preserve state indeed. The issue here is that the state preservation mechanism assumes that a URI (without path) identifies uniquely an instance. I realize this may be a corner case bit it could be that instances are fronted by a routing mechanism that redirects to a different instance by query parameters (e.g. ?target='staging' and ?target='prod'), and then the IDE is completely blind that these could be entirely different instances (codebases).

**Comment by delchev** [comment]
To be re-opened on demand
