### ISSUE TITLE
Refactor DBMetaDataUtil inside DatabaseMetadatUtil

### ISSUE THREAD

**Issue by BorisNen** [eclipse/dirigible#1435]
The methods inside engine-odata/DBMetaDataUtil have the same logic as in database-persistence/DatabaseMetadatUtil but are duplicated inside both of them.

1. Check for circular dependencies
2. Refactor the methods from DBMetaDataUtil to DatabaseMetadatUtil
3. Run all tests and check if the logic has been broken

**Comment by delchev** [comment]
done
