### ISSUE TITLE
[API] Add an API for zipping/unzipping 

### ISSUE THREAD

**Issue by vmutafov** [eclipse/dirigible#1461]
Currently, there's an API for reading from and writing into ZIP files but it would be great to have an API for unzipping an archive and zipping a folder. The current API is here: https://www.dirigible.io/api/io/zip/

I suppose having the following API would be a good addition:
```JS

function unzip(zipPath: string, folderOutputPath: string): void;
function zip(folderPath: string, zipOutputPath: string): void;

```

**Comment by ThuF** [comment]
@vmutafov That would be really nice functionality, I suggest to extend the existing ZIP API with the proposed zip/unzip functions?

**Comment by vmutafov** [comment]
Yes, it should be in the current ZIP API. Btw, we actually already need it for one of the tasks in XSK. 😀 @ivanvolkoff will probably work on this task if there is nothing else urgent

**Comment by ThuF** [comment]
Assigned @ivanvolkoff as @vmutafov proposed.

**Comment by vmutafov** [comment]
We should be careful about this interesting vulnerability: https://snyk.io/research/zip-slip-vulnerability

**Comment by vmutafov** [comment]
The [Repository ZIP Importer/Exporter](https://github.com/eclipse/dirigible/tree/master/modules/repository/repository-zip/src/main/java/org/eclipse/dirigible/repository/zip) could probably be reused in the ZipFacade for this feature.
