### ISSUE TITLE
[UI] Adopt fundamental styles - view Git

### ISSUE THREAD

**Issue by dpanayotov** [eclipse/dirigible#1500]
Issue cloned from https://github.com/SAP/xsk/issues/1137

 ### Target
- [ ] Adopt the fundamental styles in Git view

Use https://github.com/dirigiblelabs/ide-next as reference

**Comment by StanZGenchev** [comment]
New design:

![git-mockup-1](https://user-images.githubusercontent.com/82379274/185419437-dadcdaf6-39dc-49ca-a7ba-d15e28e02a41.jpg)
![git-mockup-2](https://user-images.githubusercontent.com/82379274/185419955-923c342a-2752-4236-a238-fca5b5c14025.jpg)
![git-mockup-3](https://user-images.githubusercontent.com/82379274/185419452-b0019595-4a63-4698-b2ec-a053a83fce8a.jpg)
![git-mockup-4](https://user-images.githubusercontent.com/82379274/185419456-9f56d89c-dd94-492e-9e9f-ca06b8fef501.jpg)
![git-mockup-5](https://user-images.githubusercontent.com/82379274/185419462-a91d23ca-d0a3-42e1-a595-d351591cb0c5.jpg)
![git-mockup-6](https://user-images.githubusercontent.com/82379274/185419467-7877050d-ca4c-4ae1-8163-6f43d2101567.jpg)
![git-mockup-7](https://user-images.githubusercontent.com/82379274/185419469-fadbb0e3-0a7e-49f4-a326-fc6706c101a5.jpg)
![git-mockup-8](https://user-images.githubusercontent.com/82379274/185419471-759f9f34-2b64-4a0a-8aa3-d982d349147c.jpg)
![git-mockup-9](https://user-images.githubusercontent.com/82379274/185419475-95c3570c-e7e7-4642-a9b4-3acf16a12de2.jpg)
![git-mockup-10](https://user-images.githubusercontent.com/82379274/185419477-75acc21d-604d-49cd-a2f9-ae58e0d5d10a.jpg)
![git-mockup-11](https://user-images.githubusercontent.com/82379274/185419480-cd8667d4-f88c-459f-9be0-728e6f902582.jpg)
![git-mockup-12](https://user-images.githubusercontent.com/82379274/185419482-07fa882e-0448-4e1c-9cef-c1a1ae0338c6.jpg)
![git-mockup-13](https://user-images.githubusercontent.com/82379274/185419486-ddaa0634-8ab4-4783-864e-439fe03fb230.jpg)
![git-mockup-14](https://user-images.githubusercontent.com/82379274/185419488-4267092f-0e07-4ccb-97bd-f61edd5304e6.jpg)
![git-mockup-15](https://user-images.githubusercontent.com/82379274/185419492-db400d41-2175-472a-9d47-eba7c1ac260c.jpg)

**Comment by delchev** [comment]
Fixed with: 213e5d9ef7d760b142210239b8e7f7b2e121a6c2
