### ISSUE TITLE
[UI] Adopt fundamental styles - view Logs

### ISSUE THREAD

**Issue by dpanayotov** [eclipse/dirigible#1504]
Issue cloned from https://github.com/SAP/xsk/issues/1143

 ### Target
- [ ] Adopt the fundamental styles in Logs view

Use https://github.com/dirigiblelabs/ide-next as reference

**Comment by delchev** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/cd4bd0f3bc31071248e684b7e46877d0ef23a338
