### ISSUE TITLE
[Logging] can't log anything to the IDE console but severity ERROR in a JS service

### ISSUE THREAD

**Issue by shturec** [eclipse/dirigible#151]
my logback.xml is setup like this:
```
<logger name="apps" level="ALL" additivity="false">
    	<appender-ref ref="STDOUT" />
    	<appender-ref ref="FILE_APPS" />
    	<appender-ref ref="ConsoleLoggingAppender" />
</logger>
```
and somehow I can't seem to log anything but error level messages.  It is easy to reproduce.

This doesn't work:  
`var LOGGER = require("log/v3/logging").getLogger('http.filesvc').debug('test')`
The IDE console prints nothing.  

This works:  
`var LOGGER = require("log/v3/logging").getLogger('http.filesvc').error('test')`  
The IDE console prints 'test' with severity ERROR

**Comment by SvetlinZarev** [comment]
Does not seem to be a bug. In the logback.xml you configure the "apps" logger, but in the snippet you use the "http.filesvc" logger, which is transformed to "app.http.filesvc". I.e "apps" != "app". If you change "apps" to "app" in the config it should work.

**Comment by delchev** [comment]
changed in master
