### ISSUE TITLE
[UI] Adopt fundamental styles - view Workspace

### ISSUE THREAD

**Issue by dpanayotov** [eclipse/dirigible#1518]
Issue cloned from https://github.com/SAP/xsk/issues/1157

 ### Target
- [ ] Adopt the fundamental styles in Workspace view

The new view should use the following widgets:

- jstree
- jstree-fiori-theme
- fd-button
- fd-input
- fd-toolbar
- fd-popover
- dg-contextmenu

Dialogs should be called using the new messageHub API.

When selecting the search button, it should stay activated using the `is-selected` class and a secondary toolbar containing an input should be shown. Search functionality is provided by JSTree and should be performed right after the user stops typing. Selecting the search button a second time should hide the search toolbar.

When selecting "Create workspace", there should be a global dialog asking for a name. If no name is provided, then no workspace would be created.

When selecting "Delete workspace" there should be a global dialog asking the user to confirm.

When selecting "Import files from ZIP", there should be a global dialog window containing the "import" view, which based on the `data-parameters` attribute should change its text.

Design:

![workspace-1](https://user-images.githubusercontent.com/82379274/161984354-89a090c8-32bf-4baf-a0f8-57fb8a4b7a9e.jpg)

![workspace-2](https://user-images.githubusercontent.com/82379274/161984361-6b72fd14-e2ad-4b79-b4ff-eb340e9697d9.jpg)

![workspace-3](https://user-images.githubusercontent.com/82379274/161984367-4a51f25f-19b4-4439-95e3-353aee21bc3a.jpg)

![workspace-4](https://user-images.githubusercontent.com/82379274/161984372-d880eb3e-ae94-42cd-b3af-e84eb8a5d17a.jpg)

![workspace-5](https://user-images.githubusercontent.com/82379274/161984376-d208a7f3-1be1-47b9-8b74-83c3f28d316d.jpg)

![workspace-6](https://user-images.githubusercontent.com/82379274/161984379-2c77ae97-72a9-4d2b-a3fb-8f7356196d32.png)

![workspace-7](https://user-images.githubusercontent.com/82379274/161993836-cb25ba9b-b7ab-4751-a698-bac634da9d2b.jpg)

![workspace-8](https://user-images.githubusercontent.com/82379274/161993844-bac57646-c139-40b2-b14a-f8ddad8dd789.jpg)

![workspace-9](https://user-images.githubusercontent.com/82379274/161993849-62751574-5297-4e29-a7ca-d4280eaed5fe.jpg)

**Comment by StanZGenchev** [comment]
Done in the form of:
https://github.com/dirigiblelabs/ide-projects
