### ISSUE TITLE
[UI] Adopt fundamental styles - view Access

### ISSUE THREAD

**Issue by dpanayotov** [eclipse/dirigible#1522]
Issue cloned from https://github.com/SAP/xsk/issues/1126

 ### Target
- [ ] Adopt the fundamental styles in Access view

Use https://github.com/dirigiblelabs/ide-next as reference

**Comment by dpanayotov** [comment]
fixed

**Comment by delchev** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/f1a4a2ff8edacf516224e1762f9899b0d457c4f7
