### ISSUE TITLE
[workspace] "Open" action in the context menu

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#158]
Add an "Open" action in the context menu for the cases when the technology platform does not support double-click

**Comment by shturec** [comment]
It's a feature or enhancement request, not a bug. We never agreed on supporting anything, but desktop for IDE. I still don't but i find it more complete and usable to have a selectable action counterpart to implicit mouse click actions. So from UX it makes sense to me, as long as the context menu doesn't get freakingly bloated with actions. In this case we should look for a completely different approach IMO. For now there's no such danger.

Feature definition: #169 
Provided with [432601d6dc56a619fce1439c254513dce756565a](https://github.com/eclipse/dirigible/commit/432601d6dc56a619fce1439c254513dce756565a)
