### ISSUE TITLE
Hierarchical Configuration

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#161]
Improve the Configuration framework, which as of now supports:

- built-in *.properties
- environment variables
- application arguments

to support also Repository based:

- global *.properties
- user-defined *.properties

An API to be provided for programatic usage from scripting services afterwards.
An UI View for configuration and inspection to be provided afterwards.

**Comment by shturec** [comment]
+ workspace defined *.properties.

**Comment by delchev** [comment]
Duplicate of #555
