### ISSUE TITLE
[IDE] Import project view, does not limit by file type

### ISSUE THREAD

**Issue by StanZGenchev** [eclipse/dirigible#1676]
**Describe the bug**
In the Workbench perspective, in the import view, there is a button and a drag & drop area that allow you to upload files. Those files should be projects compressed in a zip file. However, you can select any file type and upload it.

**To Reproduce**
1. Go to 'Workbench'
2. Click on the 'Import' tab
3. Select any file that is not a zip
4. See issue

**Expected behavior**
When a user drags a file that is not a zip, there should be a message (or some kind of indication) telling the user that only zip files are allowed. In the file browser, only zip files should be shown.

**Desktop:**
 - OS: macOS 12.1, Fedora Linux 35
 - Browser: Firefox, Chrome, Safari, GNOME Web
 - Version: Dirigible 6.2.14

**Comment by dimitarquanterall** [comment]
Please, assign to me
