### ISSUE TITLE
[IDE] Importing files from ZIP does not work

### ISSUE THREAD

**Issue by StanZGenchev** [eclipse/dirigible#1678]
**Describe the bug**
In the Workbench perspective, when you select "Import files from ZIP", it uploads the zip but noting happens after that. In the developer console there is the following error:

```
POST 404 http://localhost:8081/services/v4/transport/zipimport/workspace/ide-documents/%2F
```

**To Reproduce**
1. Go to 'Workbench'
2. Right-click on a project and select 'Import files from zip'
3. Select any zip file
4. See issue

**Expected behavior**
When a user uploads a zip file, its contents should be extracted into the selected project.

**Desktop:**
 - OS: macOS 12.1, Fedora Linux 35
 - Browser: Firefox, Chrome, Safari, GNOME Web
 - Version: Dirigible 6.2.14

**Comment by dimitarquanterall** [comment]
Please, assign to me
