### ISSUE TITLE
[GitHub] Improve community profile

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#172]
Overview
-

Current [status](https://github.com/eclipse/dirigible/community)
Recommended community [standards](https://opensource.guide)
Kubernetes [example](https://github.com/kubernetes/kubernetes/community)

Action Items
-

- Add **Code of conduct**
  - Example can be found [here](https://github.com/kubernetes/kubernetes/blob/master/code-of-conduct.md)
  - Does Eclipse Foundation has _Code of conduct_? 
- Add **Issue template**
  - Example can be found [here](https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE.md)
- Add **Pull request template**
  - Example can be found [here](https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by delchev** [comment]
Added Pull Request Template:
https://github.com/eclipse/dirigible/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by delchev** [comment]
Issue Templates Added:
https://github.com/eclipse/dirigible/tree/master/.github/ISSUE_TEMPLATE
