### ISSUE TITLE
[Templates] In master-details, create detail function must be disabled if no master is selected

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#1727]
In master-details, create detail function must be disabled if no master is selected

**Comment by ThuF** [comment]
To be fixed with:
- https://github.com/eclipse/dirigible/issues/670

**Comment by ThuF** [comment]
Fixed with https://github.com/eclipse/dirigible/commit/52eb0191ef9765ded24e60912a7d96a6e8111ba1
