### ISSUE TITLE
[Test] Use h2 in AbstractDirigibleTest

### ISSUE THREAD

**Issue by Fluctuationqt** [eclipse/dirigible#1731]
Add `Configuration.set("DIRIGIBLE_DATABASE_H2_URL", "jdbc:h2:mem:xsk-tests");`
to the AbstractDirigibleTest class, so that it uses h2 instead of derby.

**Comment by SAtanasovv** [comment]
After discussing the issue with Nedelcho, it can be closed, because it is fixed with this pull request ->

> [Database] Remove Derby entirely and replace it with H2 #2016

**Comment by ThuF** [comment]
Closed with:
- #2016
