### ISSUE TITLE
xsjs source code is exposed with /services/v4/web/ url prefix

### ISSUE THREAD

**Issue by dpanayotov** [eclipse/dirigible#1741]
Issue cloned from https://github.com/SAP/xsk/issues/1592

**Describe the bug**

While developing proper procedure on deploying runtime xsk instance, I run into a bug of exposing xsjs source code if accessed with particular url prefix.

For example, http://localhost:8080/services/v4/xsk/hello-world.xsjs runs xsjs code, yet http://localhost:8080/services/v4/web/hello-world.xsjs just shows source code itself.

**To Reproduce**

1. Deploy xsk instance running on localhost:8080
2. Place code `hello-world.xsjs` to public repository
3. Access it with http://localhost:8080/services/v4/xsk/hello-world.xsjs and http://localhost:8080/services/v4/web/hello-world.xsjs
4. Proper output on first link and source code on second one
![Screenshot at 2022-05-10 18-30-06](https://user-images.githubusercontent.com/1090834/167666129-6e707bbe-e0f0-4608-9b95-3d034912a921.png)
![Screenshot at 2022-05-10 18-29-51](https://user-images.githubusercontent.com/1090834/167666130-63e54f5e-bea8-490a-bb36-fec91c6beab0.png)

**Expected behavior**
Code execution result on first link and error message on another one.

**Screenshots**
Screenshots attached.

**Comment by delchev** [comment]
Dependes on #1753
