### ISSUE TITLE
[IDE] Create combo service

### ISSUE THREAD

**Issue by himchev** [eclipse/dirigible#1742]
**Is your feature request related to a problem? Please describe.**
When creating views there is a long list of required JS and CSS files that have to be specified in each view. 

**Describe the solution you'd like**
We need to create a service that will accept a module/bundle key as a parameter and return the content of the files within the bundle

**Comment by delchev** [comment]
Usage:

    .../services/v4/js/ide-core/services/loader.js?id=ide-core-ui
