### ISSUE TITLE
[IDE] When multiple files with same name are opened in tabs, project name should be shown in the tab's title

### ISSUE THREAD

**Issue by dpanayotov** [eclipse/dirigible#1743]
Issue cloned from https://github.com/SAP/xsk/issues/1596

When two files with the same name are opened, the titles in the editor's tab bar only show their name and it's difficult to distinguish which file comes from what project/folder.
Show the path in the tab titles of files with the same name, when we have such files opened in the editor.

**Comment by StanZGenchev** [comment]
Fixed in new layout
