### ISSUE TITLE
[Documentation] Fix broken links in the Samples page

### ISSUE THREAD

**Issue by slavipande** [eclipse/dirigible#1819]
Some of the hyperlinks on [dirigible.io/samples](https://www.dirigible.io/samples/) are broken and have to be fixed. @ThuF  will take care of the links under section Tutorials. The others need to be fixed by a UA colleague.

**Comment by ThuF** [comment]
Tutorials redirect links fixed with:
- https://github.com/dirigible-io/dirigible-io.github.io/commit/39f7f33516787ee8318c593e28058c04a8a38b8b

**Comment by slavipande** [comment]
Partial update: https://github.com/dirigible-io/dirigible-io.github.io/commit/48987cc4ab7ff2fa999b3efa06fdd34201c15d9c

More work left to do in this issue. Updates to follow here.

Best regards,
Svetoslav

**Comment by slavipande** [comment]
The rest of the links updated with https://github.com/dirigible-io/dirigible-io.github.io/commit/2086ec41a872fa5bc6e289aa3f8e4ceb33fb9619

Hence, I'm closing this issue.

Best regards,
Svetoslav

**Comment by ThuF** [comment]
@slavipande Thank you Svetoslav for the fixes!
