### ISSUE TITLE
[UI] Imported projects, folders and files should be automatically published.

### ISSUE THREAD

**Issue by StanZGenchev** [eclipse/dirigible#1845]
**Describe the issue**
Currently, if you import a file, folder or a project from zip, it will not be published. The user has to manually publish the file. This can be rather annoying especially if the imported files are images that cannot be edited in Dirigible.

**Expected behavior**
Imported files should be published.

**Desktop:**
 - OS: macOS 12.4
 - Browser: Firefox 101
 - Version: Dirigible 6.3.0

**Comment by ThuF** [comment]
Fixed with:
- 1899
