### ISSUE TITLE
[IDE] Creating a new file or folder should focus it

### ISSUE THREAD

**Issue by dimitarquanterall** [eclipse/dirigible#1855]
**Is your feature request related to a problem? Please describe.**
In Workbench perspective when New > File | Folder is selected it places the new node on its correct place in the tree but doesn't set focus on it. If there is a huge and spread files and folders tree it may be difficult to quickly find the new item in order to set its name. Another disadvantage is that the new file | folder must be explicitly selected and right clicked in order to be renamed.  

**Describe the solution you'd like**
When a new file or folder is created it must be immediately focused and switched to rename mode (user is able to type preferred name).

**Describe alternatives you've considered**
If it is hard to produce the desired functionality a color marker displaying which exactly is the new file | folder can be also a good idea.

**Comment by ThuF** [comment]
It's also important to fix this issue and to be able to set the name of the file/folder in advance, as once created and `renamed`, then `Unpublish` and `Publish` requests are send to the backend. To check that behaviour:
1. Create new project.
2. Create new file _(e.g. `JavaScript CJS Service`)_.
3. Rename the file _(e.g. `hello-world.js`)_
4. The file is `Published` and can be accessed/executed in the `Preview` view.

> _**Note:** In some cases this behaviour could lead to severe issue, like when creating `*.table`, `*.bpm`, `*.job` etc. files._

It should be possible to set the filename _(e.g. `hello-world.js`)_ in advance, before publishing the file.
