### ISSUE TITLE
Project view does not refresh upon import 

### ISSUE THREAD

**Issue by dimitarquanterall** [eclipse/dirigible#1873]
**Describe the bug**
After importing a project it doesn't show in Projects view until the Workbench perspective is being reloaded. 

**To Reproduce**
1. Open the Workbench perspective. 
2. Expand Import. 
3. Upload zipped project. 
4. The imported project is not visible in projects tree.
5. Refresh. Upon refresh project's files and folders are already available in the tree. 

**Expected behaviour**
Project is visible in the tree on the fly, right after upload is complete. 

**Dirigible deploy**
Version: 7.0.0-SNAPSHOT
Commit Id: [d7c6260e84c6af12580a3aa03d7d357a0906bcd7](https://github.com/eclipse/dirigible/commit/d7c6260e84c6af12580a3aa03d7d357a0906bcd7)

**Comment by StanZGenchev** [comment]
Cannot replicate

**Comment by StanZGenchev** [comment]
Still cannot replicate.

**Comment by dimitarquanterall** [comment]
Seems to be quite a specific error or browser cache strange behaviour. In order to replicate:
1. Import/create a project. 
2. Open at least one file in editor mode.
3. Stop Tomcat and delete everything form its target/ and webapps/ folders. 
4. Copy respective ROOT.war and run Tomcat again.
5. If using Chrome, do "Empty cache and hard reload". 
6. The Projects tab is now empty but XSK tries the open the already non-existing file which have been opened in Step 2. As a result the editor displays infinite "Loading data..." message. The following is logged to browser's console:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'modified')
    at editor.js:628:44
(anonymous) @ editor.js:628
Promise.then (async)
(anonymous) @ editor.js:630
Promise.then (async)
(anonymous) @ editor.js:613
s._invokeFactory @ loader.js:1189
s.complete @ loader.js:1199
s._onModuleComplete @ loader.js:1825
s._onModuleComplete @ loader.js:1837
s._onModuleComplete @ loader.js:1837
s._resolve @ loader.js:1785
s.defineModule @ loader.js:1428
s._onLoad @ loader.js:1508
(anonymous) @ loader.js:1689
e.triggerCallback @ loader.js:632
(anonymous) @ loader.js:626
u @ loader.js:658
load (async)
e.attachListeners @ loader.js:664
e.load @ loader.js:687
e.load @ loader.js:626
c @ loader.js:1684
s._loadModule @ loader.js:1696
s._resolve @ loader.js:1781
s.defineModule @ loader.js:1428
s._onLoad @ loader.js:1508
(anonymous) @ loader.js:1689
e.triggerCallback @ loader.js:632
(anonymous) @ loader.js:626
u @ loader.js:658
load (async)
e.attachListeners @ loader.js:664
e.load @ loader.js:687
e.load @ loader.js:626
c @ loader.js:1684
s._loadModule @ loader.js:1696
s._resolve @ loader.js:1781
s.defineModule @ loader.js:1428
n @ loader.js:1900
init @ editor.js:600
(anonymous) @ editor.js:924
loader.js?id=ide-view-js:117 `
`GET http://localhost:8080/services/v4/ide/workspaces/workspace 404`
`(anonymous) @ loader.js?id=ide-view-js:117
s @ loader.js?id=ide-view-js:112
(anonymous) @ loader.js?id=ide-view-js:110
(anonymous) @ loader.js?id=ide-view-js:144
$digest @ loader.js?id=ide-view-js:156
$apply @ loader.js?id=ide-view-js:159
(anonymous) @ loader.js?id=ide-view-js:25
invoke @ loader.js?id=ide-view-js:48
c @ loader.js?id=ide-view-js:25
Wc @ loader.js?id=ide-view-js:25
Ee @ loader.js?id=ide-view-js:24
(anonymous) @ loader.js?id=ide-view-js:354
e @ loader.js?id=ide-view-js:2
t @ loader.js?id=ide-view-js:2
setTimeout (async)
(anonymous) @ loader.js?id=ide-view-js:2
c @ loader.js?id=ide-view-js:2
fireWith @ loader.js?id=ide-view-js:2
fire @ loader.js?id=ide-view-js:2
c @ loader.js?id=ide-view-js:2
fireWith @ loader.js?id=ide-view-js:2
ready @ loader.js?id=ide-view-js:2
B @ loader.js?id=ide-view-js:2
workspace.js:34 Workspace service: Error: [$http:baddata] http://errors.angularjs.org/1.8.2/$http/baddata?p0=Workspace%20workspace%20does%20not%20exist.&p1=%7B%7D
    at loader.js?id=ide-view-js:10:168
    at wc (loader.js?id=ide-view-js:104:482)
    at loader.js?id=ide-view-js:105:399
    at r (loader.js?id=ide-view-js:11:76)
    at Bd (loader.js?id=ide-view-js:105:381)
    at f (loader.js?id=ide-view-js:107:472)
    at loader.js?id=ide-view-js:144:454
    at m.$digest (loader.js?id=ide-view-js:156:67)
    at m.$apply (loader.js?id=ide-view-js:159:484)
    at k (loader.js?id=ide-view-js:110:445)`
7. Perform import steps described in the issue. 
8. Files tree doesn't refresh, as well as the following is logged in console:
`loader.js?id=ide-view-js:132 TypeError: $scope.jstreeWidget.jstree(...).refresh is not a function
    at projects.js:599:59
    at loader.js?id=ide-view-js:144:454
    at m.$digest (loader.js?id=ide-view-js:156:67)
    at m.$apply (loader.js?id=ide-view-js:159:484)
    at k (loader.js?id=ide-view-js:110:445)
    at v (loader.js?id=ide-view-js:116:40)
    at y.onload (loader.js?id=ide-view-js:116:464) 'Possibly unhandled rejection: {}'`
