### ISSUE TITLE
Errorneous usage of HttpServletResponse in the rest endpoints

### ISSUE THREAD

**Issue by SvetlinZarev** [eclipse/dirigible#188]
The various rest services follow the pattern:

```
if (some_condition) {
    sendErrorXXX(response, message); //send the error response
    return Response.status(Status.ERROR_STATUS).build(); //sending the error response again
}
```

The various "sendErrorXXXX" methods in AbstractRestService are unnecessary and duplicate the behavior of the returned Response object. Even more - it's an error to use both. The proper way to send any kind of response in JAX-RS is to use the ResposneBuilder. JAX-RS endpoints should avoid touching the HttpServletResponse directly.

**Comment by g051051** [comment]
Would fixing this (by redoing the methods in the AbstractRestService class) cause a breaking change?  Is this something that's exposed to/used by end users to create custom services?

**Comment by ThuF** [comment]
Hi @g051051, no this functionality is not exposed to end users, so no breaking changes would occur. The `AbstractRestService` class is used in many (maybe all?) Dirigible's REST API Services (e.g. `DatabaseRestService`, `GitRestService`, `OAuthService`, etc.). After quick go-through the code I found that this pattern is used heavily in the extending classes:
```java
sendErrorXXX(response, message); //send the error response
return Response.status(Status.ERROR_STATUS).build();
```

As the `AbstractRestService` class has only these `sendErrorXXX()` methods and `getLogger()` (which is also abstract), it could be more reasonable to delete the whole class, move the `getLogger` method to the `IRestService` interface and replace the `sendErrorXXX()` calls with `Response.status(Status.ERROR_STATUS)` (which by the way in many cases is already in place).

**Comment by g051051** [comment]
I actually took the opposite tack, and changed the implementation of the methods to all be in the form of:

`	/**
	 * Create error response not found.
	 *
	 * @param message
	 *            the message
	 * @return the error response
	 */
	protected Response createErrorResponseNotFound(String message) {
		return Response.serverError().status(Status.NOT_FOUND).entity(message).build();
	}
`

then updated all the references to just do something like:

`		return createErrorResponseNotFound(path);
`

**Comment by ThuF** [comment]
This approach is also good 😄, so that we don't need to delete the `AbstractRestService` class. As this is change in the very core of dirigible, would you mind, before creating a PR, to do some exploratory testing:
- build and deploy Dirigible locally
- go through the samples and just try out some of them
- try to access resource that's not published (to go through the 404 code) e.g. http://localhost:8080/services/v4/web/not-existing-project/not-existing-page/

**Comment by g051051** [comment]
1. Local build was successful.  Deployment of dirigible-desktop-all to local Apache Tomcat successful.
2. I tested the following samples:
- Hello World: produced "Hello World" output.
- Bookstore Application: worked as expected.
- HTML5 (AngularJS): worked as expected.
- Message Listener: The IDE shows an error the "exports is not defined" for the handler.js file, but the output is logged as expected.  I think this is an existing error in the sample.
- Websocket Service: Same "exports is not defined" error in the IDE, but the output is logged as expected.
3. http://localhost:8080/services/v4/web/not-existing-project/not-existing-page/ produces and error page with: "Resource not found: not-existing-project/not-existing-page/index.html".

**Comment by ThuF** [comment]
Thanks, that's perfect! Now we can continue to the pull request 💯

**Comment by ThuF** [comment]
Fixed with: https://github.com/eclipse/dirigible/pull/657
