### ISSUE TITLE
[IDE] Git - No error messages for unsuccessful cloning of projects

### ISSUE THREAD

**Issue by kpetelova** [eclipse/dirigible#1885]
**Description**
In Git perspective, after filling the form for cloning with wrong (or even random) credentials, it creates a repository and no error or warning messages are displayed. Therefore, one does not know whether they have successfully cloned a repository until the projects in the Workbench perspective fail to synchronize.

**To Reproduce**
1. Go to Git perspective
2. Click on 'Clone Project' symbol
3. Paste correct URL of desired repository
4. Fill username and password fields with wrong or random credentials
5. No error messages or warnings appear
6. Name of the repository appears in the list
7. Go to Workbench
8. No Projects appear
9. Error messages indicating failure to synchronize appear

**Expected behavior**
After filling the form with wrong credentials an error should appear and the repository should not be created.

**Screenshots**
![image](https://user-images.githubusercontent.com/96417658/174592069-2de09915-658c-4d81-b81c-2985d71003ac.png)
![image](https://user-images.githubusercontent.com/96417658/174592100-da33ac65-a85d-42b6-8483-7d8b205de762.png)
![image](https://user-images.githubusercontent.com/96417658/174592131-5e5ab086-930a-40ab-ada6-68058bd54ea0.png)

**Desktop:**
 - OS: Windows
 - Browser: Mozilla

**Comment by ThuF** [comment]
Related fix:
- https://github.com/eclipse/dirigible/commit/c2ffdaddf7f0d999ce57ac6661ba9522fb944158

**Comment by ThuF** [comment]
Fixed with:
- https://github.com/eclipse/dirigible/commit/c2ffdaddf7f0d999ce57ac6661ba9522fb944158
- https://github.com/eclipse/dirigible/commit/4ebc91f288925e81c9f718b3a2d49ecf89fbe7cc
- https://github.com/eclipse/dirigible/commit/135fa83baf98ded1446535f89ffac4fe4d4ba1fc
- https://github.com/eclipse/dirigible/commit/1e2c7b50ad51a63088cffdd7f6a318aacaa55041
