### ISSUE TITLE
Console.log doesn't print

### ISSUE THREAD

**Issue by danvelkov** [eclipse/dirigible#1943]
**Describe the bug**
Console.log command doesn't show content on the console neither an error is printed on the tomcat console on the latest dirigible version.

**Desktop (please complete the following information):**
OS: Windows 10
Browser Chrome
Version 103.0.5060.114

**Comment by delchev** [comment]
Should be fixed with: https://github.com/eclipse/dirigible/commit/dc3f2830e1b2834491baace47a9e34cf561217c6
