### ISSUE TITLE
[Git] Renaming project issues

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#195]
Renaming project leads to several issues:
1. The git folder (located /root/git/dirigible/workspace/{project-name}/git.property) is not renamed also, so the Push/Pull commands are not working. The workaround is easy - rename the folder manually.
2. After push, the old folder structure is not deleted (e.g. openstack_api -> openstack leads to having both openstack_api and openstack.

**Comment by delchev** [comment]
In 4.5 there is a new architecture related to Git support
