### ISSUE TITLE
[API] Expand git branch API

### ISSUE THREAD

**Issue by StanZGenchev** [eclipse/dirigible#1998]
**Describe the issue**
The current git REST API doesn't have the endpoints for creating and deleting branches, both remote and local. There is a `createBranch` function in `GitFacade.java` but it's not used anywhere in the service.

We must create 3 new API endpoints in `GitRestService.java`:

1. Create local branch
2. Delete local branch
3. Delete remote branch (will require username, email and password)

**Comment by delchev** [comment]
POST:	/{project}/branches/local/{branch}
    DELETE:	/{project}/branches/local/{branch}
    POST:	/{project}/branches/remote/{branch} + {username: 'xxx', password: 'yyy'}
    DELETE:	/{project}/branches/remote/{branch} + {username: 'xxx', password: 'yyy'}
