### ISSUE TITLE
[API] Database - Support for Array Parameter

### ISSUE THREAD

**Issue by BorisNen** [eclipse/dirigible#2018]
## Problem
Trying to write an SQL with the **IN** operator inside an application developed with Eclipse Dirigible. Example:

```javascript
var query = require("db/v4/query");

exports.filterValues = function (paramsArray) {
	return query.execute("SELECT * FROM EXAMPLE_TABLE WHERE NAME IN (?)", paramsArray);
}
```
This produces an `IllegalArgumentException` that states - `Parameters must contain primitives and objects only`.

## Proposed Solution

The [DatabaseFacade](https://github.com/eclipse/dirigible/blob/master/api/api-facade/api-database/src/main/java/org/eclipse/dirigible/api/v3/db/DatabaseFacade.java) uses `isJsonObject()` and `isJsonPrimitive()` from gson. Add a third check of `isJsonArray()`:

```java
if (parameterElement.isJsonArray()) {
  JsonArray params = parameterElement.getAsJsonArray();
  ArrayList<String> list = new ArrayList<String>();
  for (int n=0; i < list.size(); i++){
	  list.add(params.get(n).toString());
  }
  preparedStatement.setArray(i, preparedStatement.getConnection().createArrayOf("VARCHAR", list.toArray()));
}
```

The setArray method for prepared statements requires `java.sql.Array`. This can be done using the `getConnection().createArrayOf()` method from the prepared statement. This means that the JsonArray from gson should first be read and converted to an `Array`.

## Problems with the Solution

The exact type of the elements in the Array must be passed inside the createArrayOf. This means that we should know the column type of the table itself. Also it seems that this method is not quite supported across JDBC drivers _(e.g. `H2` vs `PostgreSQL`)_.

**Comment by BorisNen** [comment]
**Workaround:**

Create the IN query inside your dirigible application. Note that your parametersArray value should have the following structure:
```
[1, 2, 3] for Integers or ["One", "Two", "Three"] for Strings
```

```
var query = require("db/v4/query");

exports.filterValues = function (parametersArray) {
	// Have your SQL statement prepared
	var sql = "SELECT * FROM EXAMPLE_TABLE WHERE NAME IN (";

	// Create the "?" placeholder for each value from the array
	parametersArray.forEach(element => {
		sql += "?,";
	})

	// Remove the last ,
	sql.slice(0, -1)
	// Close the values bracket
	sql += ')';

	// Pass the SQL statement and parameter array to the DatabaseFacade
	return query.execute(sql, parametersArray);
}
```

**Comment by ThuF** [comment]
Won't fix as it seems the support for array parameters across different JDBC drivers is not good enough.

Workaround solution proposed in the comment above.
