### ISSUE TITLE
JS with a comment at the last line can not be `require`d

### ISSUE THREAD

**Issue by vmutafov** [eclipse/dirigible#2127]
If we have a JS like the one below, it cannot be evaluated:
```JS
exports.test = () => {}
// some comment
```

**Comment by ThuF** [comment]
As with the adoption of ES6 and the upcoming deprecation of the `require()` support, it seems that this issue is no longer in our priority list. So I'm closing it as `Won't Fix`.

**Comment by vmutafov** [comment]
@ThuF this is actually fixed, we have forgotten to close the issue with this PR: https://github.com/eclipse/dirigible/pull/2126
