### ISSUE TITLE
[API] Pdf generation API gives an error when the 'rows' array is empty

### ISSUE THREAD

**Issue by himchev** [eclipse/dirigible#2179]
This is the error message:
> (Location of error unknown)org.apache.fop.fo.ValidationException: "fo:table-body" is missing child elements. Required content model: marker* (table-row+|table-cell+) (No context info available)

- https://www.dirigible.io/api/documents/pdf/

**Comment by ThuF** [comment]
@himchev to hot fix your instance, you can clone in Eclipse Dirigible's Git perspective the **api-documents** project:
- https://github.com/dirigiblelabs/api-documents
