### ISSUE TITLE
[Security] OAuth - Expired Token Issue

### ISSUE THREAD

**Issue by raagulto** [eclipse/dirigible#2197]
Hello,

Dirigible IDE was working fine then suddenly we are not able to access the UI anymore.

We found this error in the logs of the SAP BTP Cockpit.
```
2022-11-03 11:43:44.054 [ERROR] [http-nio-8080-exec-9] o.e.dirigible.oauth.utils.JwtUtils - The Token has expired on 2022-11-02T18:50:04Z. com.auth0.jwt.exceptions.TokenExpiredException: The Token has expired on 2022-11-02T18:50:04Z.
```

Is there any way to check how to re-generate or where to get the token?

Thanks!

Tried @ThuF 's suggestion:
> _Please try to refresh the browser or to open the Eclipse Dirigible IDE in an incognito window.
This should be enough to request new OAuth access token._

Still didn't work on my end.

**Comment by ThuF** [comment]
Could be related to:
- https://github.com/eclipse/dirigible/issues/2184

**Comment by ThuF** [comment]
Reopening the issue, as there is still issues with the SAP BTP Cloud Foundry deployment.

**Comment by ThuF** [comment]
Fixed, no more pending issues.
