### ISSUE TITLE
Batch insert trough DAO.insert

### ISSUE THREAD

**Issue by danvelkov** [eclipse/dirigible#2203]
**Is your feature request related to a problem? Please describe.**
When we have a lot of entities for insertion to the database, it takes up a lot of time to upload them all.

**Describe the solution you'd like**
A solution would be a batch insert logic for the insert method, where we pass an array of entities to be inserted. This would save a lot of time and resources and will make the end-user experience better.

**Comment by delchev** [comment]
done
