### ISSUE TITLE
[IDE] Acknowledge upper/lower case symbols for files

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#229]
- Create file ```test.js```
- Try to create new file with name ```Test.js``` -> results into ```file```
- Try to rename ```file``` to ```Test.js``` -> the file is not renamed at all

**Comment by delchev** [comment]
not reproducible anymore

**Comment by delchev** [comment]
it leads to more problems, depending on the underlying storage - e.g. Windows file system is case insensitive anyway

**Comment by delchev** [comment]
won't fix
