### ISSUE TITLE
Repository API v4

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#231]
Repository API v4 implementation based on the new [guidelines](https://github.com/eclipse/dirigible/wiki/api-v4-guidelines).

Module Identifier: **repository/v4/manager**
Module Source: https://github.com/dirigiblelabs/api-repository/blob/master/repository/v4/manager.js
Facade Source: https://github.com/eclipse/dirigible/blob/master/api/api-facade/api-repository/src/main/java/org/eclipse/dirigible/api/v3/repository/RepositoryFacade.java
Documentation: https://www.dirigible.io/api/repository_manager.html
Samples: ~~~http://www.dirigible.io/samples/simple_repository_manager.html~~~
Tests: ~~~https://github.com/eclipse/dirigible/tree/master/api/api-facade/api-tests/src/main/resources/repository/v4/manager~~~

**Comment by ThuF** [comment]
Fixed
