### ISSUE TITLE
Generator API v3

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#232]
Generator API v3 implementation based on the new [guidelines](https://github.com/eclipse/dirigible/wiki/api-v3-guidelines).

Module Identifier: **platform/v3/generator**
Module Source: https://github.com/dirigiblelabs/api-v3-platform/blob/master/platform/v3/generator.js
Module Mirror: https://github.com/eclipse/dirigible/blob/master/api/api-javascript/api-platform/src/main/resources/platform/v3/generator.js
Facade Source: https://github.com/eclipse/dirigible/blob/master/api/api-facades/api-platform/src/main/java/org/eclipse/dirigible/api/v3/platform/GeneratorFacade.java
Documentation: http://www.dirigible.io/api/generator.html
Samples: ~~~http://www.dirigible.io/samples/generator_basic.html~~~
Tests: ~~~https://github.com/eclipse/dirigible/tree/master/api/api-facades/api-tests/src/main/resources/platform/v3/generator~~~

**Comment by ThuF** [comment]
To be implemented with https://github.com/eclipse/dirigible/issues/507
