### ISSUE TITLE
Lifecycle API v4

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#233]
Lifecycle API v4 implementation based on the new [guidelines](https://github.com/eclipse/dirigible/wiki/api-v4-guidelines).

Module Identifier: **platform/v4/lifecycle**
Module Source: https://github.com/dirigiblelabs/api-platform/blob/master/platform/v4/lifecycle.js
Module Mirror: https://github.com/eclipse/dirigible/blob/master/api/api-javascript/api-platform/src/main/resources/platform/v4/lifecycle.js
Facade Source: https://github.com/eclipse/dirigible/blob/master/api/api-facade/api-platform/src/main/java/org/eclipse/dirigible/api/v3/platform/LifecycleFacade.java
Documentation: http://www.dirigible.io/api/platform_lifecycle.html
Samples: ~~~http://www.dirigible.io/samples/simple_platform_lifecycle.html~~~
Tests: ~~~https://github.com/eclipse/dirigible/tree/master/api/api-facade/api-tests/src/main/resources/platform/v4/lifecycle~~~

**Comment by ThuF** [comment]
Fixed
