### ISSUE TITLE
[API] Importing files doesn't work

### ISSUE THREAD

**Issue by StanZGenchev** [eclipse/dirigible#2426]
**Describe the bug**
Importing files or files from zip doesn't work. After the file gets "uploaded", the UI refreshes but the files are not there. In the console, there is an empty error response.

**To Reproduce**
1. Go to 'Workbench'
2. Try to upload a file to a project
3. See issue

**Desktop:**
 - OS: Fedora Linux 36
 - Browser: Firefox 110
 - Version: Dirigible 7.1.6

**Comment by delchev** [comment]
Cannot reproduce. Let's meet and go through the issue?
