### ISSUE TITLE
[API] To be migrated modules

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#2465]
To be migrated:

- [ ] io/image
- [ ] platform/problems
- [ ] utils/jsonpath.js
- [ ] core/destinations
- [x] etcd/client
- [x] kafka/consumer
- [x] kafka/producer
- [ ] qldb/
- [x] rabbitmq/
- [x] redis/
- [ ] spark/

**Comment by nedelcho-delchev-tues** [comment]
In progress

**Comment by nedelcho-delchev-tues** [comment]
We can leave spark for now, if so, this can be considered done.

**Comment by ThuF** [comment]
@nedelcho-delchev-tues, @delchev should we close the issue as Done? It seems that only the Spark API wasn’t migrated yet.
