### ISSUE TITLE
Role based access management support for CMIS API

### ISSUE THREAD

**Issue by stevegroom** [eclipse/dirigible#249]
We are using the latest Dirigible release for serving image assets as part of SAP Cloud Platform based solutions – thank you for this CMIS integrated build. 
 
As we create more apps, we are seeing too much demand for Dirigible in terms of Java server nodes. To reduce that demand, I would like to see role based access to different areas of the CMIS repo allowing one Dirigible instance to serve several projects. This will remove the need to provision multiple Java VMs.

**Comment by delchev** [comment]
Thanks Steve!
The initial implementation starts with https://github.com/eclipse/dirigible/commit/53574651a2fcef0a9aeb821c5b6f0b5499e8c97b

**Comment by delchev** [comment]
tested locally
