### ISSUE TITLE
[Entity Data Model] Add Number Widget Type

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#268]
The current widget types are:
- Text Box
- Text Area
- Date Picker
- Drop Down
- Lookup Dialog

We also need a Number widget type to complete the basic set of widgets.

**Comment by ThuF** [comment]
Here is also a list of the standard HTML input types: https://www.w3schools.com/html/html_form_input_types.asp

**Comment by delchev** [comment]
Fixed with:
https://github.com/eclipse/dirigible/commit/ca4ec21884ac628bb68d1090ae7b603849c01ffd
