### ISSUE TITLE
Homepage: 404 at Slides of Stan's talk

### ISSUE THREAD

**Issue by koppor** [eclipse/dirigible#2902]
1. Open https://www.dirigible.io/news/2022/09/29/news-fundamentals-conf-2022/
2. Scroll down to "Slides"
3. Click
4. Link <https://fundamentalconf.com/Stan-Fundamentally%20Changing%20Enterprise%20Web%20IDEs.pdf> is 404.

Please adjust the link to show the slides.

---

![image](https://github.com/eclipse/dirigible/assets/1366654/c70bb53a-e20f-4f72-8f77-3c26c7ef98c6)

**Comment by ThuF** [comment]
Fixed with:
- https://github.com/dirigible-io/dirigible-io.github.io/commit/191a3ac4f6521a0b70b01f9980207a97fd03b635

**Comment by ThuF** [comment]
Hi @koppor,

The slides are now available at: https://www.dirigible.io/news/2022/09/29/Fundamentally-Changing-Enterprise-Web-IDEs.pdf

You can also join our Slack Workspace at: http://slack.dirigible.io
