### ISSUE TITLE
Links in the documentation are broken

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#2941]
**Describe the bug**
A lot of the links in the documentation have invalid links

For example if you go [here](https://www.dirigible.io/help/development/artifacts/) and open `*table`, `*view` you will receive 404.

![image](https://github.com/eclipse/dirigible/assets/5058839/7a2cc6cb-c15a-4b1f-834b-8987d00e059c)
![image](https://github.com/eclipse/dirigible/assets/5058839/23724044-11ff-4862-bcff-707079914b72)

**Comment by ThuF** [comment]
Fixed with:
- https://github.com/dirigible-io/dirigible-io.github.io/commit/aa2a677d5ba00538b6ec160e645e61e99c258b45
