### ISSUE TITLE
[Core] TypeScript Services are not Published

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#2997]
## Description

It seems that the `Publish` action doesn't have effect on the `*.ts` services.

For example if several TypeScript files are generate (e.g. via template), and the the `Publish` action is performed (either on project level, or at folder level), then the compilation of `*.ts` to `*.mjs` is not triggered.

However if you manually go into each of the files and perform the `Save` action (e.g. by pressing `Ctrl+S/Cmd+S`), then the TypeScript files are complied.

## Expected Behaviour

The TypeScript files should be compiled by the `Publish` action. Also Dirigible projects (e.g. custom app) packaged in either Docker image or `*.jar` files and containing TypeScript service should be also compiled once the Dirigible instance is started.

**Comment by delchev** [comment]
@ThuF about `Publish` and `once the Dirigible instance is started`, my assumption is that `ts` files are only relevant at development phase and the only ones used at runtime are the compiled `mjs` files. This means if you have generated `ts` files (from a model) at the end of the generation should be triggered the `ts` compilation as well. In general, the point is that in the registry you use only the already compiled `mjs` files, but this does not mean automatically that the compilation should happen on Publish. There is also a `build` action at `Project` level which does exactly this, isn't it?

**Comment by ThuF** [comment]
Publishing behaviour of `*.ts` files is addressed with the following commits:
- https://github.com/eclipse/dirigible/pull/2990/commits/b443a543a7dde02fe2ce561eff5d5757e1cb2995
- https://github.com/eclipse/dirigible/pull/2990/commits/26bcc7905e255b059fe8b3f528709986b1b63aad
- as part of  https://github.com/eclipse/dirigible/pull/2990

**Changes:**
- No default compilation _(e.g. `onSave`)_ for TypeScript files.
- `tsconfig.json` file is required for projects with `*.ts` files.
- TypeScript files are compiled with `tsc` instead of `esbuild`.
- The `tsc` command needs to be added to the **actions** in the `project.json`.
- `registry` property introduced in the `project.json`.

Example:

**tsconfig.json**
```json
{
    "compilerOptions": {
        "module": "ESNext"
    }
}
```

**project.json**
```json
{
    "guid": "test",
    "actions": [
        {
            "name": "Build TypeScript",
            "commands": [
                {
                    "os": "unix",
                    "command": "tsc"
                },
                {
                    "os": "windows",
                    "command": "tsc"
                }
            ],
            "registry": "true"
        }
    ]
}
```
