### ISSUE TITLE
Colaborative editing feature

### ISSUE THREAD

**Issue by km2k** [eclipse/dirigible#301]
When two or more developers work on the same file at the same time, it could be helpful to have colaborative editing.

The feature could easily be implemented using AMQP messaging on every keystroke. Conflict resolution could follow "last-write-wins" strategy without further complications.

Vizualization can be in google-docs like style, where every developer's input is shown with a cursor in different color.

It can be quite useful in peer programing, code reviewing, etc.

**Comment by delchev** [comment]
won't fix
