### ISSUE TITLE
[FullStack App] Triggers via Messaging

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#308]
Implement a built-in functionality to send messages to predefined topics on the Entity's lifecycle events - onCreate, onUpdate, onDelete, onGet

**Comment by ThuF** [comment]
Fixed in https://github.com/eclipse/dirigible/issues/403

**Note:**
- This is an initial version and the interface may change in future versions
- The triggering functionality is part of the DAO modules
- The events are submitted in a Queue
