### ISSUE TITLE
[API] TypeScript transformation 

### ISSUE THREAD

**Issue by Mrgoblings** [eclipse/dirigible#3102]
**Is your feature request related to a problem? Please describe.**
The TypeScript APIs within Eclipse Dirigible currently lack proper typing for their methods, resulting in challenges for developers working with the APIs and impeding the overall development experience.

**Describe the solution you'd like**
I propose introducing or enhancing type definitions for the TypeScript APIs' methods. This improvement would provide developers with clear and concise information about the expected parameters and return types, enhancing code clarity and developer support.

**Describe alternatives you've considered**
One alternative is to manually document the types in comments or external documentation. However, this may not be as effective or reliable as having the types directly incorporated into the codebase.

**Contribution PRs:**
- [x] https://github.com/eclipse/dirigible/pull/3181
- [x] https://github.com/eclipse/dirigible/pull/3131
- [x] https://github.com/eclipse/dirigible/pull/3242
- [x] https://github.com/eclipse/dirigible/pull/3243
- [x] https://github.com/eclipse/dirigible/pull/3244
- [x] https://github.com/eclipse/dirigible/pull/3246
- [x] https://github.com/eclipse/dirigible/pull/3248
- [x] https://github.com/eclipse/dirigible/pull/3249
- [x] https://github.com/eclipse/dirigible/pull/3251
- [x] https://github.com/eclipse/dirigible/pull/3252
- [x] https://github.com/eclipse/dirigible/pull/3210
- [x] https://github.com/eclipse/dirigible/pull/3221
- [x] https://github.com/eclipse/dirigible/pull/3182
- [x] https://github.com/eclipse/dirigible/pull/3230
- [x] https://github.com/eclipse/dirigible/pull/3296
- [x] https://github.com/eclipse/dirigible/pull/3211 - **not fully type safe - types were introduced to key places only**
- [x] https://github.com/eclipse/dirigible/pull/3385
- [x] https://github.com/eclipse/dirigible/pull/3513  - **not fully type safe - types were introduced to key places only**
- [x] https://github.com/eclipse/dirigible/pull/3516
- [x] https://github.com/eclipse/dirigible/pull/3250
- [x] https://github.com/eclipse/dirigible/pull/3247
- [x] https://github.com/eclipse/dirigible/pull/3245
- [x] https://github.com/eclipse/dirigible/pull/3392
- [x] https://github.com/eclipse/dirigible/pull/3409
- [x] https://github.com/eclipse/dirigible/pull/3410
- [x] https://github.com/eclipse/dirigible/pull/3435
- [x] https://github.com/eclipse/dirigible/pull/3437
- [x] https://github.com/eclipse/dirigible/pull/3439
- [x] https://github.com/eclipse/dirigible/pull/3444
- [x] https://github.com/eclipse/dirigible/pull/3451
- [x] https://github.com/eclipse/dirigible/pull/3472
- [x] https://github.com/eclipse/dirigible/pull/3473
- [x] https://github.com/eclipse/dirigible/pull/3474
- [x] https://github.com/eclipse/dirigible/pull/3483
- [x] https://github.com/eclipse/dirigible/pull/3484
- [x] https://github.com/eclipse/dirigible/pull/3491
- [x] https://github.com/eclipse/dirigible/pull/3500

**Merge PRs:**
- [x] https://github.com/eclipse/dirigible/pull/3241
- [x] https://github.com/eclipse/dirigible/pull/3276
- [x] https://github.com/eclipse/dirigible/pull/3291
- [x] https://github.com/eclipse/dirigible/pull/4235
- [x] https://github.com/eclipse/dirigible/pull/4249
- [ ] https://github.com/eclipse/dirigible/pull/4254

**Comment by TIVMOF** [comment]
In the Net API there are some wrappers that may need to be migrated to TS in the future.
