### ISSUE TITLE
[IDE] Replace the old form editor with a new one

### ISSUE THREAD

**Issue by StanZGenchev** [eclipse/dirigible#3171]
**Describe the issue**
The current form file editor is broken and it uses the old UI which is going to get removed very soon.
We need a new form file editor that makes use of the new UI, both for itself and for the generated forms.

**Desktop:**
 - OS: Fedora Linux
 - Browser: All
 - Version: Dirigible 9.0.0

### Video demonstration

https://github.com/eclipse/dirigible/assets/82379274/e61238a9-ed2d-4bca-bac0-585556af72d1

**Comment by ThuF** [comment]
Fixed with: https://github.com/eclipse/dirigible/pull/3630
