### ISSUE TITLE
[Templates] Entity API - cannot update entity using the returned value by GET

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3223]
It is not possible to update entity using the returned value by GET.
For example if you get the following entity:
![image](https://github.com/eclipse/dirigible/assets/5058839/1ed571c2-4424-4f80-b5da-d9e5650bfcb1)
And try to update it using the returned body
![image](https://github.com/eclipse/dirigible/assets/5058839/3b9fa909-0112-4913-9a04-32f3330907cb)
You will get
```
{
    "code": 500,
    "message": "2024-01-16 15:03:35.0"
}
```
In the logs there is only this
```
2024-01-16 15:25:37.173 [ERROR] [http-nio-8080-exec-8] app.db.dao.codbex_salesorder - Updating CODBEX_SALESORDER[37] failed
java.lang.Exception: 2024-01-16 15:03:35.0
```

The root cause is that when you PUT a timestamp, the code expects different format or integer.
For example the following works:
![image](https://github.com/eclipse/dirigible/assets/5058839/719f960d-35ef-4fe0-af6f-94a79ee17023)

**Comment by iliyan-velichkov** [comment]
Logging will be enhanced by https://github.com/eclipse/dirigible/pull/3222

**Comment by ThuF** [comment]
@iliyan-velichkov I guess we should close this issue as it seems to be fixed with:
- https://github.com/eclipse/dirigible/pull/3366

**Comment by iliyan-velichkov** [comment]
yes, it is fixed
