### ISSUE TITLE
[EDM] Use topic instead of queue for publishing messages in the DAOs

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3224]
Use topic instead of queue for publishing messages in the DAOs.
Example:
![image](https://github.com/eclipse/dirigible/assets/5058839/119fc202-ca7d-4e69-bd0f-afa30dc4a45c)
`queue` should be `topic`
This way, you will be able to have more than one listeners.

**Comment by iliyan-velichkov** [comment]
[Electra listeners](https://github.com/codbex/codbex-electra/tree/main/codbex-electra-opencart/listeners) must be adapted as well once this issue is fixed.

**Comment by ThuF** [comment]
So I guess the DAO template should change from:

```ts
producer.queue("${projectName}/${perspectiveName}/${name}").send(JSON.stringify(data));
```
to
```ts
producer.topic("${projectName}/${perspectiveName}/${name}").send(JSON.stringify(data));
```

@iliyan-velichkov could you confirm, so that I can make the change?

**Comment by iliyan-velichkov** [comment]
> So I guess the DAO template should change from:
> 
> ```ts
> producer.queue("${projectName}/${perspectiveName}/${name}").send(JSON.stringify(data));
> ```
> 
> to
> 
> ```ts
> producer.topic("${projectName}/${perspectiveName}/${name}").send(JSON.stringify(data));
> ```
> 
> @iliyan-velichkov could you confirm, so that I can make the change?

yes

**Comment by ThuF** [comment]
To be fixed with:
- https://github.com/eclipse/dirigible/pull/3517
