### ISSUE TITLE
[EDM] Visualize entity ID in the UI in readonly mode

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3233]
Visualize entity ID in the UI in readonly mode.
For example, if you have salesorder, it will be useful to know the ID of the order.
![image](https://github.com/eclipse/dirigible/assets/5058839/46026914-2012-4eae-ad95-cf865281da51)

**Comment by ThuF** [comment]
I guess this one is duplicated by:
- https://github.com/eclipse/dirigible/issues/3305

**Comment by delchev** [comment]
Let's use and visualise the Sales Order Number (e.g. `SO00000123`) instead of ID itself. Number generation can be applied following the 6. from https://github.com/codbex/codbex-rhea/wiki

**Comment by iliyan-velichkov** [comment]
> Let's use and visualise the Sales Order Number (e.g. `SO00000123`) instead of ID itself. Number generation can be applied following the 6. from https://github.com/codbex/codbex-rhea/wiki

Yes, this will be implemented with https://github.com/codbex/codbex-electra/issues/80
But I think in general is nice to have the IDs in the UI.
Consider to add them.
This once replicates https://github.com/eclipse/dirigible/issues/3305
