### ISSUE TITLE
[EDM] Cannot update entity when changing boolean value

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3257]
If I click on `Edit` button for entry which has boolean column and change the value from checked to unchecked, I'm not able to click on `Update` button, since the button is disabled.
![image](https://github.com/eclipse/dirigible/assets/5058839/9c74beca-cc70-449f-affd-0ca16f2510a7)
![image](https://github.com/eclipse/dirigible/assets/5058839/c31575b0-8c7d-4287-af25-bcdfd5ed5fc6)

**Comment by ThuF** [comment]
@iliyan-velichkov Could you check if this was already fixed with:
- https://github.com/eclipse/dirigible/issues/3352

**Comment by iliyan-velichkov** [comment]
yes, this is already verified
