### ISSUE TITLE
Add capability for generic (customer) entity filtering

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3306]
The customer should be able to create a custom filters for an entity based on its fields (columns).
For example when you have SalesOrder entity
<img width="181" alt="image" src="https://github.com/eclipse/dirigible/assets/5058839/15b14932-d73f-445a-9751-6a60cf79d52a">
You should be able to filter by all its columns like Store, Status, Total etc.
I guess we could use the list method of the generated DAO with options.

**Comment by iliyan-velichkov** [comment]
duplicated by https://github.com/eclipse/dirigible/issues/2898 ?

**Comment by ThuF** [comment]
To be implemented in:
- https://github.com/eclipse/dirigible/issues/2898

**Comment by iliyan-velichkov** [comment]
@ThuF please reopen this issues. Check why in my comment [here](https://github.com/eclipse/dirigible/pull/3421#issuecomment-1943529401)
