### ISSUE TITLE
[Templates] Charts functionality

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3307]
We need to add charts functionality in order to support customer scenarios like
- number of sold products for period
- products which are about to be out of stock
- orders distribution by stores
- delayed orders
- etc.

**Comment by ThuF** [comment]
https://www.chartjs.org to be used as a framework for the charts.

**Comment by ThuF** [comment]
## Overview

- https://www.chartjs.org is used as a framework for the charts.
- Adds support for `Bar`, `Line`, `Pie`, `Doughnut`, `Polar Area` and `Radar` charts.
- Support of multiple datasets _(multiple properties in the entity/report definition)_.
  - For better visualization of the `Pie` and `Doughnut` charts use single dataset _(just one property in the entity/report definition)_.

## Demo

https://github.com/eclipse/dirigible/assets/4092083/84401acf-7f31-4bda-9cc6-cd3580524be7


## Chart Data Queries

### Data Count
```sql
select count(*) from
(
    select PROJECT_NAME as "Project",
        sum(TIMESHEET_HOURS) as "TotalHours",
        convert(avg(TIMESHEET_RATE), float) as "AverageRate",
        convert(sum(TIMESHEET_HOURS * TIMESHEET_RATE), float) AS "Total"
    from ${tablePrefix}PROJECT, ${tablePrefix}PROJECTASSIGNMENT, ${tablePrefix}TIMESHEET
    where PROJECT_ID = PROJECTASSIGNMENT_PROJECT and PROJECTASSIGNMENT_ID = TIMESHEET_PROJECTASSIGNMENT
    ${
        filter.Project && filter.StartPeriod && filter.EndPeriod ?
            'and PROJECT_ID = ? and TIMESHEET_STARTPERIOD >= ? and TIMESHEET_ENDPERIOD <= ?'
        :
        filter.Project && filter.StartPeriod ?
            'and PROJECT_ID = ? and TIMESHEET_STARTPERIOD >= ?'
        :
        filter.Project && filter.EndPeriod ?
            'and PROJECT_ID = ? and TIMESHEET_ENDPERIOD <= ?'
        :
        filter.StartPeriod && filter.EndPeriod ?
            'and TIMESHEET_STARTPERIOD >= ? and TIMESHEET_ENDPERIOD <= ?'
        :
        filter.Project ?
            'and PROJECT_ID = ?'
        :
        filter.StartPeriod ?
            'and TIMESHEET_STARTPERIOD >= ?'
        :
        filter.EndPeriod ?
            'and TIMESHEET_ENDPERIOD <= ?'
        :
            ''
    }
    group by PROJECT_NAME
)
```

### Data Query
```sql
select PROJECT_NAME as "Project",
    sum(TIMESHEET_HOURS) as "TotalHours",
    convert(avg(TIMESHEET_RATE), float) as "AverageRate",
    convert(sum(TIMESHEET_HOURS * TIMESHEET_RATE), float) AS "Total"
from ${tablePrefix}PROJECT, ${tablePrefix}PROJECTASSIGNMENT, ${tablePrefix}TIMESHEET
where PROJECT_ID = PROJECTASSIGNMENT_PROJECT and PROJECTASSIGNMENT_ID = TIMESHEET_PROJECTASSIGNMENT
${
    filter.Project && filter.StartPeriod && filter.EndPeriod ?
        'and PROJECT_ID = ? and TIMESHEET_STARTPERIOD >= ? and TIMESHEET_ENDPERIOD <= ?'
    :
    filter.Project && filter.StartPeriod ?
        'and PROJECT_ID = ? and TIMESHEET_STARTPERIOD >= ?'
    :
    filter.Project && filter.EndPeriod ?
        'and PROJECT_ID = ? and TIMESHEET_ENDPERIOD <= ?'
    :
    filter.StartPeriod && filter.EndPeriod ?
        'and TIMESHEET_STARTPERIOD >= ? and TIMESHEET_ENDPERIOD <= ?'
    :
    filter.Project ?
        'and PROJECT_ID = ?'
    :
    filter.StartPeriod ?
        'and TIMESHEET_STARTPERIOD >= ?'
    :
    filter.EndPeriod ?
        'and TIMESHEET_ENDPERIOD <= ?'
    :
        ''
}
group by PROJECT_NAME
${
    filter["$limit"] && filter["$offset"] ?
        'limit ? offset ?'
    :
    filter["$limit"] ?
        'limit ?'
    :
    filter["$offset"] ?
        'offset ?'
    :
        ''
}
```

## Bar Chart
<img width="1920" alt="Screenshot 2024-03-08 at 19 12 14" src="https://github.com/eclipse/dirigible/assets/4092083/7782b855-6e11-477e-b281-36cde0482947">

## Line Chart
<img width="1920" alt="Screenshot 2024-03-08 at 19 26 31" src="https://github.com/eclipse/dirigible/assets/4092083/60958b16-7ecb-4577-98ae-c84f035fa346">

## Pie Chart
<img width="1920" alt="Screenshot 2024-03-08 at 19 28 42" src="https://github.com/eclipse/dirigible/assets/4092083/8934dfff-b280-4f06-8830-a3c07c93a529">

## Pie Chart (Single Dataset)
<img width="1920" alt="Screenshot 2024-03-08 at 19 37 45" src="https://github.com/eclipse/dirigible/assets/4092083/47e060a0-5377-4b2d-b820-2e910ed078ee">

## Doughnut Chart
<img width="1920" alt="Screenshot 2024-03-08 at 19 27 58" src="https://github.com/eclipse/dirigible/assets/4092083/154ab83a-2a8c-49a4-892a-79a5041ce009">

## Doughnut Chart (Single Dataset)
<img width="1920" alt="Screenshot 2024-03-08 at 19 36 55" src="https://github.com/eclipse/dirigible/assets/4092083/35836093-be59-478d-99a8-52dca492e4fb">

## Polar Area
<img width="1917" alt="Screenshot 2024-03-08 at 19 32 19" src="https://github.com/eclipse/dirigible/assets/4092083/b0b4f49a-c39b-4eab-a95c-9b65b9f263a5">

## Radar
<img width="1920" alt="Screenshot 2024-03-08 at 19 33 55" src="https://github.com/eclipse/dirigible/assets/4092083/aeca67ff-0596-4b6a-9545-ba57d21c3158">

Fixes: #3307

**Comment by ThuF** [comment]
## TODO
- Consider using [WebJar](https://search.maven.org/artifact/org.webjars.npm/chart.js/4.4.1/jar) instead of CDN:
  ```
  "org.webjars.npm" % "chart.js" % "4.4.2"
  ```

  ```xml
  <dependency>
    <groupId>org.webjars.npm</groupId>
    <artifactId>chart.js</artifactId>
    <version>4.4.2</version>
  </dependency>
  ```

Currently the CDN distribution is being used, as using the WebJar results into the following error:

<img width="684" alt="Screenshot 2024-03-08 at 19 45 22" src="https://github.com/eclipse/dirigible/assets/4092083/f159a0bc-b98a-4450-9d6f-97f8609df76e">


```html
		<!-- <script src="/webjars/chart.js/4.4.2/dist/chart.js"></script> -->
		<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
```

**Comment by StanZGenchev** [comment]
The CDN `chart.js` file and the webjar `chart.js` file are different, despite having the same name.
When using the webjar, you must use `chart.umd.js` as that is the one used by the CDN.
So just replace the link with this:
```html
<script type="text/javascript" src="/webjars/chart.js/4.4.2/dist/chart.umd.js"></script>
```

**Comment by ThuF** [comment]
`chart.js` is now loaded from WebJar instead of the CDN:
- https://github.com/eclipse/dirigible/commit/0656ac11d4bee050b704e74bbc037cdb8a0607e3
