### ISSUE TITLE
[EDM] Support `widgetSize` for the grid layout

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#3330]
Support `widgetSize` for the grid layout

**Comment by delchev** [comment]
#if($property.widgetSize)${property.widgetSize}#elsefd-col-md--8#end

**Comment by delchev** [comment]
```
$scope.widgetSize = [
            { value: "fd-col-md--2 fd-col--3", label: "Small" },
...
```

**Comment by ThuF** [comment]
@delchev, @himchev I guess this issue should be closed, as the functionality was introduced with:
- https://github.com/eclipse/dirigible/pull/3420
