### ISSUE TITLE
[Templates] Cannot select the first entry in dropdown widget

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3355]
Having the following entity
![image](https://github.com/eclipse/dirigible/assets/5058839/fb975f4c-ec0d-4e96-904e-df0d3168afd7)
I'm not able to select the first option for store.
![image](https://github.com/eclipse/dirigible/assets/5058839/66490f51-f7f1-4d7b-8ff8-a793ad4a7649)
![image](https://github.com/eclipse/dirigible/assets/5058839/91b902d6-6a23-4612-a80f-7a8c81a567c4)
![image](https://github.com/eclipse/dirigible/assets/5058839/3cd2e5ad-de49-45a4-a577-4ae917267638)
![image](https://github.com/eclipse/dirigible/assets/5058839/30d28d33-e96b-4dcb-adf5-56fc8b6da935)

but I can select the second one
![image](https://github.com/eclipse/dirigible/assets/5058839/b0b4e048-b540-4589-a44d-8ee515f2d3ca)

**Comment by iliyan-velichkov** [comment]
it seems that the root cause is that "Demo OpenCart Store" has id=0 but I think it should be working with 0 even with negative ids.

**Comment by ThuF** [comment]
@iliyan-velichkov I guess this is more related to the validation of the input form. Maybe the validation doesn’t quite work for the dropdown widget. We’ll have to investigate this one further.
