### ISSUE TITLE
[Templates] DAO - Add upsert to generated DAOs

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3359]
Add upsert (create or update) function to the generated DAOs.

**Comment by ThuF** [comment]
It would be great if a **merge** query is being executed instead of `find` and then `create`/`update`:
- https://en.wikipedia.org/wiki/Merge_(SQL)

**Comment by ThuF** [comment]
Fixed with:
- https://github.com/eclipse/dirigible/pull/3383

Implemented as:

```ts
    public upsert(entity: EmployeeCreateEntity | EmployeeUpdateEntity): number {
        const id = (entity as EmployeeUpdateEntity).Id;
        if (!id) {
            return this.create(entity);
        }

        const existingEntity = this.findById(id);
        if (existingEntity) {
            this.update(entity as EmployeeUpdateEntity);
            return id;
        } else {
            return this.create(entity);
        }
    }
```

**Merge** functionality to be introduced at later point, if needed:
- https://en.wikipedia.org/wiki/Merge_(SQL)
