### ISSUE TITLE
[Template] Optional field for custom dataSource when generating app from model

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [eclipse/dirigible#3368]
Add `dataSource` parameter during generation. Also it should be possible to specify the `dataSource` per entity in the EDM model.

Related to:
- https://github.com/eclipse/dirigible/issues/3353

**Comment by ThuF** [comment]
Sample EDM, using the `SystemDB` datasource to fetch data from the `DIRIGIBLE_JOBS` table:

https://github.com/eclipse/dirigible/assets/4092083/c14a780c-2b40-4c70-a0fd-388ff000054f
