### ISSUE TITLE
[IDE] Support using absolute paths in the TypeScript files

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3397]
Currently only relative paths are supported but not absolute.
![image](https://github.com/eclipse/dirigible/assets/5058839/61bed496-d782-4f8b-814d-42c358ddd9ea)
If I'm using relative paths, the editor doesn't find it but the code works.

**Comment by ThuF** [comment]
`Global Imports` _(`Absolute Project Path Imports`)_ are now supported with the following syntax:

```ts
import { MyRepository } from "projectName/path/MyRepository"
```

However in order for the `tsc` compilation to work, the `tsconfig.json` should be updated as follows:

```json
{
    "compilerOptions": {
        "module": "ESNext",
        "target": "ES6",
        "moduleResolution": "Node",
        "baseUrl": "../",
        "lib": [
            "ESNext",
            "DOM"
        ],
        "paths": {
            "sdk/*": [
                "../modules/src/*"
            ],
            "/*": [
                "../*"
            ]
        },
        "types": [
            "../modules/types"
        ]
    }
}
```

A `baseUrl` and `paths` mapping for `/*` should be added in the `tsconfig.json`.
