### ISSUE TITLE
[IDE] Transpile TypeScript files on save (cmd+s)

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3402]
Will be very useful if we transpile TypeScript files on save (cmd+s) instead of publishing the whole project.

**Comment by ThuF** [comment]
Currently TypeScript files are compiled on "Publish" as described here:
- https://github.com/eclipse/dirigible/issues/2997#issuecomment-1824696981
- https://github.com/eclipse/dirigible/issues/3239

We can modify the compilation to be executed "on-save" as well, but this could result in "slow" overall IDE experience. I guess we should discuss it more thoroughly together with @delchev.

**Comment by iliyan-velichkov** [comment]
> Currently TypeScript files are compiled on "Publish" as described here:
> 
> * [[Core] TypeScript Services are not Published #2997 (comment)](https://github.com/eclipse/dirigible/issues/2997#issuecomment-1824696981)
> * [[Core] TypeScript - Define tsconfig.json to be Used #3239](https://github.com/eclipse/dirigible/issues/3239)
> 
> We can modify the compilation to be executed "on-save" as well, but this could result in "slow" overall IDE experience. I guess we should discuss it more thoroughly together with @delchev.

What is the cost of compiling one file?

**Comment by ThuF** [comment]
Workspace `onSave` extensibility can be used:
- [ide-entity/extensions/workspace-on-save.extension](https://github.com/eclipse/dirigible/blob/master/components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/extensions/workspace-on-save.extension)
- [ide-entity/template/transformer-on-save.js](https://github.com/eclipse/dirigible/blob/master/components/ide/ide-ui-entity/src/main/resources/META-INF/dirigible/ide-entity/template/transformer-on-save.js)

**Comment by ThuF** [comment]
## Demo

https://github.com/eclipse/dirigible/assets/4092083/c569175c-0fd3-42fd-9fe7-79631c3db9e8
