### ISSUE TITLE
Database table name does not match the .table file name

### ISSUE THREAD

**Issue by tsvetan-stoyanov** [eclipse/dirigible#343]
When creating a new Database Table, user is given the option to change the .table file name - e.g. to customers.table. However the resulting db table is still named MYTABLE.
This is confusing. I would expect to have the table named as the file with the definition.

<img width="514" alt="image" src="https://user-images.githubusercontent.com/6024682/46146677-07ec8e00-c26c-11e8-9de3-ca3eb4f06fae.png">

**Comment by delchev** [comment]
won't fix
