### ISSUE TITLE
[Templates] I cannot create boolean column which is not null in the DB

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3455]
I cannot create boolean column which is not null in the DB.
If I add a column which is not null, I cannot save the UI form with value false.
![image](https://github.com/eclipse/dirigible/assets/5058839/8d4e19e1-70d5-4b3d-8afb-51f263f238da)
![image](https://github.com/eclipse/dirigible/assets/5058839/85e2f750-eb80-46cc-a874-ea29b95c8bd5)

I have to make it not null. This way nulls are allowed in the table and the generated typescript allows null/undefined.

**Comment by delchev** [comment]
To be fixed as introducing an explicit property `isRequired` which can be leaved `false` for this case and still in the database will be stored the boolean value `false`
