### ISSUE TITLE
[EDM] Timestamp not properly visualized

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3481]
In the following screenshot you ca see that the time is not visible at all
![image](https://github.com/eclipse/dirigible/assets/5058839/72e8edcc-7417-41c8-bad5-3777bfbdde7b)

**Comment by ThuF** [comment]
The default widget size was introduced with:
- https://github.com/eclipse/dirigible/issues/3330

I guess we should increase the default size for timestamps.

> As a workaround the layoutSize can be configured explicitly for the timestamp fields.
