### ISSUE TITLE
Preview View

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#35]
Preview is showing the content of an URL. It has to be integrated with the Workspace View events to update the URL on file select.

**Comment by ThuF** [comment]
Initial version available at: https://github.com/dirigiblelabs/ide-preview

**Comment by delchev** [comment]
Implemented in:
https://github.com/eclipse/dirigible/tree/master/ide/ide-preview

Source:
https://github.com/dirigiblelabs/ide-preview
