### ISSUE TITLE
Exception when querying data from Snowflake

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [eclipse/dirigible#3558]
When querying data from Snowflake in the console you get the following exception:

```
JDBC driver internal error: Fail to retrieve row count for first arrow chunk: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available.
```

This is fixed when using:
```sql
ALTER SESSION SET JDBC_QUERY_RESULT_FORMAT='JSON';
```

Maybe this could be integrated to be used by default so no exception is displayed to the user.

**Comment by delchev** [comment]
fixed as built-in parameter
