### ISSUE TITLE
[BPM] Research flowable user task assignment mechanism

### ISSUE THREAD

**Issue by art-entrery** [eclipse/dirigible#3560]
In order to implement proper inbox functionality for the user tasks in flowable we have to understand few things:

1. How is the user & group assignment done in the flowable engine and how is it related to the identity management - local or federated ?
2. Can we get user roles for the currently logged in user and fetch all the task assigned to him ?
3. What should be done in the editor( represented in the BPMN xml respectively) in order to have a user properly assigned in the Flowable tables

**Comment by art-entrery** [comment]
@delchev I consider this research done after our discussion

**Comment by ThuF** [comment]
@art-entrery, @delchev I'm closing this issues as completed, since the research is already done.
