### ISSUE TITLE
[BPM][Inbox] Implement list process task REST endpoint(s)

### ISSUE THREAD

**Issue by art-entrery** [eclipse/dirigible#3604]
In order to show all the relevant tasks for the currently logged-in user we need to implement REST endpoint as follows:

1. Get the currently active user from the Spring session
2. List all the roles of the currently active user
3. Based on the roles return all the relevant tasks where the user is one of the following: assignee, candidate user, part of candidate user group

NOTE: The key insight here is that we need a match between the user or group assigned during the process modeling (design time) and the roles assigned to the currently logged in user

**Comment by ThuF** [comment]
@art-entrery Should we consider this issue done?

**Comment by entrery** [comment]
Done with #3621
