### ISSUE TITLE
[BPM][Inbox] Implement functionality to claim user task

### ISSUE THREAD

**Issue by art-entrery** [eclipse/dirigible#3605]
User tasks can be assigned directly to individual users during design time. However, it is also common practice to assign tasks to user groups, allowing any member of the group to take over and execute the task. With this in mind we need functionality to claim user tasks in the Process Perspective leveraging the existing flowable APIs. A logged in user should only claim a task if he/she is a candidate user or in the group of candidate users for the task. Prototype shown below

<img width="1458" alt="image" src="https://github.com/eclipse/dirigible/assets/160129659/8754d128-745f-4070-b0ad-5d865683c51c">

**Comment by entrery** [comment]
Done with #3655
