### ISSUE TITLE
Cannot change file name to uppercase

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3642]
Cannot change file name to uppercase.
For example, if I have a file called `file.txt` and try to rename it to `FILE.txt`, nothing happens.
![image](https://github.com/eclipse/dirigible/assets/5058839/f99aaad2-3e70-482d-890f-c8b1dd822e64)

**Comment by StanZGenchev** [comment]
Are you perhaps using macOS? The file system there is case insensitive.

**Comment by iliyan-velichkov** [comment]
> Are you perhaps using macOS? The file system there is case insensitive.

Yes, it is mac. However, this could be implemented.
Also I'm able to change the filename case in the VSCode.

**Comment by delchev** [comment]
> Also I'm able to change the filename case in the VSCode.
If VSCode can make it, we also can make it
