### ISSUE TITLE
[UI] Create a unified "Extensions" service

### ISSUE THREAD

**Issue by StanZGenchev** [eclipse/dirigible#3716]
**Describe the issue**
Extension points are a core feature of Dirigible, yet we are not taking full advantage of them.
Also, we are referencing extension point services in multiple places, which is not only confusing but it's a duplication of code.
We need a single `Extensions` service that we can use to get views, perspectives, menus and dialog windows and it must allow us to use a custom extension point. For example, that way a user can make use of the dialogWindow API to create their own custom dialog and register it on a custom extension point, so it wouldn't get mixed with the system ones. This will also help us clean a lot of the unnecessary code created in #2900 

**Example**:
```javascript
Extensions.get(
    type, // required - This is the type of extension - `perspective`, `view`, `dialogWindow` or `menu`.
    extensionPoint // optional - This is the name/id of the extension point. If not specified, a default will be used based on the type.
);
```

**Comment by StanZGenchev** [comment]
## How to use the new `Extensions` API

```javascript
Extensions.get( // Returns a promise
  type, // required - The type of extension - `perspective`, `dialogWindow`, `view`, `subview`, `editor` or `menu`
  extensionPoint // optional - The extension point on which the extension is registered. Do not specify if you want to use the system default.
)
```

Inside a view:
```javascript
angular.module('example', ['ideUI', 'ideView'])
.controller('ExampleController', ['Extensions', function (Extensions) { // Load the `Extensions` service
    Extensions.get('dialogWindow', 'custom-ext-point').then(
        function (result) {
            console.log(result);
        }, function (error) {
            console.error(error);
        } 
    )
}]);
```

Inside a custom module or controller:
```javascript
angular.module('customModule', ['ideExtensions']) // Load the `ideExtensions` module
.directive('customMenuDirective', ['Extensions', function (Extensions) { // Load the `Extensions` service
    return {
        link: function (scope) {
            Extensions.get('menu', 'custom-ext-point').then(function (menuItems) {
                scope.menu = menuItems;
            });
        },
    };
}]);
```

**Comment by ThuF** [comment]
The migrated projects can be found here:
- [test-20240405064848.zip](https://github.com/eclipse/dirigible/files/14887310/test-20240405064848.zip)
- [test-custom-actions-20240405064851.zip](https://github.com/eclipse/dirigible/files/14887311/test-custom-actions-20240405064851.zip)
