### ISSUE TITLE
[EDM] Cannot filter by boolean field with value false

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3725]
For example, I cannot filter all stores which are disabled
<img width="1549" alt="image" src="https://github.com/eclipse/dirigible/assets/5058839/ad6088ad-82c8-4513-a731-021ecf0a3942">
<img width="911" alt="image" src="https://github.com/eclipse/dirigible/assets/5058839/363f73da-4bab-4711-bb22-10b75873480a">

**Comment by ThuF** [comment]
I guess in order to cover this scenario, we should add in the filter indeterminate checkbox:

```html
<fd-form-item>
	<fd-checkbox id="cbid9" compact="false" dg-indeterminate="true">
	</fd-checkbox>
	<fd-checkbox-label for="cbid9">Indeterminate</fd-checkbox-label>
</fd-form-item>
```

https://github.com/dirigiblelabs/sample-ide-perspective/blob/e0cbf67f8b2e3ef436960cee40e6f81a69101ced/ide-example/game.html#L428-L432
