### ISSUE TITLE
[UI] Cannot copy and paste multiple files to folder

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3727]
Mark 3 files and select copy
![image](https://github.com/eclipse/dirigible/assets/5058839/b7325db1-6025-4262-a2dd-96f1098e472a)
paste into a folder
![image](https://github.com/eclipse/dirigible/assets/5058839/03ff30ec-42e4-4747-96ed-c380559e56c0)
only one file has been copied 
![image](https://github.com/eclipse/dirigible/assets/5058839/9cd94c34-6176-4ed9-8ec2-7f61a4c236b0)

**Comment by delchev** [comment]
preparation: https://github.com/eclipse/dirigible/commit/26edd5fe010e66dade66a6427874641484618265
