### ISSUE TITLE
[OTEL] Integrate Opentelemetry in dirigible

### ISSUE THREAD

**Issue by Fluctuationqt** [eclipse/dirigible#3746]
Integrate Opentelemetry in Eclipse Dirigible, there are two possible options:
- SDK
- Agent (the agent might be noisy)

Research the way to tag and group metrics from different integrations like Camel, JS/TS engine etc...

**Comment by iliyan-velichkov** [comment]
implemented in https://github.com/eclipse/dirigible/pull/4451
