### ISSUE TITLE
[Templates] Spaces in the perspective must be disallowed

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3793]
Currently, it is possible to use spaces in the perspective names.
This leads to DAO in folders with spaces.
If you want to use the generated DAOs, you will have to add imports with spaces which may lead to issues.
![image](https://github.com/eclipse/dirigible/assets/5058839/5763ee86-0191-489f-a383-8af5982b4e53)
![image](https://github.com/eclipse/dirigible/assets/5058839/a978e28d-37e8-40b5-a4c4-4a75467d07d4)

Related issue:
- https://github.com/eclipse/dirigible/issues/3715#issuecomment-2074132681

**Comment by StanZGenchev** [comment]
Perspective names are names, therefore they can have spaces, alphanumeric characters, dashes, dots, semicolons, etc.
The problem here is that the perspective name is used for the generated path. The perspective ID should be used instead.
@ThuF can you take a look at this?

**Comment by delchev** [comment]
it is fixed already with perspective name/label approach
