### ISSUE TITLE
Generated resources are placed in folders with entity perspective name

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3794]
Generated resources are placed in folders with entity perspective name.
For example, if you have project `codbex-electra` with entity `SalesOrder` in perspective `Sales orders` the DAO will be placed in folder `codbex-electra/gen/dao/Sales orders`. 
This way, if you use the generated DAO and rename the perspective, your code will stop working.
The import must be updated.

Proposed solutions:
- but the DAO in the `gen/dao` folder
- add  `index.ts` in the `dao` folder

**Comment by iliyan-velichkov** [comment]
In addition, the perspective name is used in the messaging as well
![image](https://github.com/eclipse/dirigible/assets/5058839/a75737a2-29d8-4afe-9d43-3c65221ce625)
Consider to decouple it as well.

**Comment by delchev** [comment]
@iliyan-velichkov it should be fixed now, no?

**Comment by iliyan-velichkov** [comment]
@delchev I'm not sure why it is placed in folder `sales-orders`
`sales-orders` is used for folder name and for topic name as well.
![image](https://github.com/eclipse/dirigible/assets/5058839/040a5003-9b6c-497e-bde7-70e68cbfc770)
![image](https://github.com/eclipse/dirigible/assets/5058839/2309734d-9bd7-4dfb-b731-c940248fe315)
![image](https://github.com/eclipse/dirigible/assets/5058839/6dabe036-5796-4e95-aed7-0c70199e2fd3)

**Comment by iliyan-velichkov** [comment]
Ok, I updated the entities manually and now they are placed in `salesordername`.
![image](https://github.com/eclipse/dirigible/assets/5058839/2ebd250e-0d00-4857-94cd-d1354adf5957)
However, I don't think that the perspective should be used in the topic name. In my opinion, it could be removed.
![image](https://github.com/eclipse/dirigible/assets/5058839/010cb6a7-1a98-45af-8f96-5bd6e5da621b)

**Comment by delchev** [comment]
will keep the current  behavior for now
