### ISSUE TITLE
[BPM][Inbox] Standalone UI app not loading assigned tasks automatically

### ISSUE THREAD

**Issue by entrery** [eclipse/dirigible#3803]
At the moment the standalone app is more or less a copy of the same functionality in the BPM perspective. As such the loading of the tasks is only working if we manually press the reload button which is misleading (even if we execute claim operation we dont see the effect imediately). Introduce automatic data loading in the page and remove the legacy parts from the UI code

**Comment by delchev** [comment]
Fixed with: https://github.com/eclipse/dirigible/pull/3827
