### ISSUE TITLE
[Prototype] Implement generic reporting functionality

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3831]
Implement generic reporting functionality which allows you to have
- measures
- filters
- grouping

It should be possible 
- to change the visualization - bar chart, line chart, table, pie chart, etc.
- save the configured chart
- add predefined reports (like saved searches)
- to have ordering (asc and desc)

**Comment by ThuF** [comment]
@iliyan-velichkov instead of this one, we can focus on, so maybe close this issue?
- https://github.com/eclipse/dirigible/issues/3841
- https://github.com/eclipse/dirigible/issues/3858
