### ISSUE TITLE
Broken perspective names - ${perspectiveLabel}

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3833]
When I regenerate the Electra edm using the Dirigible master version, all perspective names have value `${perspectiveLabel}`.

![image](https://github.com/eclipse/dirigible/assets/5058839/a9b52541-a858-429b-90b5-3b908b8d8b71)
![image](https://github.com/eclipse/dirigible/assets/5058839/eed47c1e-d10e-4d7e-8aef-cee0459c922f)
![image](https://github.com/eclipse/dirigible/assets/5058839/2d847568-3221-4244-ba27-665c248f05eb)

**Comment by delchev** [comment]
@iliyan-velichkov please, first click `Save` and then `Regenerate` button.
