### ISSUE TITLE
[IDE] Unpublish doesn't work

### ISSUE THREAD

**Issue by iliyan-velichkov** [eclipse/dirigible#3836]
To reproduce:
- Clone electra branch `ts-autosave-issue`
- Publish it
- Open http://localhost:8080/services/ts/codbex-electra/ui/api/TestService.ts/test
- You will get result 20
![image](https://github.com/eclipse/dirigible/assets/5058839/f8612dd5-a329-4573-9783-f647a692e949)
- Delete the `TestService.ts` file (Delete & Unpublish)
![image](https://github.com/eclipse/dirigible/assets/5058839/45e7778b-5137-43fc-8c12-03402b5226ff)
- Open http://localhost:8080/services/ts/codbex-electra/ui/api/TestService.ts/test again
- It is still available
![image](https://github.com/eclipse/dirigible/assets/5058839/f8612dd5-a329-4573-9783-f647a692e949)

The issue is reproducible even with `Unpublish` button
![image](https://github.com/eclipse/dirigible/assets/5058839/4b5449bd-e4c2-464b-8353-b5c6026c3a72)

**Comment by ThuF** [comment]
This behaviour happens only with `*.ts` files:
- When a `*.ts` file is **Published**, a `*.js` file is compiled out of it.
- When a `*.ts` file is **Unpublished**, then the `*.ts` file is deleted, but the `*.js` file remains in the `Registry`.

We should delete also the `*.js` file on **Unpublish** of the `*.ts` file:
- Add `ide-workspace-after-unpublish` extension, similar to that one: https://github.com/eclipse/dirigible/commit/2db2de95199d2321a33c4d47b490926a933779f3#diff-5424040846f9720a3823dbcf79afb5a7086539d90d35d373f64fd85e95dba402
- Add implementation of the extension, similar to that one, that would delete the `*.js` file as well: https://github.com/eclipse/dirigible/commit/2db2de95199d2321a33c4d47b490926a933779f3#diff-c77fcd5170d46d2bb884f4e55cb37aea96cbd85c6b124c1a42945dd6e188c512
