### ISSUE TITLE
[Report] Bug when opening .report file

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [eclipse/dirigible#3857]
When you refresh Dirigible and try to open `.report` file you are prompted to save the page with `f.txt` and on the second click it opens the file, this happens on every new refresh.

<img width="1605" alt="image" src="https://github.com/eclipse/dirigible/assets/5245055/48f089cf-0b84-43ba-af1d-fa94930254d2">

**Comment by delchev** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/8cabe4fae5c599a28d6fb5fe6c2c6fd0bc4398a7
