### ISSUE TITLE
Dependencies from `project.json` Not Installed When Building Docker Image with Atlas Base

### ISSUE THREAD

**Issue by Mrgoblings** [eclipse/dirigible#4056]
**Describe the bug**
When creating a Docker image using the codbex-atlas base image, the dependencies specified in the `project.json` file are not installed. This issue occurs with the following Dockerfile:

```Dockerfile
# Docker descriptor for codbex-athena
# License - http://www.eclipse.org/legal/epl-v20.html

FROM ghcr.io/codbex/codbex-atlas:0.36.0

COPY codbex-athena target/dirigible/repository/root/registry/public/codbex-athena

ENV DIRIGIBLE_HOME_URL=/services/web/codbex-athena/index.html
```

An example `project.json` file is as follows:

```json
{
    "guid": "codbex-athena",
    "dependencies": [
        {
            "guid": "codbex-account",
            "type": "git",
            "url": "https://github.com/codbex/codbex-accounts.git",
            "branch": "main"
        },
        {
            "guid": "codbex-invoices",
            "type": "git",
            "url": "https://github.com/codbex/codbex-invoices.git",
            "branch": "main"
        },
        {
            "guid": "codbex-payments",
            "type": "git",
            "url": "https://github.com/codbex/codbex-payments.git",
            "branch": "main"
        }
    ],
    "actions": [
        {
            "name": "Build TypeScript",
            "commands": [
                {
                    "os": "unix",
                    "command": "tsc"
                },
                {
                    "os": "windows",
                    "command": "cmd /c tsc"
                }
            ],
            "registry": "true"
        }
    ]
}
```

**To Reproduce**
1. Create a Dockerfile as shown above, using `ghcr.io/codbex/codbex-atlas:0.36.0` as the base image.
2. Include a `project.json` file with dependencies as shown in the example.
3. Build the Docker image.
4. Observe that the dependencies specified in `project.json` are not installed.

**Expected behavior**
The Docker image build process should install the dependencies listed in the `project.json` file.

**Desktop (please complete the following information):**
- OS: macOS
- Browser: Firefox
- Version: Latest

**Comment by iliyan-velichkov** [comment]
duplicates https://github.com/eclipse/dirigible/issues/4000
