### ISSUE TITLE
[IDE] Generic support for Statusbar

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#407]
Generic support for Statusbar, that should pop-up, when new "status" is received and collapse after that. The statusbar should contain data for previous "Errors", "Warnings" and "Notifications".

Exemplary actions:
- Save File
- Save EDM Model
- Save BPM Process
- Git Clone
- Git Push
- Git Pull
- Publish Project(s)
  - Show the status of published _BPM Processes_
  - Show the status of published _Jobs & Listeners_
  - Show the status of published _Access Constraints_

**Comment by delchev** [comment]
Sample code for the supported topics by the status bar here:
https://github.com/eclipse/dirigible/issues/430

**Comment by delchev** [comment]
- [x] Save File
- [ ] Save EDM Model
- [ ] Save BPM Process
- [ ] Git Clone
- [ ] Git Push
- [ ] Git Pull
- [ ] Publish Project(s)
  - [ ] Show the status of published _BPM Processes_
  - [ ] Show the status of published _Jobs & Listeners_
  - [ ] Show the status of published _Access Constraints_

**Comment by delchev** [comment]
https://github.com/eclipse/dirigible/commit/9e2738d984104fdb42715cf992599b200176148c
https://github.com/eclipse/dirigible/commit/24a958045736439ed131b05c873485e31021fc0b
https://github.com/eclipse/dirigible/commit/3bcfc8bca0ff149a39732eb835ba044217de3f29
https://github.com/eclipse/dirigible/commit/50be631ac4319a7056a694ad5c21cee9f10816aa
https://github.com/eclipse/dirigible/commit/b51158465e1b274b76a9f1131048bf6c49a5cf87
https://github.com/eclipse/dirigible/commit/8baa1c02113e340211e7d66d48c6fee73fab9778
https://github.com/eclipse/dirigible/commit/a1659b786fd9b93c5b565f2d24036339bf2492a7
https://github.com/eclipse/dirigible/commit/1f5c9803f483434ac40a207f3e7c124a1f9797c2
https://github.com/eclipse/dirigible/commit/b4a70132754ccdd52ae4d4b328f0b32eac61222e
https://github.com/eclipse/dirigible/commit/3893dfc4a6e8beb87d2b15b5883fa2d0bd865ee7
