### ISSUE TITLE
[cmis] Implicit document path creation while creating a document

### ISSUE THREAD

**Issue by shturec** [eclipse/dirigible#434]
Currently, it's imperative that the folder (path) structure for a document exists before it's uploaded/created. 
It would be nice to have the option to have the path created for you on the fly as the document is created/uploaded. That preference could be controlled with a request header too to make it optional and explicit. The expected behavior is that:
- Let the path `/a/b/c` be non existent
- a file `file.txt` is `POST`ed to the service as `/a/b/c/file.txt`
- `/a/b/c` is created as part of serving the `POST` request and `file.txt` is placed in `c` available for download at path `\a\b\c\file.txt`
No errors or warnings for trying to create a document in non-existent path.
Only non-existent path segment are created.
The post could be send with request header `X-cmis: create-path-ondemand`

**Comment by delchev** [comment]
won't fix
