### ISSUE TITLE
Problem with setTimestamp, setTime and setDate of Statement

### ISSUE THREAD

**Issue by Scorze** [eclipse/dirigible#441]
When executing the following code:

...
var currentDate = new Date();
var statement = connection.prepareStatement(sql);
statement.setTimestamp(1, currentDate);

I get the following error: 
[ERROR] java.lang.NoSuchMethodException: java.sql.Timestamp.(java.lang.Double)

If i change currentDate=new Date().getTime() I get the following:

Cannot find function getTime in object 1564757259614.

**Comment by delchev** [comment]
Hi Scorze,

Thanks for the issue!

Can you please specify which version of the API you are using - v3 or v4?

```
var database = require('db/v4/database');
...
```

We highly recommend to use v4.
In v4 version the snippet above is working.

Regards,
Nedelcho

**Comment by Scorze** [comment]
Hey,

I am using the v3 version, I will switch to v4.

**Comment by Scorze** [comment]
The v4 version of the database API works on my  end.
