### ISSUE TITLE
Response API println and print don't work with UTF-8 characters

### ISSUE THREAD

**Issue by Scorze** [eclipse/dirigible#442]
When writing text to the response with either println or print that includes non-standard characters, like the Cyrillic alphabet, I get the following response:
[ERROR] Not an ISO 8859-1 character: [а]

In this case a being the Cyrillic version.
The response has the default Character encoding and content type of UTF-8.
Is it possible to print through PrintWriter instead of OutputStream?

**Comment by delchev** [comment]
Hi Scorze,

The fix https://github.com/eclipse/dirigible/commit/26879b79956e16932980eed130ab9d481523702f  should be available in the next release 3.5 planned for the end of the month. You can apply it directly on your instance to see whether it works for you.
1. Clone the project https://github.com/dirigiblelabs/api-http in your Dirigible workspace
2. Apply the changes in the file http/v4/response.js as it is made here: https://github.com/dirigiblelabs/api-http/commit/9f2ee9a01f191aa32e21a87cada0c3ab1f4a0ceb
3. Save & Publish

You should have the fix applied on your instance.

Regards,
Nedelcho

**Comment by Scorze** [comment]
Hey Nedelcho,

Thanks a lot, the fix works for my instance. Looks like the changes were already applied when i cloned the project. Looking forward to the next release!
