### ISSUE TITLE
Cleanup on deleting project, jobs, tables, access constraints

### ISSUE THREAD

**Issue by Scorze** [eclipse/dirigible#446]
After a project or individual job, table or access constraint files are deleted from the IDE, dirigible keeps looking for them as they are still in the database and constantly throws exceptions which fills up the logs with megabytes of "Resource not found" or "Job not found" types of errors which also slow down their dirigible instance. After deleting a project or a resource, the user should be asked if they want to delete the resource from the registry too or the user should be informed how they can remove the resource from the registry.

**Comment by delchev** [comment]
Can be safely performed via Unpublish before deleting the project - https://github.com/eclipse/dirigible/issues/562
