### ISSUE TITLE
Visualization issue with links in blog articles on dirigible.io

### ISSUE THREAD

**Issue by danachkov** [eclipse/dirigible#454]
**Describe the bug**
The links in blogs on dirigible.io do not pop out from the remaining text. I doubt that it's due to the markdown code since [the following blog](https://www.dirigible.io/blogs/2019/09/25/how_does_eclipse_dirigible_contribute_to_eclipse_che_7.html) looks fine on [Planet Eclipse](https://planeteclipse.org/planet/#main-content). Maybe the issue is related to the UI theme?

**To Reproduce**
Go to https://www.dirigible.io/blogs/2019/09/25/how_does_eclipse_dirigible_contribute_to_eclipse_che_7.html and compare it with the version at https://planeteclipse.org/planet/#main-content

**Expected behavior**
The links there should be in a color other than grey (i.e. blue) and should be at least underlined in order to pop out from the remaining text.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Chrome

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by delchev** [comment]
Fixed with: https://github.com/dirigible-io/dirigible-io.github.io/commit/63a3600f24d2871977c5ac6d8f2279f270c9cd21
