### ISSUE TITLE
[Git] Reset project is not working as expected

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#456]
**Describe the bug**
Resetting Git project results into Git Pull/Clone instead of reset to the last commit id

**To Reproduce**
1. Crate a GitHub repository
2. Push a project to the GitHub repository
3. Edit the project sources from local project in Dirigible
4. Edit the project sources from GitHub
6. Reset project from Dirigible

**Expected behavior**
Local project sources should be reset to the commit id of the last clone/pull/push

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
N/A

**Comment by delchev** [comment]
Fixed as https://github.com/eclipse/dirigible/issues/455
