### ISSUE TITLE
Cyrilic letters in file names lead to errors when importing

### ISSUE THREAD

**Issue by malkoto1** [eclipse/dirigible#467]
**Describe the bug**
If there is a cyrilic symbols in the name of a file that is part of an archive that someone tries to import through the import interface of Dirigible, the import fails when this file is reached and the project is imported in half (everything untill that file). This leaves Dirigible in an error state when nothing more can be imported and a refresh is needed.

**To Reproduce**
1. Add cyrilic symbol in the name of a file.
2. Zip it.
3. Try to import that project
4. Observe error and a project imported in half.

**Expected behavior**
An error should be thrown at least. 
Second import should be doable.
Non ASCII symbols in the names should be supported. There are development societies as Turkey and Germany, where the developers use non latin symbols in the names and, yes this is not a joke, in the code.

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version Latest

**Comment by delchev** [comment]
wont't fix
