### ISSUE TITLE
Dirigible should be able to work with a local copy of the code

### ISSUE THREAD

**Issue by malkoto1** [eclipse/dirigible#468]
**Is your feature request related to a problem? Please describe.**
As Dirigible isn't great with Git, but is great for local development it will be good to use a local copy of the code of the developer. 

**Describe the solution you'd like**
I want to have an option "Open" which will be loading a local copy of my code. This code will be evaluated and deployed.

**Describe alternatives you've considered**
Currently I am importing my code, developing it and then copying it from the "target" folder of Dirigible to my repository folder in order to commit it.

**Comment by delchev** [comment]
First step in this endeavour #534

**Comment by delchev** [comment]
Next step: #535

**Comment by delchev** [comment]
#538 and #539
