### ISSUE TITLE
Ctrl + Shift + F

### ISSUE THREAD

**Issue by malkoto1** [eclipse/dirigible#469]
**Is your feature request related to a problem? Please describe.**
The problem is that it is rear for someone to know the whole codebase of a project in order to develop it. Consider the case of the junior joining the project. It is always a looking of different files simultaniously and jumping from one to another reaching the case where something is being used but you don't know where it is comming from. Or you are just looking for something to refactor.

**Describe the solution you'd like**
Allow me to have a Ctrl + Shift + F in order to do the above, in order to search throughout all my project for something.

**Describe alternatives you've considered**
The alternatives to his is opening another editor (Like VS Code, for example) and performing the action there, or opening the Github/Gitlab Repo. Which is a No-Go.

**Comment by delchev** [comment]
Can you please, try to open the 'Search' view from the main menu -> Window -> Show View?
We can consider to have it open by default in the Workspace perspective as well as to open it and focus on it explicitly on the Ctrl + Shift + F combination.

**Comment by malkoto1** [comment]
I am with version 4.0.0 and it seems that this Search does not search. I wrote a word that is bot part of a filename and is seen in the content of several files.

**Comment by ThuF** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/de03133f1b7c2fedfa03209e971708c369556c93

Use `Ctrl/Cmd` + `Shft` + `F` to open the `Search` view.

Improved search results to be implemented with: https://github.com/eclipse/dirigible/issues/561
