### ISSUE TITLE
[Git Support] Allow support for different branches and functionality to change from one to another.

### ISSUE THREAD

**Issue by malkoto1** [eclipse/dirigible#470]
**Is your feature request related to a problem? Please describe.**
Git support.

**Describe the solution you'd like**
I would like to have an option, when I add a project from my Git repo, to be able to create new branches and to observe other branches that I have. 

I would like to pull the master, to create custom branch and to push into that new branch.

The case is: I have my Test environment with the code. I have Dirigible that can be reached by many people. I open the code, I make fix and test it. I would then like to create new branch with my fix or new feature or whatever and to push it in order to get a Code review before submitting to the master branch.

**Describe alternatives you've considered**
The alternative is to make the fix and either copy-paste it to my local environment (from the dirigible GUI) and perform the actions or to go to the "target" folder of Dirigible and to copy-paste from there.

**Comment by delchev** [comment]
Depends on: #468

**Comment by delchev** [comment]
#539
