### ISSUE TITLE
Dirigible not taking lower -> upper or upper->lower case as a rename

### ISSUE THREAD

**Issue by malkoto1** [eclipse/dirigible#471]
**Describe the bug**
If one tries to change the name of a file that is imported as a part of a project in Dirigible by changing lower case to upper or vice versa, Dirigible don't take it as a rename and leaves the name unchanged.

**To Reproduce**
1. Try changing lower case letter to upper or upper to lower
2. Observe no change

**Expected behavior**
An actual rename to be performed.

**Comment by delchev** [comment]
Did you try this with a local (file system based) Repository on Windows?

**Comment by malkoto1** [comment]
> 
> 
> Did you try this with a local (file system based) Repository on Windows?

This is the exact situation.

**Comment by delchev** [comment]
Windows NTFS file system is case insensitive by default. It seems they added a flag to enable case sensitivity as described here:
https://www.howtogeek.com/354220/how-to-enable-case-sensitive-folders-on-windows-10/
It is interesting whether this can be handled via a Java API as well?
