### ISSUE TITLE
Fat JAR Missing

### ISSUE THREAD

**Issue by malkoto1** [eclipse/dirigible#498]
Hi, guys, 

As I see there is no more fat JAR provided. As we are using the Dirigible for local development this is kind of problem for us. The fat jar allows us to easily setup a new colleague's machine to be ready for work.

Also if we have a fat JAR, we do not need to setp servers on our machines in addition.

**Comment by delchev** [comment]
Hi,
There are security issues reported for the comparatively old version of Tomcat modules used for building the executable jar file with Maven. We didn't find alternative and replacement working with the most recent version. If you can suggest, it will be great!
An option is also to use one of the Docker packages described here: https://www.dirigible.io/help/setup_docker.html
Does it work for you?

**Comment by ThuF** [comment]
Won't fix
