### ISSUE TITLE
The Xml2Json tests fail on linux because of different line endings

### ISSUE THREAD

**Issue by SvetlinZarev** [eclipse/dirigible#50]
The Xml2Json tests fail on linux because of different line endings - the "expected" files are using CLRF endings, but the xml2json conversion is using the platform line endings. As a result the tests fail on linux

**Comment by delchev** [comment]
Fixed with:
https://github.com/eclipse/dirigible/commit/9869d23812e9c9435a4f33065e8a86477b9540c1
