### ISSUE TITLE
Generate openui5 app from edm file

### ISSUE THREAD

**Issue by Demonium** [eclipse/dirigible#519]
Hi,
I try to generate openui5 fullstack app from edm file but controller folder is not generated.
I used the edm model from the samples 
https://raw.githubusercontent.com/dirigiblelabs/sample-v3-car-service-bookings/master/car-service-bookings/car-service-bookings.edm
and for the view Navigation in views folder I have no controller folder for it.

Build on the latest source code of dirigible

**Comment by ThuF** [comment]
Hi Jonathan,

OpenUI5 templates are in experimental phase, actually we have two projects for adopting the OpenUI5 technology:
- [dirigiblelabs/template-application-openui5](https://github.com/dirigiblelabs/template-application-openui5/ ) - mixture between AngularJS based launchpad and OpenUI5 views
- [dirigiblelabs/template-application-openui5-v2](https://github.com/dirigiblelabs/template-application-openui5-v2) - OpenUI5 only

Unfortunately at this point only the AngularJS based template is fully supported: [dirigiblelabs/template-application-angular](https://github.com/dirigiblelabs/template-application-angular)

Actually we are quite open for contributions, so if you'd like to provide an application template with different technology (OpenUI5, React, Vue, ...) we'll be more than happy to help you there.

PS: To import new templates you can just clone them from the Git view and Publish them in the Workspace. After refresh, the new templates should be available in the dropdown.

Regards,
Yordan

**Comment by Demonium** [comment]
I'm SAP ABAP developper and SAPUI5 and would learn new language this is why I use dirigble so will be great if I can participate to an open source project for me!!
I will try to generate an template application for UI5 and let you inform

**Comment by ThuF** [comment]
Great, just let us know, if you face any issues or just need help :)

**Comment by Demonium** [comment]
Ok no problem thanks :)

**Comment by StanZGenchev** [comment]
We have decided that moving forward, we will use templates with SAP Fundamental-styles only and OpenUI5/SAPUI5 will not be officially supported.
