### ISSUE TITLE
no .model file generated when open .edm in orion

### ISSUE THREAD

**Issue by Demonium** [eclipse/dirigible#520]
**Describe the bug**
When opening a .edm in orion an save it, no .model file generated.
I have to open it on edm editor save it again to generate it

**To Reproduce**
1. create edm file
2. open with orion
3. paste content
4. save
5. refresh project

**Expected behavior**
.model file generated

**Screenshots**

**Comment by delchev** [comment]
It is interesting idea, thanks! So far we haven't thought that the "generation" of the *.model artefact could happen "modeller-less".
What I would propose is to enhance the extensibility of the generation feature itself.
How it would look like:

1. create an edm file
2. open with Orion editor (or any other text based editor available in you instance - Monaco, Ace,...)
3. save
4. right-click ot the edm file and choose "Generate"
5. the "Generation Dialog" appears with the corresponding templates matching your selection (*.edm)
6. click "Generate" button and the model file will appear in the e.g. same folder

The "save" in the EDM Modeller will still automatically call the same functionality, so no need of extra step to be performed in case one uses the modeller.

This approach will give us (once implemented) the flexibility to attach dynamically a generation templates to any specific file in the Workspace View via the standard extensibility mechanism (i.e. *.extension descriptors).

What do you think?

**Comment by delchev** [comment]
Another approach would be to provide extensibility for the "save" event of an artefact in the workspace, which can play a role of a "filter" post-processor.

**Comment by Demonium** [comment]
For my point of view: less action.
So yes when the file is saved and right click > generate to generate all the need could improve the use of dirigible

**Comment by delchev** [comment]
#524

**Comment by delchev** [comment]
#525

**Comment by delchev** [comment]
#533
