### ISSUE TITLE
adding proxy service to consume other data source like sap gateway

### ISSUE THREAD

**Issue by Demonium** [eclipse/dirigible#521]
**Describe the solution you'd like**
Adding a proxy service to consume sap gateway service from sample application by providing ip of the server id of the system instance number and user password or managing user throw an SSO service

**Comment by ThuF** [comment]
Hi Jonathan,

Do you mean here consumption of on-prem SAP Gateway Service from the SAP Cloud Platform (Neo/Cloud Foundry) through the Cloud Connector or something else? Can you give a bit more details?

Regards,
Yordan

**Comment by Demonium** [comment]
Hi Yordan,
The idea will be more for cibling on premise system.
We can imagine dirigible has portal that allow user to consume other systems as services so sap gateway can be one of them

**Comment by ThuF** [comment]
Do you mean something like the EDM Model -> Feed section?

You can see it by:
1. Create a new EDM file
1. Drag & Drop new Entity
1. Right click on the Entity and click on the Properties option
1. Select the Feed section

Or something like a OData/OpenAPI client for a specific system (generated from OData metadata), that you can consume afterwards?

**Comment by Demonium** [comment]
Hi Thuf,
much more the second option build from a specific system

**Comment by ThuF** [comment]
Hi Jonathan,

Thanks for the clarification, I've created two new issues to track the progress separately:
- https://github.com/eclipse/dirigible/issues/522: [Templates] Generate OData specific client from metadata
- https://github.com/eclipse/dirigible/issues/523: [Templates] Generate OpenAPI specific client from metadata

Do these issues represent correctly your proposal, so we can close this issue?

Regards,
Yordan

**Comment by Demonium** [comment]
yep!! and I think we can add the functionnalty to both to generate also the frontend , what do you think ?

**Comment by ThuF** [comment]
Sure, can you comment also in the new issues?

I'm closing this one.

https://github.com/eclipse/dirigible/issues/522
https://github.com/eclipse/dirigible/issues/523
