### ISSUE TITLE
Create file with space in the name returns http code 500

### ISSUE THREAD

**Issue by shturec** [eclipse/dirigible#54]
Request URL: <host>/services/v3/ide/workspaces/workspace1/project1/alabala/file%201
Request Method: POST
Accept: application/json, text/plain, */*
no body 

 [ERROR] Illegal character in path at index 32: workspace1/project1/alabala/file 1

The file gets created successfully though

**Comment by delchev** [comment]
Fixed with:
https://github.com/eclipse/dirigible/commit/8a5c9bc8b6c64f413d0c7125f716bf6aaeb39e56
