### ISSUE TITLE
[IDE] Git - Add File History Support

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#546]
Add support for single File History in the Git perspective.

The listed git repositories should have the following items, when expanded:
1. **Branches** (e.g. ``local``, ``remote``, ...)
1. **Working Tree** / **Content** / **Files** 

When expanded the **Working Tree** / **Content** / **Files**  section should list the project(s) and the files as in the Workspace view.

When item form the **Working Tree** / **Content** / **Files**  is selected the History view should be populated with the selected file/folder history.

**Comment by delchev** [comment]
Can we use the Workspace view with its `workspace.file.selected` event instead of to build the full tree in the Git view again?

**Comment by ThuF** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/bf56cd37a5fb76783c86d1f67d1e289379962acb
