### ISSUE TITLE
Create file - location response header is invalid

### ISSUE THREAD

**Issue by shturec** [eclipse/dirigible#57]
sample: http://localhost:8080/services/v3/workspace1/project1/alabala/file.js
it's missing the 'workspaces' segment
should be: http://localhost:8080/services/v3/workspaces/workspace1/project1/alabala/file.js

**Comment by delchev** [comment]
Fixed with:
https://github.com/eclipse/dirigible/commit/47bd4d6d60f05bda588121ee84c50807137ab450
