### ISSUE TITLE
[workspace rest api] add support for file/folder properties

### ISSUE THREAD

**Issue by shturec** [eclipse/dirigible#59]
To add a file/folders 'Properties' section to right-click context menu in IDE workspace we need a bit more info than location and media types.
Consult with different OS approach to it. Generally, it might be benefitial to add also size in bytes , UTC date/time created, UTC date/time last modified. 
In the longer run also maybe owner id, creator id, last modified by id, acl permissions...

**Comment by delchev** [comment]
Duplication of https://github.com/eclipse/dirigible/issues/37
