### ISSUE TITLE
[Doc] Update the Development & Operations section in the main documentation tree

### ISSUE THREAD

**Issue by danachkov** [eclipse/dirigible#604]
Add new bullets to the already existing ones (Web IDE, Views, etc.) in the Development & Operations section in the [main documentation tree](https://www.dirigible.io/help/):
- Editors
- Entity Data Modeler
- Database Schema Modeler
- BPMN Modeler
- Form Designer

Add short descriptions about the basic application of each feature, screenshots, and links for cross reference, if possible.

**Comment by slavipande** [comment]
Added a new bullet "Editors & Modelers" to the already existing ones (Web IDE, Views, Artifacts, Engines, Services) in the Development & Operations section.

- The bullet "Editors & Modelers" links to a web page entitled [Editors & Modelers](https://www.dirigible.io/help/editorsandmodelers.html). 
- The web page includes a list of editors and a list of modelers.
- Each bullet in the lists includes a short description and a link to a designated web page that includes more info and a screenshot of the corresponding editor/modeler.

**Comment by ThuF** [comment]
@danachkov, @slavipande thanks for providing these updates to the documentation.
Now we can consider this issue closed!
