### ISSUE TITLE
[Doc] Update the Features section

### ISSUE THREAD

**Issue by danachkov** [eclipse/dirigible#605]
Update the [Features](https://www.dirigible.io/help/features.html) section.

Add the following bullet to Integration Services:
-  Support for OData 2.0 (*.odata)

Add the following bullet to Modeling:
- Form Designer

Add links for cross reference, if possible.

**Comment by slavipande** [comment]
The Features section has been updated.

The following bullet has been added to Integration Services:

- Support for OData 2.0 (*.odata)

The following bullet has been added to Modeling:

- Form Designer

Links have been added throughout the entire Features section for cross reference between this page and other web pages referenced by the content.

**Comment by ThuF** [comment]
@danachkov, @slavipande thanks for providing these updates to the documentation.
Now we can consider this issue closed!
