### ISSUE TITLE
[UI Improvement] Move the Reset option to the Windows dropdown

### ISSUE THREAD

**Issue by danachkov** [eclipse/dirigible#630]
Moving the Reset option to the Windows dropdown on the top of the screen may be more intuitive and easier to find by users. Currently, this option is positioned along with the UI themes, which doesn't make much sense.

![reset](https://user-images.githubusercontent.com/20664881/95304115-cfd1aa00-088c-11eb-8f0c-ab6cc7fdc4ba.png)

**Comment by ThuF** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/9feec9153d1c5292dc59817f7897123f5cab60ee
