### ISSUE TITLE
[Feature request]: Enable uploading of more than one file at the same time

### ISSUE THREAD

**Issue by fifoosid** [eclipse/dirigible#642]
**Describe the bug**

When the user is wants to upload a file, currently only one file at a time can be uploaded.
I expect that users should be able to upload more than one file at a time.

**To Reproduce**
1. Right click on any folder
2. Click on Upload
3. Press Choose a file
4. Now the user should be able to select more than 1 file

**Comment by delchev** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/18056ebb4c4553c26d8a3638c78a741ba46fd5d1
