### ISSUE TITLE
[Core] Clean-up unused modules

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#656]
Schedule for deletion the unused Dirigible modules:
- Rhino JS engine
- V8 JS engine
- Nashorn JS engine
- Embedded-all releng
- etc.

**Comment by g051051** [comment]
Is there anything weird or tricky about this change?

**Comment by ThuF** [comment]
I don't think so, they could be removed right away.

**Comment by ThuF** [comment]
Fixed with: https://github.com/eclipse/dirigible/pull/661

Archive branch (including the deleted modules) created: https://github.com/eclipse/dirigible/tree/archive-2020-11-28
