### ISSUE TITLE
[IDE] OTS parsing error: Failed to convert WOFF 2.0 font to SFNT

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#663]
As noticed by @g051051, it seems that there are `OTS parsing errors` reported in the browser console, as warnings.

![error](https://user-images.githubusercontent.com/2124974/100544078-4baef980-3221-11eb-8e6e-3fa1eebea151.png)

According to https://stackoverflow.com/questions/55868995/ots-parsing-error-failed-to-convert-woff-2-0-font-to-sfnt-for-font-files-of-gly, it seems like an issue in the maven build process.

The proposed solution is:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-resources-plugin</artifactId>
    <configuration>
        <nonFilteredFileExtensions>
            <nonFilteredFileExtension>ttf</nonFilteredFileExtension>
            <nonFilteredFileExtension>woff</nonFilteredFileExtension>
            <nonFilteredFileExtension>woff2</nonFilteredFileExtension>
            <nonFilteredFileExtension>eot</nonFilteredFileExtension>
            <nonFilteredFileExtension>svg</nonFilteredFileExtension>
        </nonFilteredFileExtensions>
    </configuration>
</plugin>
```

**Comment by ThuF** [comment]
Related to: https://github.com/eclipse/dirigible/issues/491

**Comment by ThuF** [comment]
@g051051:
> I did try that, but it didn't work. I'm not familiar enough with the project to know the right place to put that. In addition, I tried extracting the font file from the packed jars and comparing them against the original file in the project, and it showed them as the same, so it might be that the font is corrupted before it's packaged.

**Comment by ThuF** [comment]
I guess that the right place of these resources is in the [resources](https://github.com/eclipse/dirigible/tree/master/resources) module.

Most probably, as you guessed they've already been corrupted beforehand.

**Comment by g051051** [comment]
I did a few more experiments, and it looks like the file is valid.  Perhaps it's being served up with the wrong mime type?

**Comment by ThuF** [comment]
The [ContentTypeHelper](https://github.com/eclipse/dirigible/blob/ed4a0d0f28eec8f9715c9be2d342d5c5b920390b/modules/commons/commons-api/src/main/java/org/eclipse/dirigible/commons/api/helpers/ContentTypeHelper.java) is supposed to set the right mime types, but there could be some issues?

**Comment by g051051** [comment]
ContentTypeHelper doesn't have an entry for "woff2".  Per https://www.w3.org/TR/WOFF2/#IMT, it should be:

	public static final String APPLICATION_FONT_WOFF2 = "font/woff2";

I just tested this and it works!  I'll raise a PR.

**Comment by ThuF** [comment]
Thanks I’ve just merged the PR. As this is fixed, can we close the issue?

**Comment by g051051** [comment]
I don't see the problem anymore, so as far as I'm concerned I don't see a reason to keep it open.

**Comment by ThuF** [comment]
Okay, then we’ll consider it closed. @g051051 thanks a lot for the contributions so far! 🙏
