### ISSUE TITLE
[API] Add client API for etcd

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#675]
Introduce new client API for the `etcd` key value store, based on the official Java implementation - [jetcd](https://github.com/etcd-io/jetcd):

Module Identifier: etcd/client
Module Source: https://github.com/dirigiblelabs/ext-etcd/blob/master/etcd/client.js
Module Mirror: https://github.com/eclipse/dirigible/blob/master/ext/ext-modules/ext-etcd/src/main/resources/etcd/client.js
Facade Source: https://github.com/eclipse/dirigible/blob/master/api/api-facade/api-etcd/src/main/java/org/eclipse/dirigible/api/mongodb/EtcdFacade.java
Documentation: http://www.dirigible.io/api/etcd_client.html
Samples: https://www.dirigible.io/samples/simple_etcd.html
Tests: ~~https://github.com/eclipse/dirigible/tree/master/api/api-facades/api-tests/src/main/resources/etcd/client.js~~

**Comment by delchev** [comment]
API project:
https://github.com/dirigiblelabs/ext-etcd/tree/master/etcd

Facade:
https://github.com/eclipse/dirigible/tree/master/api/api-facade/api-etcd

API Sync:
https://github.com/eclipse/dirigible/tree/master/ext/ext-modules/ext-etcd
