### ISSUE TITLE
dirigible-template-database-table generates invalid .table file from template

### ISSUE THREAD

**Issue by g051051** [eclipse/dirigible#681]
**Describe the bug**
The .table file created from the dirigible-template-database-table project is invalid, due to using single quotes instead of double quotes.

**To Reproduce**
1. Go to 'Welcome Page'
2. Click on 'template-database-table/template.js'
3. Fill in required fields and click "Generate".
4. Open the resulting file in the table editor.
5. The file is corrupt...the Table Description just says {{file}}, and the file can't be edited.
6. Close the file, then reopen in the Monaco editor.  The editor will highlight each field and show an error "Property keys must be doublequoted".

**Expected behavior**
The file opens correctly in the table editor and is editable.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.88

**Additional context**
Manually editing the resulting file to replace the single quotes with double quotes fixes the error and allows the file to be edited correctly.

**Comment by ThuF** [comment]
@g051051 Thank you for creating this issue and submitting a PR fix it!

Would you be so kind to apply the same fix with a PR at [dirigiblelabs/template-database-table](https://github.com/dirigiblelabs/template-database-table), as this is the repo from where the database template file is being pulled and replaced in the main repo during the `content` build phase - `mvn clean install -P content`.

You can find all `templates` related DirigibleLabs git repositories [here](https://github.com/search?p=1&q=topic%3Atemplates+org%3Adirigiblelabs&type=Repositories). The intent for all these projects/repositories is simple - speed of development. All of them could be cloned inside Dirigible as projects, being developed, and the changes being applied on the fly (In-System Development), then submitted back to DirigibleLabs and pulled as content during the `content` build phase of the main repository.

Other such modules are:
- [API](https://github.com/dirigiblelabs?q=api&type=&language=) - the JavaScript [API](https://www.dirigible.io/api/)
- [IDE](https://github.com/dirigiblelabs?q=ide&type=&language=) - the Dirigible's Web IDE plugins (e.g. Console, Preview, Git, etc.)
- [Resources](https://github.com/dirigiblelabs?q=resources&type=&language=)

**Comment by ThuF** [comment]
Fixed also at [dirigiblelabs/template-database-table](https://github.com/dirigiblelabs/template-database-table/issues/1) repo.
