### ISSUE TITLE
[IDE] Unable to import GitHub project from the Git view to my workspace

### ISSUE THREAD

**Issue by danachkov** [eclipse/dirigible#684]
I'm trying to import a GitHub project from the Git view with a locally installed Dirigible IDE instance (version 5.6.0) on Windows 10 using Tomcat 8.5:

![import-project-issue](https://user-images.githubusercontent.com/20664881/104199607-4f44bb80-5430-11eb-8f58-a88cc8919df1.png)

The following error message pops up:

[2021-01-11T14:32:38.235Z] [ERROR] java.nio.file.FileSystemException: C:\Program Files\Apache Software Foundation\Tomcat 8.5\target\dirigible\repository\root\users\...\workspace\my-first-project: A required privilege is not held by the client

I tried to restart Tomcat and run it as an administrator, but this action didn't solve the issue.

I managed to successfully import the project using the Trial version of the Dirigible Web IDE.

**Comment by ThuF** [comment]
Hi @danachkov, thanks for submitting this issue!

It seems like an issue with the Windows OS ...

As a possible workaround, could you try to run Dirigible locally from a Docker image as described here: https://www.dirigible.io/help/setup_docker.html

**Comment by danachkov** [comment]
Hi @ThuF! I ran the Dirigible Web IDE using Docker and I managed to import the project without a problem. On a separate note, I had some issues installing Docker on Windows 10, but I finally managed to get it going with the following Docker release: https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2101

**Comment by ThuF** [comment]
Hi @danachkov, thanks that's great!

How about describing the workaround as part of the local setup?
Something like: _**"There are certain functional limitations that could be experienced, while running on Windows OS. In these cases, running it with Docker is preferred."**_

Could you please update the documentation with such message/warning and then we could close this issue as "won't fix"?

**Comment by danachkov** [comment]
I'm not sure if that's the right place, but I added a section about the setup on Windows at https://www.dirigible.io/help/setup_tomcat.html.

**Comment by ThuF** [comment]
That's perfect, thanks @danachkov!
I'm closing this issue as **won't fix** as there is workaround for the Windows users.
