### ISSUE TITLE
[Documentation] Improve content in section Resource paths and path templates of the REST page

### ISSUE THREAD

**Issue by slavipande** [eclipse/dirigible#686]
During our last sync, we discussed that the text in section Resource paths and path templates of the [REST](https://www.dirigible.io/help/concepts_rest.html) page is not clear enough and should be improved.

Hence, I'm adding this issue as a reminder for this task.

**Comment by ThuF** [comment]
@slavipande can you confirm that the section description is now improved?

https://www.dirigible.io/help/development/concepts/rest/#resource-paths-and-path-templates

**Comment by slavipande** [comment]
With apologies for the delay, I went over the changes in the mentioned section. Looks OK to me. 

Closing the issue. :)

Best regards,
Svetoslav
