### ISSUE TITLE
[Epic][Doc] Redesign the help portal

### ISSUE THREAD

**Issue by slavipande** [eclipse/dirigible#687]
Redesign and improve the [help portal](https://www.dirigible.io/help/).

- Improve the homepage of the help portal because the current one just repeats the content structure in the sidebar.
- Look at [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/) as a possible replacement for the current Jekyll theme.
- Description to be enhanced as the discussion evolves.

**Comment by ThuF** [comment]
Updated:
- https://www.dirigible.io/api/
- https://www.dirigible.io/help/
- https://www.dirigible.io/samples/
