### ISSUE TITLE
[UI Improvement] Unify icons and file menu entries in the Workbench perspective

### ISSUE THREAD

**Issue by slavipande** [eclipse/dirigible#701]
**Description**
The options in the File menu are different than the options provided by the buttons (New, Publish All, etc.). They are also ordered differently.

**To Reproduce**
1. Go to 'Workbench perspective'
2. Click on 'File'
3. Compare options in the File menu with the buttons in the workspace.

**Expected behavior**
The options in the File menu are unified with the options provided by the buttons (New, Publish All, etc.). They are also ordered in the same way.

**Screenshots**
<img width="360" alt="2021-01-22_18-15-20" src="https://user-images.githubusercontent.com/46915717/106450081-643fc800-648d-11eb-9013-af9acaf768ac.png">

<img width="319" alt="2021-01-22_18-16-27" src="https://user-images.githubusercontent.com/46915717/106450362-c3054180-648d-11eb-9661-dcb958958237.png">

**Desktop:**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 88.0.705.56 (Official build) (64-bit)

**Comment by ThuF** [comment]
Font Awesome 5 icons to be considered as well: https://fontawesome.com/icons?d=gallery&m=free

> _**[Font Awesome CDN](https://cdnjs.com/libraries/font-awesome):** https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css_

**Comment by ThuF** [comment]
Related to: https://github.com/eclipse/dirigible/issues/702

**Comment by ThuF** [comment]
Partially fixed with: https://github.com/eclipse/dirigible/commit/b6fd286a642bfa71dcc83b6bab7a82666c2bf7ba
