### ISSUE TITLE
[UI Improvement] Change the icon for cloning a repo in the 'Git' perspective

### ISSUE THREAD

**Issue by slavipande** [eclipse/dirigible#706]
**Description**
The 'plus' icon does not create anything new. It clones something that exists. 

**To Reproduce**
1. Go to 'Git' perspective
2. Click on 'Clone Project' (the 'plus' icon)
3. A dialog 'Clone Project' is opened

**Expected behavior**
The icon on the button "Clone Project" should complement the functionality of the button. Here's a Font Awesome icon that would better suit the functionality of this button: https://fontawesome.com/v4.7.0/icon/clone 

**Screenshots**
![2021-02-01_14-45-59](https://user-images.githubusercontent.com/46915717/106461365-57c36b80-649d-11eb-8713-a9b2a7b8bf6d.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 88.0.705.56 (Official build) (64-bit)

**Comment by ThuF** [comment]
Font Awesome 5 icons to be considered as well: https://fontawesome.com/icons?d=gallery&m=free

> _**[Font Awesome CDN](https://cdnjs.com/libraries/font-awesome):** https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css_
