### ISSUE TITLE
[UI Improvement] Alternative icons for the 'Workbench' perspective

### ISSUE THREAD

**Issue by slavipande** [eclipse/dirigible#710]
**Description**
The icon for "Publish All" is OK but an alternative could be considered.
The icon for "Export All" should be changed because it is also used in the 'Git' perspective for a different action. 

**To Reproduce**
1. Go to 'Workbench' perspective
2. See icons 'Publish All' and 'Export All'

**Expected behavior**
Although the icon for "Publish All" is OK, here's an alternative to be considered: https://fontawesome.com/v4.7.0/icon/newspaper-o 
Clicking "Export All" downloads an archive. Hence, here's a better icon for this button: https://fontawesome.com/v4.7.0/icon/file-archive-o 

**Screenshots**
![2021-02-02_12-13-17](https://user-images.githubusercontent.com/46915717/106585925-88181200-6550-11eb-9953-b3d3c993d0ba.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 88.0.705.56 (Official build) (64-bit)

**Comment by ThuF** [comment]
Font Awesome 5 icons to be considered as well: https://fontawesome.com/icons?d=gallery&m=free

> _**[Font Awesome CDN](https://cdnjs.com/libraries/font-awesome):** https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css_

**Comment by ThuF** [comment]
Updated only the `Export` icon, as the `Publish` one is good enough for now.
