### ISSUE TITLE
[UI Improvement] Change label of 'Access' tab in the 'Documents' perspective

### ISSUE THREAD

**Issue by slavipande** [eclipse/dirigible#711]
**Description**
The label of the 'Access' tab is not descriptive enough and can be improved.

**To Reproduce**
1. Go to 'Documents' perspective
2. Click on 'Access' tab.
3. Review tab contents.

**Expected behavior**
The label of the tab should better describe the functionality in the tab. Suggestion: change the label 'Access' to 'Constraints'. This way there will be two tabs - 'Documents' and 'Constraints' which when read together would suggest that one of the tabs is for documents and the other for creating constraints about the documents.

**Screenshots**
![2021-02-02_15-21-33](https://user-images.githubusercontent.com/46915717/106606281-9d9a3580-656a-11eb-8174-da26ab6d8841.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 88.0.705.56 (Official build) (64-bit)

**Comment by ThuF** [comment]
Related to: https://github.com/eclipse/dirigible/issues/712
