### ISSUE TITLE
[UI Improvement] Enhance page title in the 'Access' tab of the 'Documents' perspective to provide more context

### ISSUE THREAD

**Issue by slavipande** [eclipse/dirigible#712]
**Description**
In the tab 'Access', there’s a piece of text that looks out of place: Access Description: Documents. 

**To Reproduce**
1. Go to 'Documents' perspective
2. Click on 'Access' tab
3. Review page title

**Expected behavior**
The page title should provide more details on what constraints do. Hence, here's a suggestion how to change it:
'Create constraints to restrict access to documents based on user roles'. 

**Screenshots**
<img width="905" alt="2021-01-22_19-03-48" src="https://user-images.githubusercontent.com/46915717/106606905-56f90b00-656b-11eb-8e8f-e7b91991d863.png">

**Desktop:**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 88.0.705.56 (Official build) (64-bit)

**Comment by ThuF** [comment]
Related to: https://github.com/eclipse/dirigible/issues/711

**Comment by ThuF** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/6edc73f5b8c387a398253616991369946e804be1
