### ISSUE TITLE
[UI Improvement] The turn on/off icon next to the username doesn't work as expected

### ISSUE THREAD

**Issue by slavipande** [eclipse/dirigible#715]
**Description**
When I click on the turn on/off icon next to my user, I'm not signed out but instead I am returned to the default perspective which is the workbench perspective. 

**To Reproduce**
1. Click on the turn on/off button in the top right corner of the screen.

**Expected behavior**
This button should lead to a log off page instead of auto log in.

**Screenshots**
<img width="958" alt="2021-01-22_19-10-43" src="https://user-images.githubusercontent.com/46915717/106612231-8ca0f280-6571-11eb-9b08-6ce5f7deb55a.png">

**Desktop:**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 88.0.705.56 (Official build) (64-bit)

**Comment by ThuF** [comment]
Progress to be tracked here: https://github.com/eclipse/dirigible/issues/730
