### ISSUE TITLE
[UI Improvement] Unable to create constraints on Trial

### ISSUE THREAD

**Issue by danachkov** [eclipse/dirigible#719]
In the Documents perspective, the **+** button for creating constraints is not responsive. When clicking this button, nothing happens. In general, a user on Trial shouldn't be able to create such constraints. We need to make sure that a message pops up explaining that this option cannot be used here on Trial.

![Cannot_create_constraints_improve-UI-text](https://user-images.githubusercontent.com/20664881/106714282-49dc2a80-6604-11eb-98fc-d58824ae864c.png)

**Comment by delchev** [comment]
obsolete
