### ISSUE TITLE
[API] Provide API for Apache Cassandra with Datastax driver

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#721]
Provide API for Apache Cassandra with Datastax driver:

https://github.com/datastax/java-driver

Similar like what is done for MongoDB:
https://github.com/eclipse/dirigible/tree/master/api/api-facade/api-mongodb
https://github.com/eclipse/dirigible/tree/master/ext/ext-modules/ext-mongodb

**Comment by delchev** [comment]
API project:
https://github.com/dirigiblelabs/ext-cassandra/tree/master/cassandra

Facade:
https://github.com/eclipse/dirigible/tree/master/api/api-facade/api-cassandra

API Sync:
https://github.com/eclipse/dirigible/tree/master/ext/ext-modules/ext-cassandra

**Comment by ThuF** [comment]
Fixed with: https://github.com/eclipse/dirigible/pull/896
