### ISSUE TITLE
[IDE] Font Awesome Version 5.x

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#731]
Upgrade to the Font Awesome version 5.x.

Free icons: https://fontawesome.com/icons?d=gallery&m=free

> _**Note:** Follow the upgrade instructions here: [Upgrading from Version 4
](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4)_

> _**[Font Awesome CDN](https://cdnjs.com/libraries/font-awesome):** https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css_

**Comment by ThuF** [comment]
Related to:
- https://github.com/eclipse/dirigible/issues/701
- https://github.com/eclipse/dirigible/issues/703
- https://github.com/eclipse/dirigible/issues/706
- https://github.com/eclipse/dirigible/issues/710

**Comment by StanZGenchev** [comment]
Closing this issue as it's no longer relevant. See issue #1680
