### ISSUE TITLE
[Documentation] Describe Debugger View better

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#732]
https://www.dirigible.io/help/development/ide/views/debugger/

Update the screenshot with light theme

**Comment by slavipande** [comment]
Updated debugger.md. Please check and close the issue if the desc is okay :)

**Comment by ThuF** [comment]
It's perfect, thanks @slavipande!

Page:
- https://www.dirigible.io/help/development/ide/views/debugger/
