### ISSUE TITLE
[CI/CD] Helm chart for full-fletched provisioning in kubernetes cluster

### ISSUE THREAD

**Issue by okimuri369** [eclipse/dirigible#733]
Every new release is coming with some changes. As a result of them, it is always a frustration to assemble and tuneup a project into an operational installation.

An up-to-date Helm chart that installs full-fletched kubernetes cluster with Dirigible that is ready to use would be of a great help and will bring a sense of a product. The basic idea is to provision a kubernetes cluster with Dirigible (design-time + runtime), KeyCloak, a PostgreSQL server (for the KeyCloak and possibly for the Dirigible instance).

**Comment by ThuF** [comment]
Related to:
- https://github.com/eclipse/dirigible/issues/564
- https://github.com/eclipse/dirigible/issues/279

**Comment by ThuF** [comment]
Usage:

1. Add the Eclipse Dirigible Helm repository:
    ```
    helm repo add dirigible https://eclipse.github.io/dirigible
    helm repo update
    ```
1. Basic deployment:
    ```
    helm install dirigible dirigible/dirigible
    ```
    > _**Note:** This will install Eclipse Dirigible **Deployment** and **Service** with **ClusterIP** only._

    To access the Dirigible instance execute the command that was printed in the console, similar to this one:
    ```
    export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=dirigible,app.kubernetes.io/instance=dirigible" -o jsonpath="{.items[0].metadata.name}")
    echo "Visit http://127.0.0.1:8080 to use your application"
    kubectl --namespace default port-forward $POD_NAME 8080:8080    
    ```
    Navigate to: [http://127.0.0.1:8080](http://127.0.0.1:8080)
    Login with: `dirigible`/`dirigible`

1. Kyma deployment:
    1.  Basic:
        ```
        helm install dirigible dirigible/dirigible \
        --set kyma.enabled=true \
        --set kyma.apirule.host=<kyma-host>
        ```
        > _**Note:** This will install additionally an **ApiRule** and **XSUAA** **ServiceInstance** and **ServiceBinding**. The appropriate roles should be assigned to the user._

    1.  Basic with PostgreSQL:
        ```
        helm install dirigible dirigible/dirigible \
        --set kyma.enabled=true \
        --set kyma.apirule.host=<kyma-host> \
        --set database.enabled=true
        ```
        > _**Note:** This will install also **PostgreSQL** database with **1Gi** storage and update the Dirigible datasource configuration to consume the database._

    1.  Basic with PostgreSQL and Keycloak:
        ```
        helm install dirigible dirigible/dirigible \
        --set kyma.enabled=true \
        --set kyma.apirule.host=<kyma-host> \
        --set database.enabled=true \
        --set keycloak.enabled=true \
        --set keycloak.install=true
        ```
        > _**Note:** In addition **Keycloak** will be deployed and configured._

**Comment by ThuF** [comment]
Artifact Hub packages can be found [here](https://artifacthub.io/packages/search?page=1&org=dirigiblelabs).

**Comment by ThuF** [comment]
Detailed documentation and steps can be found here: https://www.dirigible.io/help/setup/helm/

You can checkout the `PostgreSQL & Keycloak` tab for `Kubernetes` or `Kyma`.
