### ISSUE TITLE
[UI Improvement] Make the list of views context-aware. 

### ISSUE THREAD

**Issue by slavipande** [eclipse/dirigible#759]
In the current state of the UI, the user can open the list of views Window --> Show view and see all the views, regardless of which perspective they have opened.

However, there are certain views that are only meaningful for one perspective. 
Example1: Debugger view and Debug Preview view are only relevant when the user has the Debugger perspective opened. 
Example2: History view and Staging view are only relevant when the user has the Git perspective opened.

Hence, it would be good if the options available for selection in the list of views Window --> Show view depend on the perspective that the user has currently opened.

**Comment by delchev** [comment]
Views are not tightly bound to a Perspective in general. You can use only one Perspective with all the Views you want, based on your personalised requirement. To limit this feature for the developers is not good idea.
