### ISSUE TITLE
[API] Database - invalid encapsulating of entity name

### ISSUE THREAD

**Issue by antoanetamh** [eclipse/dirigible#770]
**Describe the bug**
AbstractSqlBuilder.encapsulateMany() method do not take into account that the name of an artifact can be represented as
namespace::artifactName

**To Reproduce**

SqlFactory.getNative(connection).create().synonym("SchemaName.namepsace::MySynonym).forSource().build("SchemaName.namepsace::SourceName");

2. The resulting assembled SQL is in invalid format: 
CREATE SYNONYM "SchemaName"."namepsace"::"MySynonym" FOR "SchemaName"."namepsace"::"SourceName";

**Expected behavior**
The expected assembled SQL should be in valid format: 
CREATE SYNONYM "SchemaName"."namepsace::Mysinonym" FOR "SchemaName"."kneo.namepsace.db::SourceName"

**Comment by ThuF** [comment]
Fixed with: https://github.com/eclipse/dirigible/pull/771
