### ISSUE TITLE
[Documentation] Update the term SAP Cloud Platform

### ISSUE THREAD

**Issue by danachkov** [eclipse/dirigible#776]
The term SAP Cloud Platform needs to be updated and changed to SAP Business Technology Platform (BTP). We can leave a mention as a note or a clarification in the footer of one of the main pages in the Eclipse Dirigible documentation what used to be the previous name of the platform - in this case, SAP Cloud Platform.

For more information, check the [SAP BTP product page on SAP Help Portal](https://help.sap.com/viewer/product/BTP/Cloud/en-US).

**Comment by danachkov** [comment]
I found only two topics in the documentation that mention SAP Cloud Platform:

- https://www.dirigible.io/help/setup/cloud-foundry/

- https://www.dirigible.io/help/setup/kyma/

I hope I'm not missing something, but the necessary changes are applied and I think that we can close the issue.

**Comment by ThuF** [comment]
Thanks @danachkov, I'm going to close it now as **fixed**.
