### ISSUE TITLE
[Documentation] Improve visual consistency of the help portal content

### ISSUE THREAD

**Issue by danachkov** [eclipse/dirigible#783]
1. There are instances where notes are formatted not according to the general markdown principles:

![note_in_grey](https://user-images.githubusercontent.com/20664881/112662235-2002ef80-8e60-11eb-8af6-96cc84f5ed66.png)

This is how a note is usually visualized:

![notes_standard_formatting](https://user-images.githubusercontent.com/20664881/112662331-3ad56400-8e60-11eb-88f2-c37ba86e7113.png)

Ideally, we should have one way of visualizing the note element. I prefer the standard formatting shown in the second screenshot.

2. In some places, it doesn't make sense to visualize a sentence as a note, because there isn't any other text around it. In addition, avoiding the frequent use of notes will improve the readability of the documentation.

For example, this topic was recently updated and some of the note titles have been removed in steps 3, 4, and 5: https://www.dirigible.io/help/setup/cloud-foundry/. The highlighted text used to be a note, but now it's a standard sentence:

![ex-note](https://user-images.githubusercontent.com/20664881/112663252-45dcc400-8e61-11eb-9a69-a202ff6c5169.png)

**Comment by slavipande** [comment]
I'd also add that we should try and use consistent formatting when mentioning UI elements (buttons, tab names, field names, view names, perspective names, etc.) in the documentation. The same is also valid for inline code and user input.

Here are my suggestions (based on the [tutorial navigator style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9#mcetoc_1dtvf3pb64) and on the official [SAP style guide](https://help.sap.com/viewer/DRAFT/e33c591ae4494a659a3f5f983c9d1161/PROD/en-US/7941df56713846efa150a21e7ef3ecc9.html)):

- [ ] **Bold Text** - Use for UI elements
- [ ] **`Monospace/bold text`** - Use for user input
- [ ] `Monospace text` - Use for inline code or file/folder names

Let's add any other cases not covered by the above suggestions in separate comments below :) 

Best regards,
Svetoslav

**Comment by ThuF** [comment]
@slavipande, @n-boshnakov Congratulations for the excellent work!

Do we know, if there are more places where such alignment should be applied, or it's already applied everywhere?

**Comment by slavipande** [comment]
@ThuF , we've scheduled a meeting for tomorrow between me, Niki, and Drago so we can discuss the matter in detail. More changes will have to be made, so I suggest we leave the issue open for now :)

**Comment by ThuF** [comment]
Changes were applied and a **Style Guide** as part of the **Contributor Guide** was created: https://www.dirigible.io/help/community/
