### ISSUE TITLE
[IDE] Monaco - Code completion suggestion not triggered by dot operator

### ISSUE THREAD

**Issue by dspenchev** [eclipse/dirigible#790]
**Is your feature request related to a problem? Please describe.**
Coming from more popular IDEs like VS Code I was surprised to see different trigger conditions of the code completion when applying the dot operator on an object to see its methods/members.  Also as a macOS user, the short key for code completion is inconvenient (Cnt + Space), which is why this feature would be also requested by users like me.

**Describe the solution you'd like**
The dot operator, applied on an object, should trigger the code suggestion logic.

**Additional context**
Currently the code completion suggestion is not triggered by applying the dot operator on the object
<img width="666" alt="Screenshot 2021-04-02 at 17 53 12" src="https://user-images.githubusercontent.com/81425054/113426841-b2653f00-93dc-11eb-8b7e-286c374190dd.png">

Here is how it is expected to work
![intellisense_icons](https://user-images.githubusercontent.com/81425054/113428106-da55a200-93de-11eb-8e03-31cb770c4a61.png)

**Comment by ThuF** [comment]
Now the code completion is triggered, by pressing the `.`:
![Screenshot 2021-04-02 at 20 01 43](https://user-images.githubusercontent.com/4092083/113436902-44297800-93ee-11eb-82c4-37428e780497.png)

**Comment by ThuF** [comment]
Also the`require(...)` code completion is automatically triggered, by pressing `"` or `'`:
![Screenshot 2021-04-02 at 20 08 29](https://user-images.githubusercontent.com/4092083/113437456-49d38d80-93ef-11eb-8bce-c7cd82493caf.png)
