### ISSUE TITLE
[Documentation] IDE - Adding shortcut information

### ISSUE THREAD

**Issue by dspenchev** [eclipse/dirigible#792]
**Is your feature request related to a problem? Please describe.**
There is information neither in dirgible.io (Documentation section) nor in Dirigible IDE about the shortcut bindings for specific actions. 

**Describe the solution you'd like**
Add information about the default Dirigible IDE shortcut bindings both in Dirigible IDE and in dirigble.io (Documentation section)

**Comment by ThuF** [comment]
Related to:
- https://github.com/eclipse/dirigible/issues/790
- https://github.com/eclipse/dirigible/issues/791

**Comment by slavipande** [comment]
Here are some shortcut bindings to be described in a separate page in the Help:
 - CTRL + S (CMD + S for Mac) = Save and Publish
 - ALT + W (Opt + W for Mac) = Close active editor
 - ALT + Shift + W (Opt + Shift + W) = Close all opened editors
 - CTRL + Shift + F = Opens Search view
 - F1 - opens command palette (add screenshot)

**Comment by slavipande** [comment]
Abovementioned shortcut bindings are described in the Help. Here's a link to the page: [Keyboard Shortcuts](https://www.dirigible.io/help/tips-%26-tricks/keyboard-shortcuts/).
Related commits:
- https://github.com/dirigible-io/dirigible-io.github.io/commit/441648e61860e45c66fbbc861899e94b2b1ff096
- https://github.com/dirigible-io/dirigible-io.github.io/commit/9298075154debe3e354e8f43bb8ae3685b2b6219

Best regards,
Svetoslav
