### ISSUE TITLE
API link is broken in docs

### ISSUE THREAD

**Issue by ageorgievg** [eclipse/dirigible#795]
**Describe the bug**
API link is broken in documentation.

**To Reproduce**
Go here - https://www.dirigible.io/samples/print-env/
Try to click on API link at the bottom.
It gives 404.

**Comment by ThuF** [comment]
Thanks @ageorgievg !

All samples pages had the same issue ..

Fixed with: https://github.com/dirigible-io/dirigible-io.github.io/commit/df3a16a63af5c2e7ba3bb3188e8cf1b6748e537b
