### ISSUE TITLE
DAO API v3

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#84]
DAO API v3 implementation based on the new [guidelines](https://github.com/eclipse/dirigible/wiki/api-v3-guidelines).

Module Identifier: **db/v3/dao**
Module Source: https://github.com/dirigiblelabs/api-v3-db/blob/master/db/v3/dao.js
Module Mirror: https://github.com/eclipse/dirigible/blob/master/api/api-javascript/api-db/src/main/resources/db/v3/dao.js
Facade Source: none
Documentation: http://www.dirigible.io/api/database_dao.html
Samples: 
Tests:

**Comment by shturec** [comment]
provided with commit [dd0f877a0e5bf4c97a2982b95c055fa3984deccb](https://github.com/eclipse/dirigible/commit/dd0f877a0e5bf4c97a2982b95c055fa3984deccb)
