### ISSUE TITLE
Http RS API v3

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#85]
HTTP RS API v3 implementation based on the new [guidelines](https://github.com/eclipse/dirigible/wiki/api-v3-guidelines).

Module Identifier: **http/v3/rs**
Module Source: https://github.com/dirigiblelabs/api-v3-http/blob/master/http/v3/rs.js
Module Mirror: https://github.com/eclipse/dirigible/blob/master/api/api-javascript/api-http/src/main/resources/http/v3/rs.js
Facade Source: none
Documentation: http://www.dirigible.io/api/http_rs.html
Samples: 
Tests:

**Comment by shturec** [comment]
Provisioned with commit [1dd685f6f169b52715f599a59ae310421bb6b1f2](https://github.com/eclipse/dirigible/commit/1dd685f6f169b52715f599a59ae310421bb6b1f2).

Tests, samples and docs are pending
