### ISSUE TITLE
[Documentation] Unify footers in the Help portal, the API page, and the Samples page

### ISSUE THREAD

**Issue by slavipande** [eclipse/dirigible#853]
**Describe the bug**
The footers of the [API](https://www.dirigible.io/api/) page and the [Samples](https://www.dirigible.io/samples/) page are different from the footer of the [Help](https://www.dirigible.io/help/) portal.

**To Reproduce**
1. Go to the [API](https://www.dirigible.io/api/) page, the [Samples](https://www.dirigible.io/samples/) page, and the [Help](https://www.dirigible.io/help/) portal.
2. Compare footers

**Expected behavior**
The footers should be unified.

**Screenshots**
Not needed

**Comment by slavipande** [comment]
Fixed with https://github.com/dirigible-io/dirigible-io.github.io/commit/593070d421d8505c116140dfbcedc291869028f6

The footers of all pages are now identical and look like this:
![2021-05-18_15-34-59](https://user-images.githubusercontent.com/46915717/118651893-ac8db680-b7ee-11eb-807c-2e4b1e016bee.png)

Hence, I'll be closing this issue.

Best regards,
Svetoslav

**Comment by ThuF** [comment]
Thanks @slavipande!
