### ISSUE TITLE
[IDE Workspace] When file is deleted from workspace it still appear in editor

### ISSUE THREAD

**Issue by antoanetamh** [eclipse/dirigible#854]
Describe the bug
When file is deleted from workspace it still appear in editor

Steps to reproduce:
1. Create some file
2. Open the file for editing
2. Delete the file using context menu->delete
3. The file in Editor still exist and changes can be saved.

![image](https://user-images.githubusercontent.com/44926767/116091916-fd0d6a80-a6ad-11eb-8f15-f17735b400b5.png)

**Comment by delchev** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/6e1e2c22fd173eedc48a5ba1b0c5ca720585b2a7
