### ISSUE TITLE
[Bindings] Update Hana Driver

### ISSUE THREAD

**Issue by ageorgievg** [eclipse/dirigible#857]
There seems to be a problem with the old driver regarding connecting to hana and it gives the following error -
`SQLException: SAP DBTech JDBC: Cannot connect to jdbc:sap://3a9e75da-23d1-456c-b58f-a12b0e647203.hana.trial-eu10.hanacloud.ondemand.com:443 [Receive of connect failed.].`

**Comment by ThuF** [comment]
Use the latest HANA Driver - e.g. `2.8.12`
