### ISSUE TITLE
[Database-sql] Composite Primary key is not supported

### ISSUE THREAD

**Issue by antoanetamh** [eclipse/dirigible#877]
If you try to create .table file with more than one Primary key, the assembled SQL is incorrect:

Generated SQL: `CREATE TABLE OFFERS ( id BIGINT  NOT NULL PRIMARY KEY , id2 BIGINT  NOT NULL PRIMARY KEY )`
ERROR: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [294]: cannot have more than one primary key: id2:

Example:
```
{
	"name": "ORDERS",
	"type": "TABLE",
	"columns":
		[
			{
				"name":"id",
				"type":"INTEGER",
				"length":"0",
				"nullable":"false",
				"primaryKey":"true",
				"defaultValue":""
			},
                       {
				"name":"id2",
				"type":"INTEGER",
				"length":"0",
				"nullable":"false",
				"primaryKey":"true",
				"defaultValue":""
			}
		]
}
```

Solution: 
The SQL should look like 
`CREATE COLUMN TABLE ORDERS ( ID INTEGER , ID2 INTEGER , PRIMARY KEY(ID,ID2))`

**Comment by ThuF** [comment]
Fixed with #880
