### ISSUE TITLE
[IDE Workspace] Rename doesn't rename the file on disk. After saving, the IDE keeps both old and new files.

### ISSUE THREAD

**Issue by StanZGenchev** [eclipse/dirigible#878]
**Describe the bug**
When you rename a file, it's renamed only in the web UI and not on disk. You can open the renamed file and save it but that will create two files. One with the new name and one with the old one. The old one will not be visible in the web UI but it will still be in the project folder and tracked by git.

**To Reproduce**
1. Rename a file
2. Go to the project folder in the terminal or file browser and see that it has the old name.
3. Open the file in the Web IDE and save it.
4. Go to the project folder in the terminal or file browser and see that there are now two files. One with the old name and one with the new.

**Expected behavior**
When you rename a file, the changes should be automatically saved and no duplicate files should exist.

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Browser: Firefox 88
 - Version: Dirigible 5.11

**Comment by delchev** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/6e1e2c22fd173eedc48a5ba1b0c5ca720585b2a7
