### ISSUE TITLE
[IDE Git] Unable to pull changes from origin

### ISSUE THREAD

**Issue by StanZGenchev** [eclipse/dirigible#890]
**Describe the bug**

When you go to the Git perspective and try to pull the latest changes for all repositories, it will fail with an empty error popup. From the console, the only error is `Error: $rootScope:inprog Action Already In Progress` and `$digest already in progress`.

**To Reproduce**
1. Go to the Git perspective
2. Click on any repository
3. Click on pull changes
4. Enter your username and password
5. See error

**Expected behavior**

Git pull should pull all the latest changes.

**Desktop:**
 - OS: macOS 11.4
 - Browser: Firefox 89
 - Version: Dirigible 5.11.1

**Comment by dimitarquanterall** [comment]
Please, assign it to me.

**Comment by dimitarquanterall** [comment]
Pull all button also doesn't work.

**Comment by dimitarquanterall** [comment]
Continue working in #1630 
Please, close this.
