### ISSUE TITLE
[IDE] Workspace - Some repositories don't show up or are messed up

### ISSUE THREAD

**Issue by StanZGenchev** [eclipse/dirigible#894]
**Describe the bug**
When you clone a repository which contains only a README, gitignore, a sub-folder and a project.json file, or a repository which is empty, it does not show up in the Workspace perspective. If you create an extension file, along with its JS and HTML files, commit, push them from somewhere else and pull them from Dirigible, two projects seem to be created in the Git perspective and in Workspace, you can see the project but only some files are visible. Refreshing the page, creating a new file in the project and restarting Dirigible doesn't help. You have to delete the project from both the Workspace and Git perspectives and pull it again.

**To Reproduce**
1. Create a repo with no extension files, either only a README or with a sub-folder and project.json file
2. Clone the repo using Dirigible
3. Go to the Workspace perspective
4. See bug

**Expected behavior**
Projects should be visible regardless if they are empty or not.

**Desktop:**
 - OS: macOS 11.4
 - Browser: Firefox 89
 - Version: Dirigible 5.11.2

**Comment by dimitarquanterall** [comment]
Connected to the bug described, it is impossible to clone 2 or more Git projects having first level folders with same names. Lots of projects have /src folder, for example, and only one can be cloned. 
Steps to reproduce:
1. Clone https://github.com/angular-ui/bootstrap.git This is a project containing /src folder. The following folders appear in Workspace tree after clone: /src, /misc, /template. They are messed up with the other folders (if any) and there is no visual distinction which folder to which project belongs.
2. Check the content of /src folder in Workbench perspective. It should contain files from bootstrap as seen in GitHub. 
3. Switch to Git perspective and clone another project having /src as a first level in its tree. You can use the following dummy repository to test: https://github.com/dimitarquanterall/test.git
4. You will see a git clone error telling "An error occurred while cloning repository. ..../workspace/src". Although an error is displayed, the "test" project appears in projects list in Git perspective. 
5. Switch to Workbench perspective to assure test project folders are not present in Workspace tree, as well as /src folder contains bootstrap files. 
6. Go back to Git perspective, select "test" project and pull. Project folders, excluding /src, will appear as non-git ones.
7. Back to Workbench perspective you will also see test project folders as not-git ones. The /src still contains bootstrap files. 
8. Go to Git perspective and delete project "test". 
9. Back in Workspace tree, deletion of test project's /src in fact deleted bootstrap's /src.

**Comment by StanZGenchev** [comment]
This issue has been resolved
