### ISSUE TITLE
[IDE Workbench] "Workspace" and "Import" tabs must not be closable

### ISSUE THREAD

**Issue by StanZGenchev** [eclipse/dirigible#899]
**Describe the bug**
Currently the "Workspace" and "Import" tabs are closable. There is no logical reason why they should be closable and if they are closed, the only way to open them again is to reset the entire layout. This is a bug.

**To Reproduce**
1. Go to 'Workbench'
2. Close "Workspace" or "Import"
3. See bug

**Expected behavior**
"Workspace" and "Import" tabs must not be closable.

**Desktop:**
 - OS: macOS 11.4
 - Browser: Firefox 89
 - Version: Dirigible 5.11.2

**Comment by ThuF** [comment]
Related to: https://github.com/eclipse/dirigible/issues/898
