### ISSUE TITLE
[IDE Workbench] Welcome screen should not be closable

### ISSUE THREAD

**Issue by StanZGenchev** [eclipse/dirigible#900]
**Describe the bug**
If you close the "Welcome" tab in the workbench perspective, it will be opened again the next time you open a file or reload the view.

**To Reproduce**
1. Go to 'Workbench'
2. Close 'Welcome'
3. Refresh the page or open a file from a project

**Expected behavior**
Welcome screen should not be closable and must always be visible.

**Desktop:**
 - OS: macOS 11.4
 - Browser: Firefox 89
 - Version: Dirigible 5.11.2

**Comment by ThuF** [comment]
Related to: https://github.com/eclipse/dirigible/issues/898
