### ISSUE TITLE
[API] request.getJSON() modifies request object

### ISSUE THREAD

**Issue by tdermendjiev** [eclipse/dirigible#919]
When request.getJSON() is called the [**request**](https://www.dirigible.io/api/http/request/) object is modified and cannot be used anymore.

```
let json = request.getJSON(); 
let json2 = request.getJSON(); 
```
Error is thrown.

**Expected behavior**
**json2** should be equal to **json**

 - OS: MacOS
 - Browser: Chrome
 - Version 5.11.5

**Comment by ThuF** [comment]
@tdermendjiev, I've proved a fix in the `api-http` module: https://github.com/dirigiblelabs/api-http/commit/73941eeb524ac4e6b8ad108ca40465b5563bbfa4

You can give it a try by `Cloning` (from the `Git` perspective) and `Publishing` in your Dirigible instance the following project: https://github.com/dirigiblelabs/api-http

Please let me know, if this solves the issue, so we could merge it in the main repository as well.

**Comment by ThuF** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/f58a3589e4e2091f126a3900d32f0ddb4b2b6b5e
