### ISSUE TITLE
[IDE] Expose 'set current workspace' functionality as an API call

### ISSUE THREAD

**Issue by StanZGenchev** [eclipse/dirigible#922]
**Describe the issue**
Currently it's not possible to change the selected workspace from code. The only way is to use the workspace UI drop-down. Exposing this functionality as an API call will help other perspectives such as `xsk-ide-perspective`.

**Expected behavior**
The API call should change the currently selected workspace in local storage but it should not refresh any views.

**Comment by ThuF** [comment]
Fixed with #923
