### ISSUE TITLE
[D3] No org.eclipse.dirigible logger logs in Tomcat catalina.yyyy-MM-dd.log

### ISSUE THREAD

**Issue by shturec** [eclipse/dirigible#97]
Windows 10 Enterprise
Tomcat 8.5.15
Dirigible v3

I can see all sorts of logs in the Console, i.e. it seems that both standard ConsoleAppender and Dirigible's ConsoleLoggingAppender are working just fine. 
However, the catalina.yyyy-MM-dd.log logs where STDOUT appender should be writing is missing anything but Tomcat's own logs.

The issue greatly affects productive maintainability wrt logging and tracing of D3 and its apps in the absence of centralized logging harvesting mechanism. At minimum it limits logs exploration that developers need to perform occasionally to the console, which is not the most convenient tool for that.

**Comment by delchev** [comment]
Can you please check also the localhost.yyyy-MM-dd.log?

**Comment by shturec** [comment]
nothing. Just a few errors from tomcat, wrt CXF not being able to find activemq-broker jar.

For reference, here's the debug log from logback's initialization (copy from console). There's a couple of errors.

01:06:27,117 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
01:06:27,118 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
01:06:27,120 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/C:/apache-tomcat-dirigible-3/webapps/ROOT/WEB-INF/classes/logback.xml]
01:06:27,280 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
01:06:27,301 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Adding LoggerContextListener of type [ch.qos.logback.classic.jul.LevelChangePropagator] to the object stack
01:06:27,320 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5067e80 - Setting level of jul logger [org.apache.catalina.core.ContainerBase.[Catalina].[localhost]] to null
01:06:27,322 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5067e80 - Propagating DEBUG level on Logger[ROOT] onto the JUL framework
01:06:27,322 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Starting LoggerContextListener
01:06:27,326 |-INFO in ch.qos.logback.core.joran.action.StatusListenerAction - Added status listener of type [ch.qos.logback.core.status.OnConsoleStatusListener]
01:06:27,342 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
01:06:27,357 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
01:06:27,369 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
01:06:27,511 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [org.eclipse.dirigible.runtime.ide.console.service.ConsoleLoggingAppender]
01:06:27,515 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ConsoleLoggingAppender]
01:06:27,518 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@19:12 - no applicable action for [encoder], current ElementPath  is [[configuration][appender][encoder]]
01:06:27,519 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@20:13 - no applicable action for [pattern], current ElementPath  is [[configuration][appender][encoder][pattern]]
01:06:27,521 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.dirigible] to DEBUG
01:06:27,521 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5067e80 - Propagating DEBUG level on Logger[org.eclipse.dirigible] onto the JUL framework
01:06:27,524 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.eclipse.dirigible] to false
01:06:27,525 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[org.eclipse.dirigible]
01:06:27,528 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ConsoleLoggingAppender] to Logger[org.eclipse.dirigible]
01:06:27,529 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
01:06:27,530 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5067e80 - Propagating INFO level on Logger[ROOT] onto the JUL framework
01:06:27,532 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
01:06:27,534 |-ERROR in ch.qos.logback.core.joran.action.ShutdownHookAction - Missing class name for shutdown hook. Near [shutdownHook] line 33
01:06:27,534 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
01:06:27,538 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@59c417f5 - Registering current configuration as safe fallback point
01:06:27,046 |-INFO in ch.qos.logback.classic.servlet.LogbackServletContainerInitializer@2a0e67ce - Adding an instance of  class ch.qos.logback.classic.servlet.LogbackServletContextListener to the current web-app

**Comment by delchev** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/c10f402efb0932fd0ff67262103d3c731de0f7f1
