### ISSUE TITLE
[Documentation] Description of CSV editor and CSVIM

### ISSUE THREAD

**Issue by danachkov** [eclipse/dirigible#987]
We need to describe the new features CSV editor and CSVIM in the Eclipse Dirigible Help Portal documentation.

**Comment by ThuF** [comment]
Another editor to be taken into account as well: https://github.com/eclipse/dirigible/issues/995

**Comment by slavipande** [comment]
We just need to check if any other screenshots will be useful to add and should be ready to close. 
[CSV Editor in the Help](https://www.dirigible.io/help/development/ide/editor-csv/)

**Comment by slavipande** [comment]
@danachkov,
I double-checked but I don't think any other screenshots are needed. 

We can close the issue once descriptions of both CSV editor and CSVIM are ready.

Best regards,
Svetoslav

**Comment by danachkov** [comment]
Both topics have been published:
- [CSV Editor](https://www.dirigible.io/help/development/ide/editor-csv/)
- [CSVIM Editor](https://www.dirigible.io/help/development/ide/editor-csvim/)
