### ISSUE TITLE
[Workspace] Mark modified/new/deleted files in Workspace View

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#988]
<img width="219" alt="Screen Shot 2021-07-27 at 15 52 36" src="https://user-images.githubusercontent.com/6852373/127156858-1f809777-1f0d-4754-ac26-9cb0ddb225a1.png">

Can be used '>' symbol as a prefix for the modified/new/deleted files like in Eclipse

**Comment by ThuF** [comment]
I guess this should be applied only for Git projects?
