### ISSUE TITLE
[Editors] CSV editor right click not working on WebKit browsers

### ISSUE THREAD

**Issue by StanZGenchev** [eclipse/dirigible#992]
**Describe the bug**
Right click in the CSV editor, does not work in Chrome, Safari and other WebKit browsers.

**To Reproduce**
1. Open Dirigible in Chrome
2. Open a csv file
3. Try to right click

**Expected behavior**
The context menu should always appear, regardless of browser.

**Desktop:**
 - OS: macOS 11.5
 - Browser: Chrome 92
 - Version: Dirigible 5.12.6

**Comment by ThuF** [comment]
Fixed with: https://github.com/eclipse/dirigible/pull/994
