### ISSUE TITLE
[Editors] Disable column drag while editing

### ISSUE THREAD

**Issue by StanZGenchev** [eclipse/dirigible#993]
**Describe the bug**
When editing a column title, the action of text selection using the mouse is recognized as column drag.

**To Reproduce**
1. Open a csv file
2. Start editing a column title
3. Try to select the text in the input from start to end

**Expected behavior**
Drag and reorder functionality should be disabled while editing column titles.

**Desktop:**
 - OS: macOS 11.5
 - Browser: Chrome 92
 - Version: Dirigible 5.12.6

**Comment by ThuF** [comment]
Fixed with: https://github.com/eclipse/dirigible/pull/994
