### ISSUE TITLE
[Documentation] Description of Access editor

### ISSUE THREAD

**Issue by ThuF** [eclipse/dirigible#995]
We need to describe the Access editor in the Eclipse Dirigible Help Portal documentation.

We also should make clear how to expose **Public** endpoints:
- Adding the **public** role
- Access the resource (frontend *.htm, *.css, ...) via `/public/` endpoint instead of `/web/` endpoint (e.g. `http://localhost:8080/services/v4/public/my-project/index.html`)

**Comment by slavipande** [comment]
Access editor described. Here's a link to the page in the Help: [Access Editor](https://www.dirigible.io/help/development/ide/editor-access/).

Related commits:
- https://github.com/dirigible-io/dirigible-io.github.io/commit/7dfa50d667fb63b65b734f1271f3fbb8d22b93f5
- https://github.com/dirigible-io/dirigible-io.github.io/commit/7ac7b12fe6ae57523cfde00c1866bb4ce2d6b895

Best regards,
Svetoslav

**Comment by ThuF** [comment]
Thanks @slavipande, the [Access Editor](https://www.dirigible.io/help/development/ide/editor-access/) page is great!!!
