### ISSUE TITLE
[OData] Deep inserts / update / delete

### ISSUE THREAD

**Issue by delchev** [eclipse/dirigible#997]
Deep inserts / update / delete support

**Comment by mit-ko** [comment]
This should work with the 6.0.0 snapshot version

**Comment by ThuF** [comment]
@mit-ko could you share a sample project and sample request(s), so we could test it out?

**Comment by mit-ko** [comment]
There is one example in ODataSQLProcessorTest method testCreateEntityWithReferenceID

**Comment by delchev** [comment]
done
